groups/flowDefinitions/objects/TW1_Operador__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Senha__c</fullName>
        <externalId>true</externalId>
        <label>Senha</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Operadores</relationshipLabel>
        <relationshipName>Operadores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operador</fullName>
                </value>
                <value>
                    <fullName>Coordenador</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operador</label>
    <nameField>
        <label>Nome do Operador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CordenadorManager.cls
/******************************************************************************************************
Author  	: Wellington Rodrigues
Date    	: 16/01/2018
Purpose 	: Api Rest para buscar informações do Cordenador para a aplicação de promoção
*******************************************************************************************************/
@RestResource(urlMapping='/Cordenador/*')
global with sharing class CordenadorManager {
    
    @HttpGet
    global static List<TW1_Operador__c> getCordenadorPorShopping(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        List<TW1_Operador__c> listaCordenadorPorShopping = new List<TW1_Operador__c>();
        
        String vaIdShopping = req.params.get('IdShopping');
            String vaIdOperador= req.params.get('IdOperador');
        String vaSenha = req.params.get('SenhaOperaodor');
        
        If(vaIdShopping != null && vaIdShopping != '' && vaIdShopping != 'null'){
            
            try{
                listaCordenadorPorShopping = [
                    select 
                    id,
                    name,
                    TW1_Shopping__c
                    from 
                    TW1_Operador__c
                    where TW1_Tipo__c='Coordenador' and TW1_Shopping__c=:vaIdShopping
                ];  
                return listaCordenadorPorShopping; 
                
            }catch(exception e){return null;}}
        
        If(vaIdOperador != null && vaIdOperador != '' && vaIdOperador != 'null' || vaSenha != null && vaSenha != '' && vaSenha != 'null'){
            
            try{
                listaCordenadorPorShopping = [
                    select 
                    id,
                    name,
                    TW1_Shopping__c,
                    TW1_Senha__c
                    from 
                    TW1_Operador__c
                    where id=:vaIdOperador and TW1_Senha__c=:vaSenha limit 1
                ];  
                return listaCordenadorPorShopping; 
                
            }catch(exception e){return null;}
        }

        return listaCordenadorPorShopping;
    }
    
}