groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>Sigla</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Tw1_Ancar_ShoppingManager_tst.cls
@istest
private class Tw1_Ancar_ShoppingManager_tst {
	
     static testMethod void testdoShopping() {
       
        TW1_Shopping__c shopping = new TW1_Shopping__c();
    		shopping.TW1_SGL_Empreendimento__c = 'BPS';
        	shopping.Name = 'Barra Shopping';
        
         Insert shopping;

        // COMEÇA O TESTE
        string nome= '';
        string Cpf = '';
        
        //+'&nome='+Nome+'&cpf='+Cpf

        RestRequest request = new RestRequest();
        request.requestUri ='/services/apexrest/Shopping';
        
        //request.addParameter('Id', acc.Id);
        //request.addParameter('IdCliente', acc.Id);
        //request.addParameter('Valor', '200');
        
        //request.addParameter('IdShopping', shopping.Id);
        //request.addParameter('IdOperador', operador.Id);
        //request.addParameter('SenhaOperaodor', operador.TW1_Senha__c);

        request.httpMethod = 'GET';
		
        RestContext.request = request;
         System.debug(RestContext.request);
        
        ShoppingManager.getShoppings();

    }
}