groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Stand__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Stands</relationshipLabel>
        <relationshipName>Stands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stand</label>
    <nameField>
        <label>Nome do Stand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Terminal__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Terminais</relationshipLabel>
        <relationshipName>Terminais</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Stand__c</fullName>
        <label>Stand</label>
        <referenceTo>TW1_Stand__c</referenceTo>
        <relationshipLabel>Terminais</relationshipLabel>
        <relationshipName>Terminais</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Terminal</label>
    <nameField>
        <label>Nome do Terminal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terminais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UtilFluxoCaixaManager.cls
/******************************************************************************************************
Author  	: Leonardo Façanha
Date    	: 05/01/2017
Purpose 	: Api Rest para buscar informações do fluxo de Caixa para a aplicação de promoção
*******************************************************************************************************/
@RestResource(urlMapping='/UtilFluxoCaixa/*')
global with sharing class UtilFluxoCaixaManager {
    
    @HttpGet
    global static responseWrapper getStandTerminalPorId(){
        RestRequest req = RestContext.request;
        responseWrapper rew = new responseWrapper();
        
        String vaShoppingId = req.params.get('IdShopping');
        String vaStandId = req.params.get('IdStand');
        
        if(vaShoppingId != null && vaShoppingId != '' && vaShoppingId != 'null'){
            rew.Stands = [Select Id,Name From TW1_Stand__c where TW1_Shopping__c =:vaShoppingId];
            Return rew;   
        }
        else{
            rew.Terminais = [Select Id,Name,TW1_Stand__c From TW1_Terminal__c where TW1_Stand__c =:vaStandId];
            Return rew;               
        }        
    }
    
    
    global class responseWrapper
    {
        public List<TW1_Stand__c> Stands;
        public List<TW1_Terminal__c> Terminais;
    }   
}