objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fidelidade</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Esse cliente já possui registro de Fidelidade criado. Não é possível criar um novo registro.</errorMessage>
            <filterItems>
                <field>TW1_Fidelidade__c.TW1_Nome_Cliente__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cliente</relationshipLabel>
        <relationshipName>TW1_Relation_Fidelidade_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Cartoes_Estacionamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio__c</fullName>
        <label>Data início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Fidelidade__c</fullName>
        <label>Número Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cartões Estacionamento</relationshipLabel>
        <relationshipName>Cart_es_Estacionamento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Inativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cartão Estacionamento</label>
    <nameField>
        <label>Número do cartão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões Estacionamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Fidelidade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Modalidade__c</fullName>
        <label>Modalidade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Nome_Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nome do Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fidelidade</relationshipLabel>
        <relationshipName>Fidelidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Saldo__c</fullName>
        <label>Saldo</label>
        <summarizedField>TW1_Historico__c.TW1_Pontos__c</summarizedField>
        <summaryForeignKey>TW1_Historico__c.TW1_Fidelidade__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fidelidade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número Fidelidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidelidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Tw1_Ancar_IntegracaoCartao_Handler_cls.cls
global with sharing class Tw1_Ancar_IntegracaoCartao_Handler_cls {
    
    @future
    public static void sendWithFuture(){
        executeJob();
    } 
    
    @testVisible
    private static void executeJob(){ 
        
        Anc_Utils_cls.LogToSystemDebug('Inicio do processamento Tw1_Ancar_IntegracaoCartao_Handler_cls.sendWithFuture');
        try 
        {  
            // get data 
            Anc_Utils_cls.LogToSystemDebug('obtendo dados...');
            getDataToProcess();   
            Anc_Utils_cls.LogToSystemDebug('processando informação...');
        }
        catch(Anc_Utils_cls.Cal_Exception e)
        {   
            System.debug('Tw1_Ancar_IntegracaoCartao_Handler_cls.sendWithFuture error: ' + e.getMessage()); 
        }
        finally{
            if(!Test.isRunningTest())
                scheaduleJobAgain();
        }  
        Anc_Utils_cls.LogToSystemDebug('Fim do processamento Tw1_Ancar_IntegracaoCartao_Handler_cls.sendWithFuture');
        
    }
    
    private static void getDataToProcess(){ 
        
        string stringAttac = '';
        List<TW1_Fidelidade__c> Listfidelidade = [select TW1_Modalidade__c,TW1_Saldo__c,TW1_Nome_Cliente__c from TW1_Fidelidade__c where Tw1_Modalidade__c != 'Prospect'];
        Map<Id,TW1_Fidelidade__c> Listfidelidadee = new Map<Id,TW1_Fidelidade__c>(Listfidelidade);
		List<TW1_Cartoes_Estacionamento__c> Listcartao = [select Id,TW1_Numero__c,TW1_Data_Fim__c,TW1_Data_inicio__c,TW1_Status__c,TW1_Numero_Fidelidade__c from TW1_Cartoes_Estacionamento__c where TW1_Numero_Fidelidade__c IN :Listfidelidadee.keySet()];
        List<Account> Listacc = [Select Id,Name from Account where recordtype.Name = 'Conta pessoal padrão'];

        for(TW1_Fidelidade__c fidelidade : Listfidelidade)
        {
            for(TW1_Cartoes_Estacionamento__c cartao : Listcartao)
            {	
                if(cartao.TW1_Numero_Fidelidade__c == fidelidade.Id){
                Account acc;
                    for(Account item:Listacc)
                    {
                        if(item.Id == fidelidade.TW1_Nome_Cliente__c)
                           acc = item;
                    }
                date dataIni = cartao.TW1_Data_inicio__c;
                date dataFim = cartao.TW1_Data_Fim__c;
                
                string Iniciodia = string.valueOf(dataIni.day());
                string InicioMes = string.valueOf(dataIni.month());
                string InicioAno = string.valueOf(dataIni.year());
                string Fimdia = string.valueOf(dataFim.day());
                string FimMes = string.valueOf(dataFim.month());
                string FimAno = string.valueOf(dataFim.year());
                
                string numero = CompletarCodigoDeBarras(cartao.TW1_Numero__c);
                
                
                string stringAttachment = '20,'; 
                stringAttachment = stringAttachment +  (numero + cartao.TW1_Numero__c);
                stringAttachment = stringAttachment + (',' + string.valueOf( acc.Name));
                stringAttachment = stringAttachment + (',FIDELIDADE ' + string.valueOf(fidelidade.TW1_Modalidade__c));
                stringAttachment = stringAttachment + (',' + Iniciodia + InicioMes + InicioAno);
                stringAttachment = stringAttachment + (',' + Fimdia + FimMes + FimAno + ',');
                stringAttachment = stringAttachment + (cartao.TW1_Status__c == 'Ativo'? 'A' : 'I');
                stringAttachment = stringAttachment + '\n';
                
            	stringAttac = stringAttac + stringAttachment;
                }
            }
        }
        
       // if(!Test.isRunningTest()){ 
            Cal_EmailUtils_cls.sendEmail( new String[] {'estacionamento.barra@riodesign.com.br' },null,'Informações do Cliente - Cartão Estacionamento', 'teste Ancar envio de email', '<h3>Ancar - Integração Cartão Estacionamento</h3>',stringAttac,'CartaoEstacionamento.txt');
        //}
    }
    
    public static String CompletarCodigoDeBarras(String paCdBarras){
        String n ='';
        for (integer i=paCdBarras.length();i<=7;i++){
            n+='0';
        }	
        return n;
    }
    
    private static void scheaduleJobAgain(){
        //Produção
        Anc_ScheaduleUtils_cls.scheadule('Tw1_Ancar_IntegracaoCartao_sch', DateTime.now().addMinutes(480));
    }
}