objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fidelidade</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Esse cliente já possui registro de Fidelidade criado. Não é possível criar um novo registro.</errorMessage>
            <filterItems>
                <field>TW1_Fidelidade__c.TW1_Nome_Cliente__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cliente</relationshipLabel>
        <relationshipName>TW1_Relation_Fidelidade_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Cartoes_Estacionamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Numero_Fidelidade__c</fullName>
        <label>Número Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cartões Estacionamento</relationshipLabel>
        <relationshipName>Cart_es_Estacionamento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <type>AutoNumber</type>
    </fields>
    <label>Cartão Estacionamento</label>
    <nameField>
        <label>Número do cartão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões Estacionamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Fidelidade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Nome_Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nome do Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fidelidade</relationshipLabel>
        <relationshipName>Fidelidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fidelidade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número Fidelidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidelidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Tw1_Cartao_Estacio_Ctr_Reempressao.cls
public class Tw1_Cartao_Estacio_Ctr_Reempressao {
    
    public TW1_Cartao_Estacio_Serv cartaoService = new TW1_Cartao_Estacio_Serv();
    
    public TW1_Cartoes_Estacionamento__c vaCartao {get;set;}
    public TW1_Fidelidade__c vaFidelidade {get;set;}
    public Account vaAccount {get;set;}
    public string CompletarDigitos {get;set;}
    private final TW1_Cartoes_Estacionamento__c acct;
    
    
    public Tw1_Cartao_Estacio_Ctr_Reempressao(ApexPages.StandardController stdController) {
        this.acct = (TW1_Cartoes_Estacionamento__c)stdController.getRecord();
    }
    
    public String CompletarCodigoDeBarras(String paCdBarras){
        String n ='';
        for (integer i=paCdBarras.length();i<=7;i++){
            n+='0';
        }	
        return n;
    }
    
    public void GerarPdf(){
        String idCartaoEstacionamento = ApexPages.currentPage().getParameters().get('id');
        GerarCartao(idCartaoEstacionamento);
    }
    
    public void GerarCartao(String paIdCartaoEstacionamento){
        List<TW1_Cartoes_Estacionamento__c> vaCartaoo = cartaoService.getCartaoEstacionamento(paIdCartaoEstacionamento);
        vaCartao = vaCartaoo.get(0);
        vaFidelidade = cartaoService.getFidelidade(vaCartao.TW1_Numero_Fidelidade__c);
        vaAccount = cartaoService.geAccount(vaFidelidade.TW1_Nome_Cliente__c);
        CompletarDigitos 	= CompletarCodigoDeBarras(vaCartao.TW1_Numero__c);
    }
}