objects/Account.object
<CustomObject>
    <fields>
        <fullName>CEP__c</fullName>
        <label>CEP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Av_Rua__c</fullName>
        <label>Av./Rua</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Bairro__c</fullName>
        <label>Bairro</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <externalId>true</externalId>
        <label>CPF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Celular__c</fullName>
        <label>Celular</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>TW1_Cidade__c</fullName>
        <label>Cidade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Complemento__c</fullName>
        <label>Complemento</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Email_comercial__c</fullName>
        <label>E-mail comercial</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TW1_Estado__c</fullName>
        <label>Estado</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_ID_Externo__c</fullName>
        <externalId>true</externalId>
        <label>ID Externo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Marca_pretendida__c</fullName>
        <label>Marca pretendida</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_fantasia__c</fullName>
        <label>Nome Fantasia</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Pais__c</fullName>
        <label>País</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afeganistão</fullName>
                </value>
                <value>
                    <fullName>África do Sul</fullName>
                </value>
                <value>
                    <fullName>Albânia</fullName>
                </value>
                <value>
                    <fullName>Alemanha</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antiga e Barbuda</fullName>
                </value>
                <value>
                    <fullName>Arábia Saudita</fullName>
                </value>
                <value>
                    <fullName>Argélia</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Arménia</fullName>
                </value>
                <value>
                    <fullName>Austrália</fullName>
                </value>
                <value>
                    <fullName>Áustria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijão</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bangladexe</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Barém</fullName>
                </value>
                <value>
                    <fullName>Bélgica</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benim</fullName>
                </value>
                <value>
                    <fullName>Bielorrússia</fullName>
                </value>
                <value>
                    <fullName>Bolívia</fullName>
                </value>
                <value>
                    <fullName>Bósnia e Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botsuana</fullName>
                </value>
                <value>
                    <fullName>Brasil</fullName>
                    <default>true</default>
                    <label>Brasil</label>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgária</fullName>
                </value>
                <value>
                    <fullName>Burquina Faso</fullName>
                </value>
                <value>
                    <fullName>Burúndi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Razao_Social__c</fullName>
        <label>Razão Social</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Contas (Shopping)</relationshipLabel>
        <relationshipName>Contas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Telefone_comercial__c</fullName>
        <label>Telefone comercial</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TW1_Cotacao_sincronizada__c</fullName>
        <label>Cotação sincronizada</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Marca_pretendida__c</fullName>
        <label>Marca pretendida</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Oportunidade_aprovada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Oportunidade aprovada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Prazo__c</fullName>
        <label>Prazo (dias)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Frio</fullName>
                    <default>true</default>
                    <label>Frio</label>
                </value>
                <value>
                    <fullName>Morno</fullName>
                </value>
                <value>
                    <fullName>Quente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Cidade__c</fullName>
        <label>Cidade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AC</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>CE</fullName>
                </value>
                <value>
                    <fullName>DF</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MG</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PB</fullName>
                </value>
                <value>
                    <fullName>PE</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>RJ</fullName>
                </value>
                <value>
                    <fullName>RN</fullName>
                </value>
                <value>
                    <fullName>RO</fullName>
                </value>
                <value>
                    <fullName>RR</fullName>
                </value>
                <value>
                    <fullName>RS</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>TO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Id_Externo_VS__c</fullName>
        <externalId>true</externalId>
        <label>Id Externo VS</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TW1_Id_Externo__c</fullName>
        <externalId>true</externalId>
        <label>Id Externo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>Sigla</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/User.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <label>Shopping</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NORTH SHOPPING JOQUEI</fullName>
                </value>
                <value>
                    <fullName>NORTH SHOPPING FORTALEZA</fullName>
                </value>
                <value>
                    <fullName>VIA SUL SHOPPING</fullName>
                </value>
                <value>
                    <fullName>NORTH SHOPPING MARACANAU</fullName>
                </value>
                <value>
                    <fullName>SHOPPING CONJUNTO NACIONAL</fullName>
                </value>
                <value>
                    <fullName>PANTANAL SHOPPING</fullName>
                </value>
                <value>
                    <fullName>SHOPPING NOVA IGUAÇU</fullName>
                </value>
                <value>
                    <fullName>RIO DESIGN LEBLON</fullName>
                </value>
                <value>
                    <fullName>RIO DESIGN BARRA</fullName>
                </value>
                <value>
                    <fullName>SHOPPING NOVA AMERICA</fullName>
                </value>
                <value>
                    <fullName>BOTAFOGO PRAIA SHOPPING</fullName>
                </value>
                <value>
                    <fullName>DOWNTOWN</fullName>
                </value>
                <value>
                    <fullName>BOULEVARD RIO SHOPPING</fullName>
                </value>
                <value>
                    <fullName>ANCAR</fullName>
                </value>
                <value>
                    <fullName>NATAL SHOPPING</fullName>
                </value>
                <value>
                    <fullName>PORTO VELHO SHOPPING</fullName>
                </value>
                <value>
                    <fullName>SHOPPING PARQUE DAS BANDEIRAS</fullName>
                </value>
                <value>
                    <fullName>GOLDEN SQUARE SHOPPING</fullName>
                </value>
                <value>
                    <fullName>CENTERVALE SHOPPING</fullName>
                </value>
                <value>
                    <fullName>SHOPPING ELDORADO</fullName>
                </value>
                <value>
                    <fullName>SHOPPING METRO ITAQUERA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TW1_Ancar_OpportunityMockGenerator_cls.cls
public class TW1_Ancar_OpportunityMockGenerator_cls {
    
    public static TW1_Ancar_wrapRecodtypes rec = new TW1_Ancar_wrapRecodtypes();
    
    public static List<RecordType> recordMarca = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Marca LIMIT 1];
    
    public static Account criaMarca(){
        list<RecordType> recMarca = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Marca Limit 1];   
        
        Account vaMarca = new Account();
        vaMarca.Name = 'Apex Text Marca';
        vaMarca.RecordTypeId = recMarca.get(0).Id;
        vaMarca.TW1_ID_Externo__c = 'TextoId 20';
        vaMarca.TW1_Status__c = 'Ativa';
        Insert vaMarca;
        return vaMarca;
        
    }
    public static Account criaCliente(String cpf){
        list<RecordType> recContato_PF = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Contato_Comercial_PF Limit 1];   
        
        Account vaContato = new Account();
        vaContato.TW1_ID_Externo__c = 'Texto id externo';
        vaContato.Firstname = 'Text(40)';
        vaContato.LastName = 'Text(80)';
        vaContato.TW1_CPF__c = cpf;
        vaContato.TW1_Marca_pretendida__c = 'Text(80)';
        vaContato.TW1_Telefone_comercial__c = '26090000';
        vaContato.TW1_Celular__c = '26090000';
        vaContato.TW1_Email_comercial__c = 'email@email.com';
        vaContato.CEP__c = 8;
        vaContato.TW1_Av_Rua__c = 'Text(100)';
        vaContato.TW1_Numero__c = 8;
        vaContato.TW1_Complemento__c = 'Text(50)';
        vaContato.TW1_Bairro__c = 'Text(50)';
        vaContato.TW1_Cidade__c = 'Text(50)';
        vaContato.TW1_Estado__c = 'Text(20)';
        vaContato.TW1_Pais__c = 'Brasil';
        vaContato.TW1_Razao_Social__c = 'Text(100)';
        vaContato.TW1_Nome_fantasia__c = 'Text(100)';
        vaContato.TW1_Status__c = 'Ativa';
        vaContato.RecordTypeId = recContato_PF.get(0).Id;        
        
        Insert vaContato;
        System.debug('vaContato:'+vaContato);
        return vaContato;
        
    }
    public static TW1_Shopping__c criaShopping(String uniqueExternalID){
        
        System.debug('uniqueExternalID: ' + uniqueExternalID);
        TW1_Shopping__c vaShopping = new TW1_Shopping__c();
        vaShopping.Name = 'Shopping Teste';
        vaShopping.TW1_SGL_Empreendimento__c='ST';
        vaShopping.TW1_Id_Externo_VS__c = uniqueExternalID;
        insert vaShopping;
        system.debug('Shopping: ' + vaShopping);
        return vaShopping;        
    }
    public static User criaOwner(String uniqueUsername)
    {
        Profile pf= [Select Id from profile where Name='System Administrator' or Name='Administrador do sistema']; 
        
        User user =new User(
            firstname = 'ABC', 
            lastName = 'XYZ', 
            email = uniqueUsername, 
            Username = uniqueUsername, 
            EmailEncodingKey = 'ISO-8859-1', 
            Alias = uniqueUsername.substring(0, 4), 
            TimeZoneSidKey = 'America/Los_Angeles', 
            LocaleSidKey = 'en_US', 
            LanguageLocaleKey = 'en_US', 
            ProfileId = pf.Id
        ); 
        insert user;
        
        User manager = new User(
            firstname = 'ABC', 
            lastName = 'XYZ', 
            email = 'manager' + uniqueUsername, 
            Username = 'manager' + uniqueUsername, 
            EmailEncodingKey = 'ISO-8859-1', 
            Alias = uniqueUsername.substring(0, 4), 
            TimeZoneSidKey = 'America/Los_Angeles', 
            LocaleSidKey = 'en_US', 
            LanguageLocaleKey = 'en_US', 
            ProfileId = pf.Id
        ); 
        insert manager;
        
        user.ManagerId = manager.Id;
        update user;
        
        return user;
    }
    
    public static Opportunity getFeiraoMock()
    {
        List<RecordType> recordFeirao = [SELECT Id FROM RecordType WHERE Name = :rec.rec_feiras];
        
        //Criando uma oportunidade de feiras e eventos        
        Opportunity opportunity = new Opportunity(       
            RecordTypeId = recordFeirao[0].Id,            
            Name = 'ApexTest Opportunity Feirao',
            TW1_Cotacao_sincronizada__c = null,
            TW1_Data_inicio_de_vigencia__c = Date.today().AddDays(2),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(3),
            StageName = 'Em negociação',
            TW1_Prazo__c = 0,
            CloseDate = Date.newInstance(2018,04,18),
            TW1_Oportunidade_aprovada__c = true,
            TW1_Marca__c = criaMarca().Id,
            TW1_Shopping__c = criaShopping('ID_EXTERNO').Id,
            AccountId = criaCliente('56430245519').Id,
            OwnerId = criaOwner('testAncar@test.com.br').Id //ownerId
        );                  
        insert opportunity; 
        
        return opportunity;
    }
    
    public static Opportunity getMallMock()
    {
        List<RecordType> recordMall = [SELECT Id FROM RecordType WHERE Name = :rec.rec_mall];
                
        //Criando uma oportunidade de Mall
        Opportunity opportunity = new Opportunity(        
            Name = 'ApexTest Opportunity Mall',
            TW1_Cotacao_sincronizada__c = null,
            TW1_Data_inicio_de_vigencia__c = Date.today().AddDays(9),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(15),
            StageName = 'Em negociação',
            TW1_Prazo__c = 0,
            CloseDate = Date.today(),
            TW1_Oportunidade_aprovada__c = true,
            RecordTypeId = recordMall[0].Id,  
            TW1_Marca__c = criaMarca().Id,
            TW1_Shopping__c = criaShopping('ID_EXTERNO').Id,
            AccountId = criaCliente('56430245519').Id,
            OwnerId = criaOwner('testAncar@test.com.br').Id //ownerId
        );
        insert opportunity; 
        
        return opportunity;
    }
    
    public static Opportunity getMidiaMock()
    {
        System.debug('Mídia Mock');
        List<RecordType> recordMidia = [SELECT Id FROM RecordType WHERE Name = :rec.rec_midia];
         
        //Criando uma oportunidade de Mídia        
        Opportunity opportunity = new Opportunity(              
            Name = 'ApexTest Opportunity Mídia',
            TW1_Cotacao_sincronizada__c = null,
            TW1_Data_inicio_de_vigencia__c = Date.today().AddDays(9),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(10),
            StageName = 'Em negociação',
            TW1_Prazo__c = 0,
            CloseDate = Date.today(),   
            TW1_Oportunidade_aprovada__c = true, 
            RecordTypeId = recordMidia[0].Id, 
            TW1_Marca__c = criaMarca().Id,
            TW1_Shopping__c = criaShopping('ID_EXTERNO').Id,
            TW1_Possui_midia_inaugural__c = false,
            AccountId = criaCliente('56430245519').Id,
            OwnerId = criaOwner('testAncar@test.com.br').Id
        );                  
        insert opportunity;
        
        return opportunity;
    }
    
    public static Opportunity getLojaMock()
    {        
        List<RecordType> recordLoja = [SELECT Id FROM RecordType WHERE Name = :rec.rec_loja];

        //Criando uma oportunidade
        Opportunity opportunity = new Opportunity(                 
            Name = 'ApexTest Opportunity 1',
            TW1_Cotacao_sincronizada__c = null,
            TW1_Data_inicio_de_vigencia__c = Date.today().AddDays(9),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(10),
            StageName = 'Em negociação',
            CloseDate = Date.today(),  
            TW1_Oportunidade_aprovada__c = true,
            RecordTypeId = recordLoja[0].Id, 
            TW1_Marca__c = criaMarca().Id,
            TW1_Shopping__c = criaShopping('ID_EXTERNO').Id,
            AccountId = criaCliente('56430245519').Id,
            TW1_Id_VS__c = 'ID_Opp_VS',
            NextStep = 'Texto 255',
            Description = 'Long Text Area(32000)',
            Loss_Reason__c = 'Price',
            TW1_Prazo__c = 1234567891,
            TW1_Status__c = 'Quente',
            TW1_Valor__c = 1234567812345678.22,
            TW1_VGL_faturado__c = 1234567812345678.22,
            TW1_ABL_faturada__c = 1234567812345678.22,
            TW1_Comissao__c = 1234567812345678.22,
            TW1_Descricao_erro_integracao__c = 'Text Area(255)',
            TW1_Quantidade_de_propriedades__c = 1234567891,
            TW1_VGL_AMM__c = 1234567812345678.22,
            TW1_VGL_total__c = 1234567812345678.22,
            TW1_Etapa__c = 'Texto',
            TW1_Descricao_da_etapa__c = 'Texto',
            OwnerId = criaOwner('testAncar@test.com.br').Id //ownerId        
        );
        insert opportunity; 
        
        opportunity = [SELECT Id, Name, TW1_Cotacao_sincronizada__c, TW1_Data_inicio_de_vigencia__c, 
                       TW1_Data_fim_de_vigencia__c, StageName, CloseDate, TW1_Oportunidade_aprovada__c, 
                       RecordTypeId, TW1_Marca__c, TW1_Shopping__c, AccountId, OwnerId
                       FROM Opportunity
                       WHERE Id = :opportunity.Id];
        
        return opportunity;
    }
    
    public static Opportunity getMidiaUniqueOwnerMock(String ownerUniqueUsername, String cpf)
    {        
        List<RecordType> recordMidia = [SELECT Id FROM RecordType WHERE Name = :rec.rec_midia];
 
        //Criando uma oportunidade
        Opportunity opportunity = new Opportunity(                 
            Name = 'ApexTest Opportunity 1',
            TW1_Cotacao_sincronizada__c = null,
            TW1_Data_inicio_de_vigencia__c = Date.today().AddDays(9),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(10),
            StageName = 'Em negociação',
            CloseDate = Date.today(),  
            TW1_Oportunidade_aprovada__c = true,
            RecordTypeId = recordMidia[0].Id, 
            TW1_Marca__c = criaMarca().Id,
            TW1_Shopping__c = criaShopping(ownerUniqueUsername.substring(0, 10)).Id,
            AccountId = criaCliente(cpf).Id,
            TW1_Id_VS__c = 'ID_Opp_VS',
            NextStep = 'Texto 255',
            Description = 'Long Text Area(32000)',
            Loss_Reason__c = 'Price',
            TW1_Prazo__c = 1234567891,
            TW1_Status__c = 'Quente',
            TW1_Valor__c = 1234567812345678.22,
            TW1_VGL_faturado__c = 1234567812345678.22,
            TW1_ABL_faturada__c = 1234567812345678.22,
            TW1_Comissao__c = 1234567812345678.22,
            TW1_Descricao_erro_integracao__c = 'Text Area(255)',
            TW1_Quantidade_de_propriedades__c = 1234567891,
            TW1_VGL_AMM__c = 1234567812345678.22,
            TW1_VGL_total__c = 1234567812345678.22,
            TW1_Etapa__c = 'Texto',
            TW1_Descricao_da_etapa__c = 'Texto',
            OwnerId = criaOwner(ownerUniqueUsername).Id        
        );
        insert opportunity; 
        
        opportunity = [SELECT Id, Name, TW1_Cotacao_sincronizada__c, TW1_Data_inicio_de_vigencia__c, 
                       TW1_Data_fim_de_vigencia__c, StageName, CloseDate, TW1_Oportunidade_aprovada__c, 
                       RecordTypeId, TW1_Marca__c, TW1_Shopping__c, AccountId, OwnerId
                       FROM Opportunity
                       WHERE Id = :opportunity.Id];
        
        return opportunity;
    }
}