objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_Nome_fantasia__c</fullName>
        <label>Nome Fantasia</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Ramo_de_atividade__c</fullName>
        <label>Ramo de atividade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AGÊNCIA DE VIAGENS</fullName>
                </value>
                <value>
                    <fullName>ALIMENTAÇÃO</fullName>
                </value>
                <value>
                    <fullName>ALIMENTOS ESPECIAIS(CONGELADOS/DIETÉTICOS/NATURAIS</fullName>
                </value>
                <value>
                    <fullName>ARMARINHO</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS DIVERSOS</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS DO LAR</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS ESPORTIVOS</fullName>
                </value>
                <value>
                    <fullName>BAZAR</fullName>
                </value>
                <value>
                    <fullName>BOLICHE</fullName>
                </value>
                <value>
                    <fullName>BRINQUEDOS</fullName>
                </value>
                <value>
                    <fullName>CABELEIREIRO, CLÍNICAS DE ESTÉTICA E PODOLOGIA)</fullName>
                </value>
                <value>
                    <fullName>CALÇADOS</fullName>
                </value>
                <value>
                    <fullName>CASA DE SHOWS</fullName>
                </value>
                <value>
                    <fullName>CENTRO DE CONVENÇÕES/SALA DE CONVENÇÕES</fullName>
                </value>
                <value>
                    <fullName>CHAVEIRO</fullName>
                </value>
                <value>
                    <fullName>CINEMAS</fullName>
                </value>
                <value>
                    <fullName>CONSERTOS</fullName>
                </value>
                <value>
                    <fullName>CONSTRUÇÃO E DECORAÇÃO(NOVO)</fullName>
                </value>
                <value>
                    <fullName>CORREIO</fullName>
                </value>
                <value>
                    <fullName>DELICATESSEN(QUEIJOS/FRIOS/BEBIDAS)</fullName>
                </value>
                <value>
                    <fullName>DIVERSÕES(PARQUES/VIDEOGAMES)</fullName>
                </value>
                <value>
                    <fullName>ELETRODOMÉSTICOS E ELETROELETRÔNICOS</fullName>
                </value>
                <value>
                    <fullName>ELETRODOMESTICOS E ELETROELETRÔNICOS(NOVO)</fullName>
                </value>
                <value>
                    <fullName>FARMÁCIA/DROGRARIA/FARMACIAS ESPECIAIS(HOMEOPATIA</fullName>
                </value>
                <value>
                    <fullName>FLORISTA</fullName>
                </value>
                <value>
                    <fullName>FOTO REVELAÇÃO</fullName>
                </value>
                <value>
                    <fullName>HIPERMERCADO</fullName>
                </value>
                <value>
                    <fullName>HOTEL</fullName>
                </value>
                <value>
                    <fullName>JÓIAS, RELÓGIOS E BIJOUTERIAS</fullName>
                </value>
                <value>
                    <fullName>JORNALEIRO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Tipo_de_Atividade__c</fullName>
        <label>Tipo de Atividade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACESSÓRIOS E ARTIGOS PARA VIAGENS</fullName>
                </value>
                <value>
                    <fullName>ACESSÓRIOS P/ VESTUÁRIO</fullName>
                </value>
                <value>
                    <fullName>ACESSÓRIOS PARA DECORAÇÃO</fullName>
                </value>
                <value>
                    <fullName>ACESSÓRIOS PARA VESTUÁRIO (BOLSAS, CINTOS E OUTROS</fullName>
                </value>
                <value>
                    <fullName>ANTENAS E OPERADORAS</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS ELETRÔNICOS</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS ESPORTIVOS</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS INFANTIS</fullName>
                </value>
                <value>
                    <fullName>BIJOUTERIAS</fullName>
                </value>
                <value>
                    <fullName>BRINQUEDOS</fullName>
                </value>
                <value>
                    <fullName>CAFETERIAS</fullName>
                </value>
                <value>
                    <fullName>CALÇADOS ESPORTIVOS (TÊNIS)</fullName>
                </value>
                <value>
                    <fullName>CALÇADOS FEMININOS</fullName>
                </value>
                <value>
                    <fullName>CALÇADOS GERAL</fullName>
                </value>
                <value>
                    <fullName>CALÇADOS INFANTIS</fullName>
                </value>
                <value>
                    <fullName>CALÇADOS MASCULINOS</fullName>
                </value>
                <value>
                    <fullName>CALÇADOS ORTOPÉDICOS</fullName>
                </value>
                <value>
                    <fullName>CAMA/MESA/BANHO</fullName>
                </value>
                <value>
                    <fullName>COLCHÕES (NOVO)</fullName>
                </value>
                <value>
                    <fullName>COSMÉTICOS</fullName>
                </value>
                <value>
                    <fullName>ELETRODOMÉSTICOS</fullName>
                </value>
                <value>
                    <fullName>FAST-FOOD</fullName>
                </value>
                <value>
                    <fullName>INFORMÁTICA</fullName>
                </value>
                <value>
                    <fullName>JOALHERIAS</fullName>
                </value>
                <value>
                    <fullName>LIVRARIA</fullName>
                </value>
                <value>
                    <fullName>MAQUIAGEM</fullName>
                </value>
                <value>
                    <fullName>MARCA PRÓPRIA</fullName>
                </value>
                <value>
                    <fullName>MODA ÍNTIMA (LINGERIE/MEIAS)</fullName>
                </value>
                <value>
                    <fullName>MODA JOVEM (UNISSEX)</fullName>
                </value>
                <value>
                    <fullName>MODA PRAIA (BIQ./MAIÔS/SUNGAS)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Informacoes_historicas__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM_faturado__c</fullName>
        <label>AMM faturado</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Aluguel_percentual_faturado__c</fullName>
        <label>Aluguel percentual faturado</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Area__c</fullName>
        <label>Área</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio_comum__c</fullName>
        <label>Condomínio comum</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio_comum_m2__c</fullName>
        <label>Condomínio comum /m2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Custo_Ocupacao_Comum__c</fullName>
        <label>Custo Ocupação Comum</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Custo_Ocupacao_Comum_m2__c</fullName>
        <label>Custo Ocupação Comum/m²</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_FPP_Total_faturado__c</fullName>
        <label>FPP Total faturado</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_FPP_m2__c</fullName>
        <label>FPP /m2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Grocc_Comum_percentual__c</fullName>
        <label>Grocc Comum (%)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Grupo_de_atividade__c</fullName>
        <label>Grupo de atividade</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Lucs_secundarias__c</fullName>
        <label>Lucs secundárias</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Marca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>O valor preenchido no filtro não retornou nenhum registro existente.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Marca</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_fantasia__c</fullName>
        <label>Nome fantasia</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Percentual_sobre_vendas__c</fullName>
        <label>Percentual sobre vendas</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Propriedade old</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Tipo_de_Atividade__c</fullName>
        <label>Tipo de Atividade</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_do_Aluguel_m2__c</fullName>
        <label>Valor do Aluguel /m2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Venda_Total__c</fullName>
        <label>Venda Total</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_descricao_aluguel_dobrado__c</fullName>
        <label>Descrição do aluguel dobrado</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vendas_Total_m2__c</fullName>
        <label>Vendas Total /m2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Informação histórica da propriedade</label>
    <nameField>
        <label>Ano/Mes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações históricas da propriedade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_JuctionMarcaPlanoMix__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Marca__c</fullName>
        <label>Marca</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plano de mix</relationshipLabel>
        <relationshipName>TW1_Marcas_e_Plano_de_mix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Marca e Plano de mix</label>
    <nameField>
        <label>Marcas e Plano de mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas e Plano de mix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Plano_de_mix__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Grupo_de_atividade__c</fullName>
        <label>Grupo de atividade</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Tipo_de_atividade__c</fullName>
        <label>Tipo de atividade</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Plano de mix</label>
    <nameField>
        <label>Código Plano de mix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de mix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TabelaHistoricoController.cls
public class TabelaHistoricoController {
    @AuraEnabled
    public static List<	TW1_Informacoes_historicas__c> getTabelaHistorica(String shoppingId, String lucName, String marcaBuscada, Map<Id,Account> AccountsIds, String segmentoBuscado, String lucBuscada, String shoppingBuscado, String tipoBusca){
        List<TW1_Informacoes_historicas__c> tabelaHistorica = new List<TW1_Informacoes_historicas__c>();
        List<TW1_Informacoes_historicas__c> InftabelaHistorica = new List<TW1_Informacoes_historicas__c>();
	
        if(marcaBuscada != null && tipoBusca=='marca'){
            
            List<Account> marca = getListMarca(marcaBuscada);
			Map<Id,Account> accountsId = new Map<Id,Account>(marca);
            
            tabelaHistorica = 
                [
                    SELECT 
                    TW1_Aluguel_percentual_faturado__c,
                    TW1_AMM_faturado__c,
                    Name,
                    TW1_Condominio_comum__c,
                    TW1_Condominio_comum_m2__c,
                    TW1_Custo_Ocupacao_Comum__c,
                    TW1_Custo_Ocupacao_Comum_m2__c,
                    TW1_descricao_aluguel_dobrado__c,
                    TW1_FPP_m2__c,
                    TW1_FPP_Total_faturado__c,
                    TW1_Grocc_Comum_percentual__c,
                    TW1_Lucs_secundarias__c,
                    TW1_Percentual_sobre_vendas__c,
                    TW1_Propriedade__c,
                    TW1_Valor_do_Aluguel_m2__c,
                    TW1_Venda_Total__c,
                    Vendas_Total_m2__c,
                    TW1_Area__c,
                    TW1_Marca__c,
                    TW1_Nome_fantasia__c,
                    TW1_Grupo_de_atividade__c,
                    TW1_Tipo_de_Atividade__c,
                    TW1_Ramo_de_atividade__c
                    FROM TW1_Informacoes_historicas__c
                    WHERE TW1_Shopping__c = :shoppingId
                    AND TW1_Marca__c IN :accountsId.keySet() ORDER BY Name DESC
                ];
        }else if(segmentoBuscado != null && tipoBusca=='segmento'){
            TW1_Plano_de_mix__c segmentoId = getSegmento(segmentoBuscado);
            tabelaHistorica = 
                [
                    SELECT 
                    TW1_Aluguel_percentual_faturado__c,
                    TW1_AMM_faturado__c,
                    Name,
                    TW1_Condominio_comum__c,
                    TW1_Condominio_comum_m2__c,
                    TW1_Custo_Ocupacao_Comum__c,
                    TW1_Custo_Ocupacao_Comum_m2__c,
                    TW1_descricao_aluguel_dobrado__c,
                    TW1_FPP_m2__c,
                    TW1_FPP_Total_faturado__c,
                    TW1_Grocc_Comum_percentual__c,
                    TW1_Lucs_secundarias__c,
                    TW1_Percentual_sobre_vendas__c,
                    TW1_Propriedade__c,
                    TW1_Valor_do_Aluguel_m2__c,
                    TW1_Venda_Total__c,
                    Vendas_Total_m2__c,
                    TW1_Area__c,
                    TW1_Marca__c,
                    TW1_Nome_fantasia__c,
                    TW1_Grupo_de_atividade__c,
                    TW1_Tipo_de_Atividade__c,
                    TW1_Ramo_de_atividade__c
                    
                    FROM TW1_Informacoes_historicas__c
                    WHERE TW1_Shopping__c = :shoppingId And
                    TW1_Marca__c IN (
                	SELECT TW1_Marca__c
                    FROM TW1_JuctionMarcaPlanoMix__c
                    WHERE TW1_Plano_de_mix__c = :segmentoId.Id
                ) ORDER BY Name DESC
                ];
        }else if(lucBuscada != null && tipoBusca=='shopping_luc'){
            
            TW1_Propriedade__c prop = [SELECT Id FROM TW1_Propriedade__c where Name =:lucName];
            
            tabelaHistorica = 
                [
                    SELECT 
                    TW1_Aluguel_percentual_faturado__c,
                    TW1_AMM_faturado__c,
                    Name,
                    TW1_Condominio_comum__c,
                    TW1_Condominio_comum_m2__c,
                    TW1_Custo_Ocupacao_Comum__c,
                    TW1_Custo_Ocupacao_Comum_m2__c,
                    TW1_descricao_aluguel_dobrado__c,
                    TW1_FPP_m2__c,
                    TW1_FPP_Total_faturado__c,
                    TW1_Grocc_Comum_percentual__c,
                    TW1_Lucs_secundarias__c,
                    TW1_Percentual_sobre_vendas__c,
                    TW1_Propriedade__c,
                    TW1_Valor_do_Aluguel_m2__c,
                    TW1_Venda_Total__c,
                    Vendas_Total_m2__c,
                    TW1_Area__c,
                    TW1_Marca__c,
                    TW1_Nome_fantasia__c,
                    TW1_Grupo_de_atividade__c,
                    TW1_Tipo_de_Atividade__c,
                    TW1_Ramo_de_atividade__c
                    
                    FROM TW1_Informacoes_historicas__c
                    WHERE TW1_Shopping__c = :shoppingId And
                    TW1_Propriedade__c = :prop.Id ORDER BY Name DESC
                ];
        }
        
         InftabelaHistorica = new List<TW1_Informacoes_historicas__c>();
        
        Set<String> IdsHisto = new Set<String>();

        for(TW1_Informacoes_historicas__c tabhisto : tabelaHistorica){
            IdsHisto.add(tabhisto.TW1_Marca__c);
        }
            
        List<TW1_JuctionMarcaPlanoMix__c> listMap = [select TW1_Plano_de_mix__c,Name,TW1_Marca__c from TW1_JuctionMarcaPlanoMix__c where TW1_Marca__c IN :IdsHisto];
        Map<Id,TW1_JuctionMarcaPlanoMix__c> listjunt = new Map<Id,TW1_JuctionMarcaPlanoMix__c>(listMap);
        
        List<account> accc = [Select Id,Name From account where Id IN :listjunt.keySet()];
        Map<Id,account> acontMap = new Map<Id,account>(accc);
        
		 Set<String> IdsPlanoMix = new Set<String>();
        
        for(TW1_Informacoes_historicas__c listtabelaHistorica : tabelaHistorica){
        for(TW1_JuctionMarcaPlanoMix__c juntionMixx : listMap){          
                if(juntionMixx.TW1_Marca__c == listtabelaHistorica.TW1_Marca__c){
                    IdsPlanoMix.add(juntionMixx.TW1_Plano_de_mix__c);
                }
        }} 
        
         List<TW1_Plano_de_mix__c> ListPlanoMix = [select TW1_Grupo_de_atividade__c,Ramo_de_atividade__c,TW1_Tipo_de_atividade__c from TW1_Plano_de_mix__c where Id IN :IdsPlanoMix];
         Map<Id,TW1_Plano_de_mix__c> MapPlanoMix = new Map<Id,TW1_Plano_de_mix__c>(ListPlanoMix);
        
        
        for(TW1_Informacoes_historicas__c InfHistorico : tabelaHistorica)
        {
            InfHistorico.TW1_Nome_fantasia__c = '';
            InfHistorico.TW1_Grupo_de_atividade__c = '';
            InfHistorico.TW1_Ramo_de_atividade__c = '';
            InfHistorico.TW1_Tipo_de_Atividade__c = '';
            List<TW1_JuctionMarcaPlanoMix__c> ListJuntionMix = new List<TW1_JuctionMarcaPlanoMix__c>(); 

            for(TW1_JuctionMarcaPlanoMix__c juntionMix : listMap){
                if(juntionMix.TW1_Marca__c == InfHistorico.TW1_Marca__c){
                    ListJuntionMix.add(juntionMix);
                }
            }
            
            for(TW1_JuctionMarcaPlanoMix__c Junction : ListJuntionMix)
            {
                
                account acc = acontMap.get(Junction.TW1_Marca__c);
                
                if(acc != null)
                InfHistorico.TW1_Nome_fantasia__c = acc.Name == null ? '':acc.Name;
                
                TW1_Plano_de_mix__c PlanoMixJunction = MapPlanoMix.get(Junction.TW1_Plano_de_mix__c); 
                
                    if(PlanoMixJunction.TW1_Grupo_de_atividade__c != null)
                        InfHistorico.TW1_Grupo_de_atividade__c = InfHistorico.TW1_Grupo_de_atividade__c + PlanoMixJunction.TW1_Grupo_de_atividade__c +'/';
                    if(PlanoMixJunction.Ramo_de_atividade__c != null)
                        InfHistorico.TW1_Ramo_de_atividade__c = InfHistorico.TW1_Ramo_de_atividade__c + PlanoMixJunction.Ramo_de_atividade__c +'/';
                    if(PlanoMixJunction.TW1_Tipo_de_atividade__c != null)
                        InfHistorico.TW1_Tipo_de_Atividade__c = InfHistorico.TW1_Tipo_de_Atividade__c + PlanoMixJunction.TW1_Tipo_de_atividade__c +'/';				                        
            }
            InftabelaHistorica.add(InfHistorico);
        }
        
        insertAuditoriaInfHistorica(lucName, marcaBuscada, segmentoBuscado, shoppingBuscado, tipoBusca);
        
        if(segmentoBuscado != null && (tipoBusca=='segmento' || tipoBusca=='shopping_luc'))
        {
            return SomatorioSegmento(InftabelaHistorica);
        }  
        
        
        return InftabelaHistorica;
    }
    
    public static List<TW1_Informacoes_historicas__c> SomatorioSegmento(List<TW1_Informacoes_historicas__c> tabelaHistorica)
    {
        Set<String> NomesPeriodo = new Set<String>();
        List<TW1_Informacoes_historicas__c> ListInfSomado = new List<TW1_Informacoes_historicas__c>();
        
        for(TW1_Informacoes_historicas__c InfHisto : tabelaHistorica)
        {  
        	 NomesPeriodo.add(InfHisto.Name);
        }
        
        for(String nome : NomesPeriodo)
        {
            TW1_Informacoes_historicas__c inf = new TW1_Informacoes_historicas__c();
            inf.Name = nome;
            	//System.debug('2----- Infor.TW1_Venda_Total__c' + inf.TW1_Venda_Total__c);
                //System.debug('2----- Infor.Vendas_Total_m2__c' + inf.Vendas_Total_m2__c);
            	inf.TW1_Aluguel_percentual_faturado__c = (inf.TW1_Aluguel_percentual_faturado__c == null ? 0:inf.TW1_Aluguel_percentual_faturado__c);
                inf.TW1_Venda_Total__c = (inf.TW1_Venda_Total__c == null ? 0:inf.TW1_Venda_Total__c);
                inf.Vendas_Total_m2__c = (inf.Vendas_Total_m2__c == null ? 0:inf.Vendas_Total_m2__c);
                inf.TW1_AMM_faturado__c = (inf.TW1_AMM_faturado__c == null ? 0:inf.TW1_AMM_faturado__c);
                inf.TW1_Valor_do_Aluguel_m2__c = (inf.TW1_Valor_do_Aluguel_m2__c == null ? 0:inf.TW1_Valor_do_Aluguel_m2__c);
                inf.TW1_Condominio_comum__c = (inf.TW1_Condominio_comum__c == null ? 0:inf.TW1_Condominio_comum__c);
                inf.TW1_Condominio_comum_m2__c = (inf.TW1_Condominio_comum_m2__c == null ? 0:inf.TW1_Condominio_comum_m2__c);
                inf.TW1_FPP_Total_faturado__c = (inf.TW1_FPP_Total_faturado__c == null ? 0:inf.TW1_FPP_Total_faturado__c);
                inf.TW1_FPP_m2__c = (inf.TW1_FPP_m2__c == null ? 0:inf.TW1_FPP_m2__c);
                inf.TW1_Custo_Ocupacao_Comum__c = (inf.TW1_Custo_Ocupacao_Comum__c == null ? 0:inf.TW1_Custo_Ocupacao_Comum__c);
                inf.TW1_Custo_Ocupacao_Comum_m2__c = (inf.TW1_Custo_Ocupacao_Comum_m2__c == null ? 0:inf.TW1_Custo_Ocupacao_Comum_m2__c);
                inf.TW1_Grocc_Comum_percentual__c = (inf.TW1_Grocc_Comum_percentual__c == null ? 0:inf.TW1_Grocc_Comum_percentual__c);
            	inf.TW1_Percentual_sobre_vendas__c = (inf.TW1_Percentual_sobre_vendas__c == null ? 0:inf.TW1_Percentual_sobre_vendas__c);
         		inf.TW1_Area__c = (inf.TW1_Area__c == null ? 0:inf.TW1_Area__c);
            	inf.TW1_Grupo_de_atividade__c = '';
            	inf.TW1_Ramo_de_atividade__c = ''; 
                inf.TW1_Tipo_de_Atividade__c = '';
                
            for(TW1_Informacoes_historicas__c InfHisto : tabelaHistorica)
            {
                If(InfHisto.Name == nome)
                {
                    //System.debug('3----- inf.TW1_Venda_Total__c + InfHisto.TW1_Venda_Total__c' + inf.TW1_Venda_Total__c);
                	//System.debug('3----- inf.Vendas_Total_m2__c + InfHisto.Vendas_Total_m2__c' + inf.Vendas_Total_m2__c);
                    
                    inf.TW1_Venda_Total__c = inf.TW1_Venda_Total__c + InfHisto.TW1_Venda_Total__c;
                    inf.TW1_Aluguel_percentual_faturado__c = inf.TW1_Aluguel_percentual_faturado__c + InfHisto.TW1_Aluguel_percentual_faturado__c;
                    inf.Vendas_Total_m2__c = inf.Vendas_Total_m2__c + InfHisto.Vendas_Total_m2__c;
                    inf.TW1_AMM_faturado__c = inf.TW1_AMM_faturado__c + InfHisto.TW1_AMM_faturado__c;
                    inf.TW1_Valor_do_Aluguel_m2__c = inf.TW1_Valor_do_Aluguel_m2__c + InfHisto.TW1_Valor_do_Aluguel_m2__c;
                    inf.TW1_Condominio_comum__c = inf.TW1_Condominio_comum__c + InfHisto.TW1_Condominio_comum__c;
                    inf.TW1_Condominio_comum_m2__c = inf.TW1_Condominio_comum_m2__c + InfHisto.TW1_Condominio_comum_m2__c;
                    inf.TW1_FPP_Total_faturado__c = inf.TW1_FPP_Total_faturado__c + InfHisto.TW1_FPP_Total_faturado__c;
                    inf.TW1_FPP_m2__c = inf.TW1_FPP_m2__c + InfHisto.TW1_FPP_m2__c;
                    inf.TW1_Custo_Ocupacao_Comum__c = inf.TW1_Custo_Ocupacao_Comum__c + InfHisto.TW1_Custo_Ocupacao_Comum__c;
                    inf.TW1_Custo_Ocupacao_Comum_m2__c = inf.TW1_Custo_Ocupacao_Comum_m2__c + InfHisto.TW1_Custo_Ocupacao_Comum_m2__c;
                    inf.TW1_Grocc_Comum_percentual__c = inf.TW1_Grocc_Comum_percentual__c + InfHisto.TW1_Grocc_Comum_percentual__c;
                    inf.TW1_Percentual_sobre_vendas__c = inf.TW1_Percentual_sobre_vendas__c + InfHisto.TW1_Percentual_sobre_vendas__c;
                    inf.TW1_Area__c = inf.TW1_Area__c + InfHisto.TW1_Area__c;
                    inf.TW1_Grupo_de_atividade__c = InfHisto.TW1_Grupo_de_atividade__c != null ? InfHisto.TW1_Grupo_de_atividade__c : inf.TW1_Grupo_de_atividade__c;
                	inf.TW1_Ramo_de_atividade__c = InfHisto.TW1_Ramo_de_atividade__c != null ? InfHisto.TW1_Ramo_de_atividade__c : inf.TW1_Grupo_de_atividade__c;
                	inf.TW1_Tipo_de_Atividade__c = InfHisto.TW1_Tipo_de_Atividade__c != null ? InfHisto.TW1_Tipo_de_Atividade__c : inf.TW1_Grupo_de_atividade__c;
                }
            }
            	
            ListInfSomado.add(inf);
        }


		return ListInfSomado;  
    }
    
    public static List<Account> getListMarca(String strMarca){
        List<Account> listaMarcasEqual = [SELECT Name FROM Account WHERE RecordType.Name='Marca' And Name = :strMarca];
        
        if(listaMarcasEqual.size() >= 1){
            return listaMarcasEqual;
        }else{
            String strMarcaLike = '%' + strMarca + '%';
            List<Account> listaMarcasLike = [SELECT Name FROM Account WHERE RecordType.Name='Marca' And Name LIKE :strMarcaLike ];
            
            if(listaMarcasLike.size() >= 1){
                return listaMarcasLike;
            }else{
                return new List<Account>();
                
            }
        }
    }

    public static TW1_Plano_de_mix__c getSegmento(String strSegmento){

        List<TW1_Plano_de_mix__c> listaSegmentosEqual = [SELECT Name,Ramo_de_atividade__c FROM TW1_Plano_de_mix__c WHERE Ramo_de_atividade__c = :strSegmento];

        if(listaSegmentosEqual.size() >= 1){
            return listaSegmentosEqual.get(0);
        }else{
            String strSegmentoLike = strSegmento + '%';
            List<TW1_Plano_de_mix__c> listaSegmentosLike = [SELECT Name,Ramo_de_atividade__c FROM TW1_Plano_de_mix__c WHERE Ramo_de_atividade__c LIKE :strSegmentoLike ];
            
            if(listaSegmentosLike.size() == 0)
              return null;
                
            return listaSegmentosLike.get(0);
            /*
            if(listaSegmentosLike.size() >= 1){
                List<String> listaSegmentosLikeStr = new List<String>();
                for(TW1_Plano_de_mix__c segmentoLike : listaSegmentosLike){
                    listaSegmentosLikeStr.add(segmentoLike.Ramo_de_atividade__c);
                }
                Integer moreSimilarSegmentoIndex = Util.getClosestString(strSegmento, listaSegmentosLikeStr);
               
                return listaSegmentosLike.get(moreSimilarSegmentoIndex);
            }else{
                List<TW1_Plano_de_mix__c> listaSegmentosAll = [SELECT Ramo_de_atividade__c FROM TW1_Plano_de_mix__c];
                
                List<String> listaSegmentosAllStr = new List<String>();
                for(TW1_Plano_de_mix__c segmentoAll : listaSegmentosAll){
                    listaSegmentosAllStr.add(segmentoAll.Ramo_de_atividade__c);
                }
                
                Integer moreSimilarSegmentoIndex = Util.getClosestString(strSegmento, listaSegmentosAllStr);
                
                return listaSegmentosAll.get(moreSimilarSegmentoIndex);
                
            }*/
        }
    }
    
    public static void insertAuditoriaInfHistorica(String lucPesquisada, String marcaPesquisada, String segmentoPesquisado, String shoppingPesquisado, String tipoBusca){
        TW1_Auditoria_Inf_Historicas__c auditoria = new TW1_Auditoria_Inf_Historicas__c();
        
        auditoria.TW1_Data_da_pesquisa__c = System.today();
        auditoria.TW1_Shopping_pesquisado__c = shoppingPesquisado;
        auditoria.TW1_Usuario__c = UserInfo.getUserId();
        auditoria.TW1_Tipo_de_pesquisa__c = tipoBusca;
        if(tipoBusca == 'shopping_luc'){
            auditoria.TW1_LUC_pesquisada__c = lucPesquisada;
        }else if(tipoBusca == 'segmento'){
            auditoria.TW1_Segmento_pesquisado__c = segmentoPesquisado;
        }else if(tipoBusca == 'marca'){
            auditoria.TW1_Marca_pesquisada__c = marcaPesquisada;
        }
        
        insert auditoria;
    }
}