objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_Ramo_de_atividade__c</fullName>
        <label>Ramo de atividade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AGÊNCIA DE VIAGENS</fullName>
                </value>
                <value>
                    <fullName>ALIMENTAÇÃO</fullName>
                </value>
                <value>
                    <fullName>ALIMENTOS ESPECIAIS(CONGELADOS/DIETÉTICOS/NATURAIS</fullName>
                </value>
                <value>
                    <fullName>ARMARINHO</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS DIVERSOS</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS DO LAR</fullName>
                </value>
                <value>
                    <fullName>ARTIGOS ESPORTIVOS</fullName>
                </value>
                <value>
                    <fullName>BAZAR</fullName>
                </value>
                <value>
                    <fullName>BOLICHE</fullName>
                </value>
                <value>
                    <fullName>BRINQUEDOS</fullName>
                </value>
                <value>
                    <fullName>CABELEIREIRO, CLÍNICAS DE ESTÉTICA E PODOLOGIA)</fullName>
                </value>
                <value>
                    <fullName>CALÇADOS</fullName>
                </value>
                <value>
                    <fullName>CASA DE SHOWS</fullName>
                </value>
                <value>
                    <fullName>CENTRO DE CONVENÇÕES/SALA DE CONVENÇÕES</fullName>
                </value>
                <value>
                    <fullName>CHAVEIRO</fullName>
                </value>
                <value>
                    <fullName>CINEMAS</fullName>
                </value>
                <value>
                    <fullName>CONSERTOS</fullName>
                </value>
                <value>
                    <fullName>CONSTRUÇÃO E DECORAÇÃO(NOVO)</fullName>
                </value>
                <value>
                    <fullName>CORREIO</fullName>
                </value>
                <value>
                    <fullName>DELICATESSEN(QUEIJOS/FRIOS/BEBIDAS)</fullName>
                </value>
                <value>
                    <fullName>DIVERSÕES(PARQUES/VIDEOGAMES)</fullName>
                </value>
                <value>
                    <fullName>ELETRODOMÉSTICOS E ELETROELETRÔNICOS</fullName>
                </value>
                <value>
                    <fullName>ELETRODOMESTICOS E ELETROELETRÔNICOS(NOVO)</fullName>
                </value>
                <value>
                    <fullName>FARMÁCIA/DROGRARIA/FARMACIAS ESPECIAIS(HOMEOPATIA</fullName>
                </value>
                <value>
                    <fullName>FLORISTA</fullName>
                </value>
                <value>
                    <fullName>FOTO REVELAÇÃO</fullName>
                </value>
                <value>
                    <fullName>HIPERMERCADO</fullName>
                </value>
                <value>
                    <fullName>HOTEL</fullName>
                </value>
                <value>
                    <fullName>JÓIAS, RELÓGIOS E BIJOUTERIAS</fullName>
                </value>
                <value>
                    <fullName>JORNALEIRO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Contas (Shopping)</relationshipLabel>
        <relationshipName>Contas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Informacoes_historicas__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM_faturado__c</fullName>
        <label>AMM faturado</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Aluguel_percentual_faturado__c</fullName>
        <label>Aluguel percentual faturado</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Area__c</fullName>
        <label>Área</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio_comum__c</fullName>
        <label>Condomínio comum</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio_comum_m2__c</fullName>
        <label>Condomínio comum /m2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Custo_Ocupacao_Comum__c</fullName>
        <label>Custo Ocupação Comum</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Custo_Ocupacao_Comum_m2__c</fullName>
        <label>Custo Ocupação Comum/m²</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_FPP_Total_faturado__c</fullName>
        <label>FPP Total faturado</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_FPP_m2__c</fullName>
        <label>FPP /m2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Grocc_Comum_percentual__c</fullName>
        <label>Grocc Comum (%)</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Grupo_de_atividade__c</fullName>
        <label>Grupo de atividade</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Marca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>O valor preenchido no filtro não retornou nenhum registro existente.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Marca</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Percentual_sobre_vendas__c</fullName>
        <label>Percentual sobre vendas</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade1__c</fullName>
        <label>Propriedade</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Propriedade old</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Ramo_de_atividade__c</fullName>
        <label>Ramo de atividade</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_do_Aluguel_m2__c</fullName>
        <label>Valor do Aluguel /m2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Venda_Total__c</fullName>
        <label>Venda Total</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendas_Total_m2__c</fullName>
        <label>Vendas Total /m2</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Informação histórica da propriedade</label>
    <nameField>
        <label>Ano/Mes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações históricas da propriedade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_JuctionMarcaPlanoMix__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Marca__c</fullName>
        <label>Marca</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plano de mix</relationshipLabel>
        <relationshipName>TW1_Marcas_e_Plano_de_mix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Marca e Plano de mix</label>
    <nameField>
        <label>Marcas e Plano de mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas e Plano de mix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Plano_de_mix__c.object
<CustomObject>
    <fields>
        <fullName>Ramo_de_atividade__c</fullName>
        <label>Ramo de atividade</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Grupo_de_atividade__c</fullName>
        <label>Grupo de atividade</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Plano de mix</label>
    <nameField>
        <label>Código Plano de mix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de mix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato assinado</fullName>
                </value>
                <value>
                    <fullName>Repasse</fullName>
                </value>
                <value>
                    <fullName>Vaga</fullName>
                </value>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>Sigla</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_HistoricoTipoDeBusca_tst.cls
@isTest
public class TW1_Ancar_HistoricoTipoDeBusca_tst {
		
    
     @isTest
    static void TestgetLucsByShopping(){
        Test.startTest();
        	
        	recordtype RT = [Select Id,Name from recordtype where Name='Marca'];
        
        	TW1_Shopping__c shopping = new TW1_Shopping__c(Name='Teste Shopping 2',TW1_SGL_Empreendimento__c = 'BPS');
        	insert shopping;
        
        	TW1_Propriedade__c propriedade = new TW1_Propriedade__c();
        	propriedade.Name = 'Luc1';
        	propriedade.TW1_Shopping__c = shopping.Id;
        	propriedade.TW1_Status__c = 'Vaga';
        	insert propriedade;
        
        	Account acc = new Account();
        	acc.Name = 'dfds';
        	acc.RecordTypeId = RT.Id;
			insert acc; 
                
        	TW1_Informacoes_historicas__c iNF = new TW1_Informacoes_historicas__c();
        	iNF.Name = 'ssss';
        	iNF.TW1_Shopping__c =  shopping.Id;
        	iNF.TW1_Propriedade__c = propriedade.Id;
            iNF.TW1_Propriedade1__c = propriedade.Name;
        	iNF.TW1_Marca__c = acc.Id;
        	iNF.TW1_Venda_Total__c = 1;
        	iNF.TW1_Aluguel_percentual_faturado__c = 1;
            iNF.Vendas_Total_m2__c = 1;
            iNF.TW1_AMM_faturado__c = 1;
            iNF.TW1_Valor_do_Aluguel_m2__c =1; 
            iNF.TW1_Condominio_comum__c = 1;
            iNF.TW1_Condominio_comum_m2__c =1; 
            iNF.TW1_FPP_Total_faturado__c = 1;
            iNF.TW1_FPP_m2__c = 1;
            iNF.TW1_Custo_Ocupacao_Comum__c =1; 
            iNF.TW1_Custo_Ocupacao_Comum_m2__c =1; 
            iNF.TW1_Grocc_Comum_percentual__c = 1;
            iNF.TW1_Percentual_sobre_vendas__c = 1;
            iNF.TW1_Area__c = 1;
            iNF.TW1_Grupo_de_atividade__c = '';
            iNF.TW1_Ramo_de_atividade__c = ''; 
            iNF.TW1_Tipo_de_Atividade__c = '';
			insert iNF;
        
        	TW1_Informacoes_historicas__c iNFF = new TW1_Informacoes_historicas__c();
        	iNFF.Name = 'ssss';
        	iNFF.TW1_Shopping__c =  shopping.Id;
        	iNFF.TW1_Propriedade__c = propriedade.Id;
            iNFF.TW1_Propriedade1__c = propriedade.Name;
        	iNFF.TW1_Marca__c = acc.Id;
        	iNFF.TW1_Venda_Total__c = 1;
        	iNFF.TW1_Aluguel_percentual_faturado__c = 1;
            iNFF.Vendas_Total_m2__c = 1;
            iNFF.TW1_AMM_faturado__c = 1;
            iNFF.TW1_Valor_do_Aluguel_m2__c =1; 
            iNFF.TW1_Condominio_comum__c = 1;
            iNFF.TW1_Condominio_comum_m2__c =1; 
            iNFF.TW1_FPP_Total_faturado__c = 1;
            iNFF.TW1_FPP_m2__c = 1;
            iNFF.TW1_Custo_Ocupacao_Comum__c =1; 
            iNFF.TW1_Custo_Ocupacao_Comum_m2__c =1; 
            iNFF.TW1_Grocc_Comum_percentual__c = 1;
            iNFF.TW1_Percentual_sobre_vendas__c = 1;
            iNFF.TW1_Area__c = 1;
            iNFF.TW1_Grupo_de_atividade__c = '';
            iNFF.TW1_Ramo_de_atividade__c = ''; 
            iNFF.TW1_Tipo_de_Atividade__c = '';
			insert iNFF;
        
        	TW1_Plano_de_mix__c plano = new TW1_Plano_de_mix__c();
        	plano.Name = 'sdf';
        	plano.Ramo_de_atividade__c = 'sads';
            plano.TW1_Grupo_de_atividade__c = 'asd';
            plano.TW1_Tipo_de_atividade__c = 'sadsa';
        	plano.Id_Externo__c = 'sadsa';
        	insert plano;
        
        	TW1_JuctionMarcaPlanoMix__c junction = new TW1_JuctionMarcaPlanoMix__c();
        	junction.TW1_Marca__c = acc.Id;
        	junction.Name = 'safdsa';
        	junction.TW1_Plano_de_mix__c = plano.Id;
       		insert junction;
        

        
        	TW1_Ancar_HistoricoTipoDeBusca tabelaHistorico = new TW1_Ancar_HistoricoTipoDeBusca();
        	tabelaHistorico.displayTabela = true;
            //tabelaHistorico.valorPesquisaShopping = shopping.Name;
        	tabelaHistorico.IdObjetoDisplay = shopping.Id; 
        	tabelaHistorico.MostraPesquisaSegmento();
        	tabelaHistorico.TelaInicio();
        	tabelaHistorico.MostraPesquisaMarca();
        	tabelaHistorico.MostraPesquisaShopping();
        	tabelaHistorico.ShowLuc();
        	tabelaHistorico.valorPesquisaSegmento = '';
        	tabelaHistorico.valorPesquisaLuc = '1';
        	tabelaHistorico.valorPesquisaMarca = acc.Id;
        	tabelaHistorico.tabelaHistorica = New List<TW1_Informacoes_historicas__c>();
   			tabelaHistorico.InftabelaHistorica = New List<TW1_Informacoes_historicas__c>();
    	    tabelaHistorico.ListShoppingsSegmento = new List<TW1_Shopping__c>();
   			tabelaHistorico.ListShoppingsluc = new List<TW1_Shopping__c>();
            tabelaHistorico.shoppingId = '';
            tabelaHistorico.lucName = '';
            tabelaHistorico.marcaBuscada = '';
            tabelaHistorico.segmentoBuscado = '';
            tabelaHistorico.lucBuscada = '';
            tabelaHistorico.shoppingBuscado = '';
        	tabelaHistorico.NomeDoMarca = acc.Name;
            tabelaHistorico.NomeDaLuc = propriedade.Name;   
        	tabelaHistorico.shoppingBuscado = shopping.Id;
        	tabelaHistorico.displayRetornoPesquisa =true;
            tabelaHistorico.SegmentoRamo = '';
            tabelaHistorico.accountsIds = new Map<Id,Account>();
            tabelaHistorico.NomeDoSegmento ='';
        
        
        	tabelaHistorico.getShoppingsSegmento();
        
        	tabelaHistorico.valorPesquisaSegmento = 'dolar';
        	tabelaHistorico.getSegmento();
        	tabelaHistorico.valorPesquisaSegmento = '';
        	tabelaHistorico.getSegmento();
        
        	//TW1_Shopping__c dd = TW1_Ancar_HistoricoTipoDeBusca.getShopping('Teste Shopping 2');
       		//TW1_Shopping__c dc = TW1_Ancar_HistoricoTipoDeBusca.getShopping('');
       		tabelaHistorico.valorPesquisaShoppinLuc = 'Luc';
        	tabelaHistorico.getLucsByLuc();
        	tabelaHistorico.valorPesquisaShoppinLuc = '';
        	tabelaHistorico.getLucsByLuc();
        	tabelaHistorico.valorPesquisaShoppinLuc = 'zzcxz';
        	tabelaHistorico.getLucsByLuc();
        	
        	tabelaHistorico.getTabelaHistorica();
        	tabelaHistorico.tipodeBusca = 'marca';
        	tabelaHistorico.NomeDoMarca = 'zoa';
        	tabelaHistorico.getTabelaHistorica();
        
        	tabelaHistorico.valorPesquisaLuc = '';
        	tabelaHistorico.getShoppingsByMarca();
        	tabelaHistorico.getLucsByLuc();
        	List<TW1_Propriedade__c> listluc = TW1_Ancar_HistoricoTipoDeBusca.getLuc('Luc1', shopping.Id);
        	List<TW1_Propriedade__c> listlucc = TW1_Ancar_HistoricoTipoDeBusca.getLuc('L', shopping.Id);
        	tabelaHistorico.getMarca();
            tabelaHistorico.valorPesquisaMarca ='';
       		tabelaHistorico.getMarca();
        
        	tabelaHistorico.tipodeBusca = 'shopping_luc';
        	tabelaHistorico.getTabelaHistoricaLuc();
        
        	tabelaHistorico.NomeDaLuc = 'xzc';
        	tabelaHistorico.getTabelaHistoricaLuc();
        	tabelaHistorico.IdObjetoDisplay = plano.Id;
        	tabelaHistorico.shoppingId = shopping.Id;
        	tabelaHistorico.NomeDoShopping = 'Nova';
       		tabelaHistorico.tipodeBusca = 'segmento';
        	tabelaHistorico.getTabelaHistoricaSegmento();
        	tabelaHistorico.shoppingBuscado = 'a010R000000n9V7';
        	tabelaHistorico.getTabelaHistoricaSegmento();
        	
        
        	List<TW1_Informacoes_historicas__c> tabelaHistorica = new List<TW1_Informacoes_historicas__c>();
        	tabelaHistorica.add(iNF);
       		tabelaHistorica.add(iNFF);
        	List<TW1_Informacoes_historicas__c> s = TW1_Ancar_HistoricoTipoDeBusca.SomatorioSegmento(tabelaHistorica);
        
        	

        Test.stopTest();
    }
  }