objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_Apelido__c</fullName>
        <label>Apelido</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fidelidade</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Esse cliente já possui registro de Fidelidade criado. Não é possível criar um novo registro.</errorMessage>
            <filterItems>
                <field>TW1_Fidelidade__c.TW1_Nome_Cliente__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cliente</relationshipLabel>
        <relationshipName>TW1_Relation_Fidelidade_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Cartoes_Estacionamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Cartao_Gerado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cartão Gerado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio__c</fullName>
        <label>Data início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Marca__c</fullName>
        <label>Marca</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Modelo__c</fullName>
        <label>Modelo</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Fidelidade__c</fullName>
        <label>Número Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cartões Estacionamento</relationshipLabel>
        <relationshipName>Cart_es_Estacionamento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>TW1_Placa__c</fullName>
        <label>Placa</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Inativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cartão Estacionamento</label>
    <nameField>
        <label>Número do cartão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões Estacionamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Fidelidade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Historico__c</fullName>
        <label>Histórico</label>
        <summarizedField>TW1_Historico__c.TW1_Pontos__c</summarizedField>
        <summaryFilterItems>
            <field>TW1_Historico__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cadastro de NTFS</value>
        </summaryFilterItems>
        <summaryForeignKey>TW1_Historico__c.TW1_Fidelidade__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nome do Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fidelidade</relationshipLabel>
        <relationshipName>Fidelidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Saldo__c</fullName>
        <label>Saldo</label>
        <summarizedField>TW1_Historico__c.TW1_Pontos__c</summarizedField>
        <summaryForeignKey>TW1_Historico__c.TW1_Fidelidade__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fidelidade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número Fidelidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidelidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Historico__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Data__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Data</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <label>Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Históricos</relationshipLabel>
        <relationshipName>Hist_ricos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Pontos__c</fullName>
        <label>Pontos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Saldo__c</fullName>
        <formula>TW1_Fidelidade__r.TW1_Saldo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Saldo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Válida</fullName>
                    <default>true</default>
                    <label>Válida</label>
                </value>
                <value>
                    <fullName>Expirada</fullName>
                </value>
                <value>
                    <fullName>Utilizada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ajuste de Saldo</fullName>
                </value>
                <value>
                    <fullName>Aniversário</fullName>
                </value>
                <value>
                    <fullName>Cadastro de NTFS</fullName>
                </value>
                <value>
                    <fullName>Cartão Estacionamento</fullName>
                </value>
                <value>
                    <fullName>Saldo Inicial</fullName>
                </value>
                <value>
                    <fullName>Vinho</fullName>
                </value>
                <value>
                    <fullName>Nota Expirada</fullName>
                </value>
                <value>
                    <fullName>Ação Marketing</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Histórico</label>
    <nameField>
        <displayFormat>HIST-{00000000}</displayFormat>
        <label>Código Histórico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TW1_Cartao_Estacio_Serv.cls
public class TW1_Cartao_Estacio_Serv {
    
    public List<TW1_Cartoes_Estacionamento__c> getCartaoEstacionamento(String Id){
       
            List<TW1_Cartoes_Estacionamento__c> listaCartaoEstacionamento = [
                select 
                id,
                Name,
                TW1_Cartao_Gerado__c,
                TW1_Numero__c,
                TW1_Numero_Fidelidade__c,
                TW1_Data_inicio__c,
                TW1_Data_Fim__c,
                TW1_Status__c
                from TW1_Cartoes_Estacionamento__c 
                where id=:Id
            ];
            
            return listaCartaoEstacionamento;
    }
    
    public TW1_Fidelidade__c getFidelidade(String IdFidelidade){
       
            TW1_Fidelidade__c listarFidelidade = [
                Select 
                Id,
                Name,
                TW1_Nome_Cliente__c,
                TW1_Saldo__c
                from
                TW1_Fidelidade__c
                where 
                Id=:IdFidelidade Limit 1
            ];
            return listarFidelidade;
    }
    
    public Account geAccount(String IdCliente){
      
            Account listarAccount= [
                Select 
                Id,
                Name,
                TW1_Apelido__c
                from
                Account
                where 
                Id=:IdCliente Limit 1
            ];
            return listarAccount;
    }
    
     public void UpdateCartaoGeradoInativo(String IdCartao){
        TW1_Cartoes_Estacionamento__c CartaoGerado = [
            select 
            Id,
            Name,
            TW1_Cartao_Gerado__c,
            TW1_Numero__c,
            TW1_Numero_Fidelidade__c,
            TW1_Data_inicio__c,
            TW1_Data_Fim__c,
            TW1_Status__c
            from TW1_Cartoes_Estacionamento__c 
            where Id=:IdCartao limit 1 
        ];
        
        CartaoGerado.TW1_Status__c = 'Inativo';
      
            Update CartaoGerado;
            
           TW1_Cartoes_Estacionamento__c CartaoGeradoCopy = new TW1_Cartoes_Estacionamento__c();
       
            CartaoGeradoCopy.TW1_Data_Fim__c = CartaoGerado.TW1_Data_Fim__c;
            CartaoGeradoCopy.TW1_Data_inicio__c = CartaoGerado.TW1_Data_inicio__c;
            CartaoGeradoCopy.TW1_Cartao_Gerado__c = false;
            CartaoGeradoCopy.TW1_Status__c = 'Ativo';
            CartaoGeradoCopy.TW1_Numero_Fidelidade__c = CartaoGerado.TW1_Numero_Fidelidade__c;
            CartaoGeradoCopy.TW1_Marca__c = CartaoGerado.TW1_Marca__c;
            CartaoGeradoCopy.TW1_Modelo__c = CartaoGerado.TW1_Modelo__c;
            CartaoGeradoCopy.TW1_Placa__c = CartaoGerado.TW1_Placa__c;
          
            Insert CartaoGeradoCopy;
    }
    
    public void GerarHistorico(String IdFidelidade){
        
        recordtype rc = [select Id,Name from recordtype where Name='Cartão Estacionamento' Limit 1];
        TW1_Historico__c historico = new TW1_Historico__c();
        historico.TW1_Fidelidade__c = IdFidelidade;
        historico.RecordTypeId = rc.Id;
        historico.TW1_Tipo__c = 'Cartão Estacionamento';
        historico.TW1_Data__c = DateTime.now().date();
        historico.TW1_Pontos__c = -1000;
        
        insert historico;
        
    }
    
    public TW1_Cartoes_Estacionamento__c UpdateCartaoGerado(String IdCartao){
        TW1_Cartoes_Estacionamento__c CartaoGerado = [
            select 
            Id,
            Name,
            TW1_Cartao_Gerado__c,
            TW1_Numero__c,
            TW1_Numero_Fidelidade__c,
            TW1_Data_inicio__c,
            TW1_Data_Fim__c,
            TW1_Status__c
            from TW1_Cartoes_Estacionamento__c 
            where Id=:IdCartao limit 1 
        ];
        
        CartaoGerado.TW1_Cartao_Gerado__c = true;
       
            Update CartaoGerado;
            return CartaoGerado;
    }
}