objects/Account.object
<CustomObject>
    <fields>
        <fullName>CEP__c</fullName>
        <label>CEP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Av_Rua__c</fullName>
        <label>Av./Rua</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Bairro__c</fullName>
        <label>Bairro</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Cidade__c</fullName>
        <label>Cidade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Estado__c</fullName>
        <label>Estado</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Contas (Shopping)</relationshipLabel>
        <relationshipName>Contas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Telefone_comercial__c</fullName>
        <label>Telefone comercial</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TW1_Marca__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Marca</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Marca</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades de Marcas</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Frio</fullName>
                    <default>true</default>
                    <label>Frio</label>
                </value>
                <value>
                    <fullName>Morno</fullName>
                </value>
                <value>
                    <fullName>Quente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Cidade__c</fullName>
        <label>Cidade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AC</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>CE</fullName>
                </value>
                <value>
                    <fullName>DF</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MG</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PB</fullName>
                </value>
                <value>
                    <fullName>PE</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>RJ</fullName>
                </value>
                <value>
                    <fullName>RN</fullName>
                </value>
                <value>
                    <fullName>RO</fullName>
                </value>
                <value>
                    <fullName>RR</fullName>
                </value>
                <value>
                    <fullName>RS</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>TO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>Sigla</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_NovaCotacaoConfig_Test.cls
@isTest
public class TW1_Ancar_Venda_NovaCotacaoConfig_Test {
	
    @isTest
    static Opportunity TW1_Ancar_Venda_NovaCotacaoConfig_Test_Moc(){
    
        RecordType vaRecodtypeMarca = [SELECT Id, Name FROM RecordType WHERE Name ='Marca'];
        
        Account vaMarca = new Account();
        vaMarca.Name = 'Apex test Marca';
        vaMarca.TW1_Status__c = 'Ativa';
		vaMarca.RecordTypeId = vaRecodtypeMarca.Id; 
        Insert vaMarca;

        RecordType vaRecodtypeConta = [SELECT Id, Name FROM RecordType WHERE Name ='Contato comercial PF'];
        
        Account vaConta = new Account();
        vaConta.FirstName = 'Apex Test Contato'; 
        vaConta.LastName = 'de Teste';
        vaConta.CEP__c = 235847658;
		vaConta.TW1_Av_Rua__c = 'Rua teste';
        vaConta.TW1_Numero__c = 123;
        vaConta.TW1_Bairro__c = 'Bairro de Teste';
        vaConta.TW1_Cidade__c = 'Cidade de teste';
        vaConta.TW1_Estado__c = 'Estado de Teste';
        vaConta.TW1_Telefone_comercial__c = '21999998888';
        vaConta.RecordTypeId = vaRecodtypeConta.Id; 
		Insert vaConta;
        
        TW1_Shopping__c vaShopping = new TW1_Shopping__c();
        vaShopping.Name = 'Apex Test Shopping de Teste';
        vaShopping.TW1_SGL_Empreendimento__c = 'MST';
		Insert vaShopping;
        
        RecordType vaRecodtypeOppotunity = [SELECT Id, Name FROM RecordType WHERE Name ='Oportunidade de Loja'];
        
        Opportunity vaOportunidade = new Opportunity();
		vaOportunidade.Name = 'Apex Test '+vaRecodtypeOppotunity.Name;
        vaOportunidade.TW1_Shopping__c = vaShopping.Id;
        vaOportunidade.TW1_Marca__c = vaMarca.Id;
        vaOportunidade.AccountId = vaConta.Id;
        vaOportunidade.StageName = 'Em negociação';
        vaOportunidade.CloseDate = Date.valueOf('2018-02-12');
        vaOportunidade.RecordTypeId = vaRecodtypeOppotunity.Id; 
        Insert vaOportunidade;
        
		return vaOportunidade;
    }
    
    @isTest
    static void getObjectById_Test(){
        String vaOpportunityId = TW1_Ancar_Venda_NovaCotacaoConfig_Test_Moc().id;
        System.debug('id de teste:'+vaOpportunityId);
        
        Test.startTest();
            String retornaDto = TW1_Ancar_Venda_NovaCotacaoConfig_ctrl.getObjectById(vaOpportunityId);
        	System.assert(retornaDto!=null);
        test.stopTest();
    }
    
}