objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_CNPJ__c</fullName>
        <externalId>true</externalId>
        <label>CNPJ</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <externalId>true</externalId>
        <label>CPF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fidelidade</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Esse cliente já possui registro de Fidelidade criado. Não é possível criar um novo registro.</errorMessage>
            <filterItems>
                <field>TW1_Fidelidade__c.TW1_Nome_Cliente__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cliente</relationshipLabel>
        <relationshipName>TW1_Relation_Fidelidade_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Cartoes_Estacionamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Cartao_Gerado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cartão Gerado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio__c</fullName>
        <label>Data início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Fidelidade__c</fullName>
        <label>Número Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cartões Estacionamento</relationshipLabel>
        <relationshipName>Cart_es_Estacionamento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Inativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cartão Estacionamento</label>
    <nameField>
        <label>Número do cartão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões Estacionamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Fidelidade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Nome_Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nome do Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fidelidade</relationshipLabel>
        <relationshipName>Fidelidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fidelidade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número Fidelidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidelidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Cartao_Estacio_Tst_Reempressao.cls
@isTest
public with sharing class TW1_Cartao_Estacio_Tst_Reempressao {
    
    @isTest public static void testGerarCartaoEstacionamento(){
        
        recordtype varecodtype=[select id,name from recordtype where name='Conta pessoal padrão' limit 1];
        
        //Inserindo a massa de teste
        Account vaAccount = new Account(); 
        vaAccount.FirstName ='Teste';
        vaAccount.LastName ='silva';
        vaAccount.TW1_CPF__c='74745710569';
        vaAccount.TW1_CNPJ__c='27364928000101';
        vaAccount.Phone = '2133337444';
        vaAccount.PersonMobilePhone = '21999984578';
        vaAccount.RecordTypeId = varecodtype.id;
        insert vaAccount;
        
        TW1_Fidelidade__c vafidelidade = new TW1_Fidelidade__c();
        system.debug(vaAccount.Id);
        vafidelidade.TW1_Nome_Cliente__c = vaAccount.Id;
        insert vafidelidade;
        
        TW1_Cartoes_Estacionamento__c cartao = new TW1_Cartoes_Estacionamento__c();
        cartao.TW1_Cartao_Gerado__c = true;
        cartao.TW1_Data_Fim__c = Date.newinstance(2017,01,01);
        cartao.TW1_Data_inicio__c = Date.newinstance(2017,01,10);
        cartao.TW1_Numero_Fidelidade__c = vafidelidade.Id;
        cartao.TW1_Status__c = 'Ativo';
        insert cartao;
        
        //Começando os Testes
        Test.startTest();
        
        ApexPages.CurrentPage().getparameters().put('id', cartao.Id);      
        
        Apexpages.StandardController sc = new Apexpages.StandardController(cartao);
        Tw1_Cartao_Estacio_Ctr_Reempressao ctrCartEst = new Tw1_Cartao_Estacio_Ctr_Reempressao(sc);
        
        ctrCartEst.GerarPdf();
        
        Test.stopTest();
        //Fim do teste
    }
}