objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_CNPJ__c</fullName>
        <externalId>true</externalId>
        <label>CNPJ</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <externalId>true</externalId>
        <label>CPF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fidelidade</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Esse cliente já possui registro de Fidelidade criado. Não é possível criar um novo registro.</errorMessage>
            <filterItems>
                <field>TW1_Fidelidade__c.TW1_Nome_Cliente__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cliente</relationshipLabel>
        <relationshipName>TW1_Relation_Fidelidade_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Cartoes_Estacionamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Cartao_Gerado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cartão Gerado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio__c</fullName>
        <label>Data início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Fidelidade__c</fullName>
        <label>Número Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cartões Estacionamento</relationshipLabel>
        <relationshipName>Cart_es_Estacionamento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Inativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cartão Estacionamento</label>
    <nameField>
        <label>Número do cartão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões Estacionamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Fidelidade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Historico__c</fullName>
        <label>Histórico</label>
        <summarizedField>TW1_Historico__c.TW1_Pontos__c</summarizedField>
        <summaryFilterItems>
            <field>TW1_Historico__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cadastro de NTFS</value>
        </summaryFilterItems>
        <summaryForeignKey>TW1_Historico__c.TW1_Fidelidade__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nome do Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fidelidade</relationshipLabel>
        <relationshipName>Fidelidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fidelidade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número Fidelidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidelidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Historico__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Data__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Data</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <label>Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Históricos</relationshipLabel>
        <relationshipName>Hist_ricos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Pontos__c</fullName>
        <label>Pontos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Válida</fullName>
                    <default>true</default>
                    <label>Válida</label>
                </value>
                <value>
                    <fullName>Expirada</fullName>
                </value>
                <value>
                    <fullName>Utilizada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ajuste de Saldo</fullName>
                </value>
                <value>
                    <fullName>Aniversário</fullName>
                </value>
                <value>
                    <fullName>Cadastro de NTFS</fullName>
                </value>
                <value>
                    <fullName>Cartão Estacionamento</fullName>
                </value>
                <value>
                    <fullName>Saldo Inicial</fullName>
                </value>
                <value>
                    <fullName>Vinho</fullName>
                </value>
                <value>
                    <fullName>Nota Expirada</fullName>
                </value>
                <value>
                    <fullName>Ação Marketing</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Histórico</label>
    <nameField>
        <displayFormat>HIST-{00000000}</displayFormat>
        <label>Código Histórico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TW1_Cartao_Estacio_Tst_GerarPDFT.cls
@isTest
public with sharing class TW1_Cartao_Estacio_Tst_GerarPDFT {
    
    @isTest 
    public static void testGerarCartaoPDFSaldoMaiorQue1000(){
        //Inserindo a massa de teste
        recordtype varecodtype2=[select id,name from recordtype where name='Cartão Estacionamento' limit 1];
        recordtype varecodtype=[select id,name from recordtype where name='Conta pessoal padrão' limit 1];
        
        Account vaAccounts = new Account(); 
        vaAccounts.FirstName ='Teste';
        vaAccounts.LastName ='silva';
        vaAccounts.TW1_CPF__c='74745710569';
        vaAccounts.TW1_CNPJ__c='27364928000101';
        vaAccounts.Phone = '2133337444';
        vaAccounts.PersonMobilePhone = '21999984578';
        vaAccounts.RecordTypeId = varecodtype.id;
        insert vaAccounts;
        
        TW1_Fidelidade__c vafidelidade = new TW1_Fidelidade__c();
        system.debug(vaAccounts.Id);
        vafidelidade.TW1_Nome_Cliente__c = vaAccounts.Id;
        insert vafidelidade;
        
        TW1_Cartoes_Estacionamento__c cartao = new TW1_Cartoes_Estacionamento__c();
        cartao.TW1_Cartao_Gerado__c = true;
        cartao.TW1_Data_Fim__c = Date.newinstance(2017,01,01);
        cartao.TW1_Data_inicio__c = Date.newinstance(2017,01,10);
        cartao.TW1_Numero_Fidelidade__c = vafidelidade.Id;
        cartao.TW1_Status__c = 'Ativo';
        insert cartao;
        
        TW1_Historico__c historico = new TW1_Historico__c();
        historico.TW1_Fidelidade__c = vafidelidade.id;
        historico.RecordTypeId = varecodtype2.id;
        historico.TW1_Tipo__c = 'Cartão Estacionamento';
        historico.TW1_Data__c = DateTime.now().date();
        historico.TW1_Pontos__c = 1000;
        insert historico;
        
        //Começando os Testes
        Test.startTest();
        ApexPages.CurrentPage().getparameters().put('id', cartao.Id);      
        Apexpages.StandardController sc = new Apexpages.StandardController(cartao);
        TW1_Cartao_Estacio_Ctr_GerarPDFT ctrCartEst = new TW1_Cartao_Estacio_Ctr_GerarPDFT(sc);
        
        ctrCartEst.GerarPdf();
        
        Test.stopTest();
        //Fim do teste
    }
    
    @isTest public static void testGerarCartaoPDFSaldoMenorQue1000(){
        //Inserindo a massa de teste
        
         recordtype varecodtype2=[select id,name from recordtype where name='Cartão Estacionamento' limit 1];
        recordtype varecodtype=[select id,name from recordtype where name='Conta pessoal padrão' limit 1];
        
        Account vaAccounts = new Account(); 
        vaAccounts.FirstName ='Teste';
        vaAccounts.LastName ='silva';
        vaAccounts.TW1_CPF__c='74745710569';
        vaAccounts.TW1_CNPJ__c='27364928000101';
        vaAccounts.Phone = '2133337444';
        vaAccounts.PersonMobilePhone = '21999984578';
        vaAccounts.RecordTypeId = varecodtype.id;
        insert vaAccounts;
        
        TW1_Fidelidade__c vafidelidade = new TW1_Fidelidade__c();
        system.debug(vaAccounts.Id);
        vafidelidade.TW1_Nome_Cliente__c = vaAccounts.Id;
        insert vafidelidade;
        
        TW1_Cartoes_Estacionamento__c cartao = new TW1_Cartoes_Estacionamento__c();
        cartao.TW1_Cartao_Gerado__c = true;
        cartao.TW1_Data_Fim__c = Date.newinstance(2017,01,01);
        cartao.TW1_Data_inicio__c = Date.newinstance(2017,01,10);
        cartao.TW1_Numero_Fidelidade__c = vafidelidade.Id;
        cartao.TW1_Status__c = 'Ativo';
        insert cartao;
        
        TW1_Historico__c historico = new TW1_Historico__c();
        historico.TW1_Fidelidade__c = vafidelidade.id;
        historico.RecordTypeId = varecodtype2.id;
        historico.TW1_Tipo__c = 'Cartão Estacionamento';
        historico.TW1_Data__c = DateTime.now().date();
        historico.TW1_Pontos__c = 0;
        insert historico;
        
        //Começando os Testes
        Test.startTest();
        ApexPages.CurrentPage().getparameters().put('id', cartao.Id);      
        Apexpages.StandardController sc = new Apexpages.StandardController(cartao);
        TW1_Cartao_Estacio_Ctr_GerarPDFT ctrCartEst = new TW1_Cartao_Estacio_Ctr_GerarPDFT(sc);
        
        ctrCartEst.GerarPdf();
        
        Test.stopTest();
        //Fim do teste
    }
    
    @isTest public static void testGerarCartaoPDFStatusInativoMenorQue1000(){
        //Inserindo a massa de teste
       
       	 recordtype varecodtype2=[select id,name from recordtype where name='Cartão Estacionamento' limit 1];
        recordtype varecodtype=[select id,name from recordtype where name='Conta pessoal padrão' limit 1];
        
        Account vaAccounts = new Account(); 
        vaAccounts.FirstName ='Teste';
        vaAccounts.LastName ='silva';
        vaAccounts.TW1_CPF__c='74745710569';
        vaAccounts.TW1_CNPJ__c='27364928000101';
        vaAccounts.Phone = '2133337444';
        vaAccounts.PersonMobilePhone = '21999984578';
        vaAccounts.RecordTypeId = varecodtype.id;
        insert vaAccounts;
        
        TW1_Fidelidade__c vafidelidade = new TW1_Fidelidade__c();
        system.debug(vaAccounts.Id);
        vafidelidade.TW1_Nome_Cliente__c = vaAccounts.Id;
        insert vafidelidade;
        
        TW1_Cartoes_Estacionamento__c cartao = new TW1_Cartoes_Estacionamento__c();
        cartao.TW1_Cartao_Gerado__c = false;
        cartao.TW1_Data_Fim__c = Date.newinstance(2017,01,01);
        cartao.TW1_Data_inicio__c = Date.newinstance(2017,01,10);
        cartao.TW1_Numero_Fidelidade__c = vafidelidade.Id;
        cartao.TW1_Status__c = 'inativo';
        insert cartao;
        
        TW1_Historico__c historico = new TW1_Historico__c();
        historico.TW1_Fidelidade__c = vafidelidade.id;
        historico.RecordTypeId = varecodtype2.id;
        historico.TW1_Tipo__c = 'Cartão Estacionamento';
        historico.TW1_Data__c = DateTime.now().date();
        historico.TW1_Pontos__c = 0;
        insert historico;
        
        //Começando os Testes
        Test.startTest();
        ApexPages.CurrentPage().getparameters().put('id', cartao.Id);      
        Apexpages.StandardController sc = new Apexpages.StandardController(cartao);
        TW1_Cartao_Estacio_Ctr_GerarPDFT ctrCartEst = new TW1_Cartao_Estacio_Ctr_GerarPDFT(sc);
        
        ctrCartEst.GerarPdf();
        
        Test.stopTest();
        //Fim do teste
    }
    
    @isTest public static void testGerarCartaoPDFStatusIDNulo(){
        //Inserindo a massa de teste
        recordtype varecodtype2=[select id,name from recordtype where name='Cartão Estacionamento' limit 1];
        recordtype varecodtype=[select id,name from recordtype where name='Conta pessoal padrão' limit 1];
        
        Account vaAccounts = new Account(); 
        vaAccounts.FirstName ='Teste';
        vaAccounts.LastName ='silva';
        vaAccounts.TW1_CPF__c='74745710569';
        vaAccounts.TW1_CNPJ__c='27364928000101';
        vaAccounts.Phone = '2133337444';
        vaAccounts.PersonMobilePhone = '21999984578';
        vaAccounts.RecordTypeId = varecodtype.id;
        insert vaAccounts;
        
        TW1_Fidelidade__c vafidelidade = new TW1_Fidelidade__c();
        system.debug(vaAccounts.Id);
        vafidelidade.TW1_Nome_Cliente__c = vaAccounts.Id;
        insert vafidelidade;
        
        TW1_Cartoes_Estacionamento__c cartao = new TW1_Cartoes_Estacionamento__c();
        cartao.TW1_Cartao_Gerado__c = false;
        cartao.TW1_Data_Fim__c = Date.newinstance(2017,01,01);
        cartao.TW1_Data_inicio__c = Date.newinstance(2017,01,10);
        cartao.TW1_Numero_Fidelidade__c = vafidelidade.Id;
        cartao.TW1_Status__c = 'inativo';
        insert cartao;
        
        TW1_Historico__c historico = new TW1_Historico__c();
        historico.TW1_Fidelidade__c = vafidelidade.id;
        historico.RecordTypeId = varecodtype2.id;
        historico.TW1_Tipo__c = 'Cartão Estacionamento';
        historico.TW1_Data__c = DateTime.now().date();
        historico.TW1_Pontos__c = 0;
        insert historico;
        
        //Começando os Testes
        Test.startTest();
        ApexPages.CurrentPage().getparameters().put('id', null);      
        Apexpages.StandardController sc = new Apexpages.StandardController(cartao);
        TW1_Cartao_Estacio_Ctr_GerarPDFT ctrCartEst = new TW1_Cartao_Estacio_Ctr_GerarPDFT(sc);
        
        ctrCartEst.GerarPdf();
        
        Test.stopTest();
        //Fim do teste
    }
}