objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_CNPJ__c</fullName>
        <externalId>true</externalId>
        <label>CNPJ</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <externalId>true</externalId>
        <label>CPF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fidelidade</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Esse cliente já possui registro de Fidelidade criado. Não é possível criar um novo registro.</errorMessage>
            <filterItems>
                <field>TW1_Fidelidade__c.TW1_Nome_Cliente__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cliente</relationshipLabel>
        <relationshipName>TW1_Relation_Fidelidade_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Cartoes_Estacionamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio__c</fullName>
        <label>Data início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Fidelidade__c</fullName>
        <label>Número Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cartões Estacionamento</relationshipLabel>
        <relationshipName>Cart_es_Estacionamento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Inativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cartão Estacionamento</label>
    <nameField>
        <label>Número do cartão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões Estacionamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Fidelidade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Modalidade__c</fullName>
        <label>Modalidade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Nome_Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nome do Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fidelidade</relationshipLabel>
        <relationshipName>Fidelidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fidelidade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número Fidelidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidelidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Tw1_Ancar_IntegracaoCartao_sch_tst.cls
@istest
public with sharing class Tw1_Ancar_IntegracaoCartao_sch_tst {
    
    @isTest static void testexecuteJob1() { 
        
        recordtype varecodtype=[select id,name from recordtype where name='Conta pessoal padrão' limit 1];
        
        Account act = new Account(); 
        act.FirstName ='Teste';
        act.LastName ='silva';
        act.TW1_CPF__c='74745710569';
        act.TW1_CNPJ__c='27364928000101';
        act.Phone = '2133337444';
        act.PersonMobilePhone = '21999984578';
        act.RecordTypeId = varecodtype.id;
        insert act;
        
        TW1_Fidelidade__c vafidelidade = new TW1_Fidelidade__c();
        vafidelidade.TW1_Modalidade__c='Prospect';
        vafidelidade.TW1_Nome_Cliente__c=act.id;
        insert vafidelidade; 
        
        TW1_Fidelidade__c vaUpdatefidelidade = [select id from TW1_Fidelidade__c where id=:vafidelidade.id];
        vaUpdatefidelidade.TW1_Modalidade__c='Gold';
        Update vaUpdatefidelidade;

        TW1_Cartoes_Estacionamento__c cartao = new TW1_Cartoes_Estacionamento__c();
        cartao.TW1_Numero_Fidelidade__c = vafidelidade.Id;
        Cartao.TW1_Status__c = 'Ativo';
        cartao.TW1_Data_Fim__c = DateTime.now().addMonths(3).date();
        cartao.TW1_Data_inicio__c = DateTime.now().date();
		insert cartao;
        
        Test.startTest();  
        	Tw1_Ancar_IntegracaoCartao_Handler_cls.executeJob();//.sendWithFuture(); 
        Test.stopTest();
    } 
    @isTest static void testexecuteJob2() { 
        
        recordtype varecodtype=[select id,name from recordtype where name='Conta pessoal padrão' limit 1];
        
        Account act = new Account(); 
        act.FirstName ='Teste';
        act.LastName ='silva';
        act.TW1_CPF__c='74745710569';
        act.TW1_CNPJ__c='27364928000101';
        act.Phone = '2133337444';
        act.PersonMobilePhone = '21999984578';
        act.RecordTypeId = varecodtype.id;
        insert act;
        
        TW1_Fidelidade__c vafidelidade = new TW1_Fidelidade__c();
        vafidelidade.TW1_Modalidade__c='Prospect';
        vafidelidade.TW1_Nome_Cliente__c=act.id;
        insert vafidelidade; 
        
        TW1_Fidelidade__c vaUpdatefidelidade = [select id from TW1_Fidelidade__c where id=:vafidelidade.id];
        vaUpdatefidelidade.TW1_Modalidade__c='Gold';
        Update vaUpdatefidelidade;

        TW1_Cartoes_Estacionamento__c cartao = new TW1_Cartoes_Estacionamento__c();
        cartao.TW1_Numero_Fidelidade__c = vafidelidade.Id;
        Cartao.TW1_Status__c = 'Ativo';
        cartao.TW1_Data_Fim__c = DateTime.now().addMonths(3).date();
        cartao.TW1_Data_inicio__c = DateTime.now().date();
		insert cartao;
        
       	Test.startTest();  
        Anc_ScheaduleUtils_cls.scheadule('Tw1_Ancar_IntegracaoCartao_sch', DateTime.now().addMinutes(1)); 
        Test.stopTest(); 
    } 
}