objects/Account.object
<CustomObject>
    <fields>
        <fullName>CEP__c</fullName>
        <label>CEP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DDD__c</fullName>
        <label>DDD</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Av_Rua__c</fullName>
        <label>Av./Rua</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Bairro__c</fullName>
        <label>Bairro</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <externalId>true</externalId>
        <label>CPF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Celular__c</fullName>
        <label>Celular</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>TW1_Cidade__c</fullName>
        <label>Cidade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Complemento__c</fullName>
        <label>Complemento</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Correspondencia__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Correspondência</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_DDI__c</fullName>
        <defaultValue>55</defaultValue>
        <label>DDI</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Nascimento__c</fullName>
        <label>Data de Nascimento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_EmailCB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Email__c</fullName>
        <label>E-mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TW1_Estado_civil__c</fullName>
        <label>Estado civil</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solteiro(a)</fullName>
                </value>
                <value>
                    <fullName>Casado(a)</fullName>
                </value>
                <value>
                    <fullName>Viúvo(a)</fullName>
                </value>
                <value>
                    <fullName>Divorciado(a)</fullName>
                </value>
                <value>
                    <fullName>União estável</fullName>
                </value>
                <value>
                    <fullName>Outros</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Identidade__c</fullName>
        <label>Identidade</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Numero__c</fullName>
        <label>Número</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Permite_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Permite SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Sexo__c</fullName>
        <label>Sexo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Masculino</fullName>
                </value>
                <value>
                    <fullName>Feminino</fullName>
                </value>
                <value>
                    <fullName>Indefinido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Contas (Shopping)</relationshipLabel>
        <relationshipName>Contas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_TelefoneCB__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Telefone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_UF_de_emissao__c</fullName>
        <label>UF de emissão</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AC</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AP</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>CE</fullName>
                </value>
                <value>
                    <fullName>DF</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>GO</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MG</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>PB</fullName>
                </value>
                <value>
                    <fullName>PE</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>PR</fullName>
                </value>
                <value>
                    <fullName>RJ</fullName>
                </value>
                <value>
                    <fullName>RN</fullName>
                </value>
                <value>
                    <fullName>RO</fullName>
                </value>
                <value>
                    <fullName>RR</fullName>
                </value>
                <value>
                    <fullName>RS</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>SE</fullName>
                </value>
                <value>
                    <fullName>SP</fullName>
                </value>
                <value>
                    <fullName>TO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Cupom__c.object
<CustomObject>
    <fields>
        <fullName>Numero__c</fullName>
        <label>Número</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sexo__c</fullName>
        <label>Sexo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Masculino</fullName>
                </value>
                <value>
                    <fullName>Feminino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Bairro__c</fullName>
        <label>Bairro</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_CEP__c</fullName>
        <label>CEP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <label>CPF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Celular__c</fullName>
        <label>Celular</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Cidade__c</fullName>
        <label>Cidade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Complemento__c</fullName>
        <label>Complemento</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Data__c</fullName>
        <label>Data</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_Nascimento__c</fullName>
        <label>Data de Nascimento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Email__c</fullName>
        <label>E-mail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_Lojista__c</fullName>
        <label>Nome Lojista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_da_Loja__c</fullName>
        <label>Nome da Loja</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_do_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nome do Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Conta pessoal padrão</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cupons</relationshipLabel>
        <relationshipName>Cupons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Pergunta__c</fullName>
        <label>Pergunta</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_RG__c</fullName>
        <label>RG</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Rua__c</fullName>
        <label>Rua</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Cupom</label>
    <nameField>
        <displayFormat>CUP-{0000000000}</displayFormat>
        <label>Número do Cupom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cupons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Operador__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Email__c</fullName>
        <externalId>true</externalId>
        <label>E-mail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Operadores</relationshipLabel>
        <relationshipName>Operadores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Operador</label>
    <nameField>
        <label>Nome do Operador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Parametros_Promocao__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Cert_de_Aut__c</fullName>
        <label>Cert. de Aut.</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Cidade__c</fullName>
        <label>Cidade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Pergunta__c</fullName>
        <label>Pergunta</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipName>Promo_es</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parâmetros da Promoção</label>
    <nameField>
        <label>Nome da Promoção</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parâmetros da Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>DDD__c</fullName>
        <label>DDD</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Cidade__c</fullName>
        <label>Cidade</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_DDI__c</fullName>
        <label>DDI</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TrocarCuponManager.cls
/******************************************************************************************************
Author  	: Leonardo Façanha
Date    	: 22/12/2017
Purpose 	: Api Rest para buscar informações do Trocar Cupon para a aplicação de promoção
*******************************************************************************************************/
@RestResource(urlMapping='/TrocarCupom/*')
global with sharing class TrocarCuponManager {
	
    @HttpGet
    global static requestWrapper getTrocarCuponPorId(){
        try{
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
      
        String accountId = req.params.get('accountId');
        Integer Quantidade = Integer.valueOf(req.params.get('QuantidadeCupons'));
        String Shopping = req.params.get('IdShopping');
        String IdOperador = req.params.get('IdOperador');
        String NomeLojista = req.params.get('NomeLojista') == null? '':req.params.get('NomeLojista');
        String NomeLoja = req.params.get('NomeLoja') == null ? '':req.params.get('NomeLoja');
		
        Boolean EspacoNomeLojista = NomeLojista.contains('-');
            
        If(EspacoNomeLojista)
        NomeLojista = NomeLojista.replace('-', ' ');
            
        Boolean EspacoNomeLoja = NomeLoja.contains('-');
            
        If(EspacoNomeLoja)
        NomeLoja = NomeLoja.replace('-', ' ');
            
            
        requestWrapper acc = new requestWrapper();
        acc.cupom = new List<Cupom>();
         List<TW1_Cupom__c> Listcup = new List<TW1_Cupom__c>();
		 date vaData = DateTime.now().date();
            
        TW1_Parametros_Promocao__c Promocao = [Select Id,Name,TW1_Cert_de_Aut__c,TW1_Pergunta__c From TW1_Parametros_Promocao__c Where TW1_Shopping__c=:Shopping And TW1_Data_Fim__c >=:vaData Limit 1];
        TW1_Shopping__c shoppingCorrente = [Select Id,Name From TW1_Shopping__c Where Id=:Shopping Limit 1];
            
        Account account = [Select  Id,
                        FirstName,
                        LastName,
                        Name,
                        TW1_Av_Rua__c,
                        TW1_Numero__c,
                        TW1_Bairro__c,
                        CEP__c,
                        TW1_Complemento__c,
                        TW1_Estado_civil__c,
                        TW1_Sexo__c,
                        TW1_Cidade__c,
                        TW1_UF_de_emissao__c,
                        TW1_CPF__c,
                        TW1_Identidade__c,
                        PersonEmail,
                        TW1_Permite_SMS__c,
                        TW1_Data_Nascimento__c,
                        DDD__c,
                        TW1_DDI__c,
                        Phone,
                        TW1_EmailCB__c,
                        TW1_TelefoneCB__c,
                        TW1_Correspondencia__c
                        FROM Account Where Id=:accountId Limit 1];

        for(Integer i = 1; i <= Quantidade; i++)
        {
            TW1_Cupom__c cup = new TW1_Cupom__c();
            
              cup.TW1_Nome_Lojista__c = NomeLojista;
              cup.TW1_Nome_da_Loja__c = NomeLoja;
              cup.TW1_Data__c = DateTime.now();
              cup.TW1_Nome_do_Cliente__c = accountId;
              cup.TW1_Bairro__c =  account.TW1_Bairro__c;
              cup.TW1_Celular__c =  String.valueOf(account.DDD__c) + String.valueOf(account.Phone);
              cup.TW1_CEP__c =  String.valueOf(account.CEP__c);
              cup.TW1_Cidade__c =  account.TW1_Cidade__c;
              cup.TW1_Complemento__c =  account.TW1_Complemento__c;
              cup.TW1_CPF__c =  account.TW1_CPF__c;
              cup.TW1_Data_de_Nascimento__c =  account.TW1_Data_Nascimento__c;
              cup.TW1_Email__c =  account.PersonEmail;
              cup.Numero__c =  account.TW1_Numero__c;
              cup.TW1_RG__c =  account.TW1_Identidade__c;
              cup.TW1_Rua__c =  account.TW1_Av_Rua__c;
              cup.Sexo__c =  account.TW1_Sexo__c;
              cup.TW1_UF__c =  account.TW1_UF_de_emissao__c;
           	  cup.TW1_Certificado_Autenticao_Promocao__c = 	Promocao.TW1_Cert_de_Aut__c;
              cup.TW1_Pergunta__c = Promocao.TW1_Pergunta__c;
              cup.TW1_Operador__c = IdOperador;
              cup.TW1_Shopping_Lookup__c = shoppingCorrente.Id;
              //cup.TW1_Formas_de_Pagamento__c = ;
              cup.TW1_Parametro_Promocao__c = Promocao.Id;
              
              Listcup.add(cup);             
        }  
        
        insert Listcup;
            
        Map<Id,TW1_Cupom__c> MapCup = new Map<Id,TW1_Cupom__c>(Listcup);
        
        List<Tw1_Cupom__c> listaCupom = [Select Id,Name,TW1_Operador__r.Name From TW1_Cupom__c Where Id In:MapCup.keySet()];
        
        Map<Id,TW1_Cupom__c> litsMapCup = new Map<Id,TW1_Cupom__c>(listaCupom);

        acc.cupom = MapCupom(litsMapCup,Listcup,Promocao,account,shoppingCorrente,NomeLojista,NomeLoja);
        
         return acc;

        }
        catch (Exception ex) {
               return new requestWrapper();
           }  
    }

    Private static List<Cupom> MapCupom(Map<Id,TW1_Cupom__c> litsMapCup,List<TW1_Cupom__c> Listcup,TW1_Parametros_Promocao__c Promocao,Account account,TW1_Shopping__c shoppingCorrente, string NomeLojista,string NomeLoja)
    {
        List<Cupom> listcupomSalesforce = new List<Cupom>();

        for(TW1_Cupom__c Cup : Listcup){
        
        Cupom cupom = new Cupom();
			
            DateTime dataCup = Cup.TW1_Data__c;
            
            cupom.Nome_Lojista = NomeLojista;
            cupom.Nome_da_Loja = NomeLoja;
            cupom.TW1_DataCupom = dataCup.format('dd/MM/yyyy HH:mm:ss');
            cupom.Numero_Cupom = litsMapCup.get(Cup.Id).Name;
            cupom.TW1_Nome_do_Cliente = account.Name;
            cupom.TW1_Bairro =  account.TW1_Bairro__c;
            cupom.TW1_Celular =  String.valueOf(account.DDD__c) + String.valueOf(account.Phone);
            cupom.TW1_CEP =  String.valueOf(account.CEP__c);
            cupom.TW1_Cidade =  account.TW1_Cidade__c;
            cupom.TW1_Complemento =  account.TW1_Complemento__c;
            cupom.TW1_CPF =  account.TW1_CPF__c;
            cupom.TW1_Data_de_Nascimento = account.TW1_Data_Nascimento__c.day() + '/' + account.TW1_Data_Nascimento__c.month() + '/' + account.TW1_Data_Nascimento__c.year();
            System.debug(cupom.TW1_Data_de_Nascimento);
            cupom.TW1_Email =  account.PersonEmail;
            cupom.Numero =  String.valueOf(account.TW1_Numero__c);
            cupom.TW1_RG =  account.TW1_Identidade__c;
            cupom.TW1_Rua =  account.TW1_Av_Rua__c;
            cupom.Sexo =  account.TW1_Sexo__c;
            cupom.TW1_UF =  account.TW1_UF_de_emissao__c;
            cupom.TW1_Certificado_Autenticao_Promocao = Promocao.TW1_Cert_de_Aut__c;
            cupom.TW1_Pergunta = Promocao.TW1_Pergunta__c;
            cupom.TW1_Operador = litsMapCup.get(Cup.Id).TW1_Operador__r.Name;
            cupom.Nome_Parametro_Promocao = Promocao.Name;
            cupom.Nome_Shopping = shoppingCorrente.Name; 

            listcupomSalesforce.add(cupom);
        }

        return listcupomSalesforce;       
    }
    
    global class requestWrapper 
    {
        public List<Cupom> cupom;
    }

    global class Cupom 
    {
        public String Numero_Cupom;
        public String TW1_DataCupom;
        public String TW1_Nome_do_Cliente;
        public String TW1_Bairro; 
        public String TW1_Celular;
        public String TW1_CEP; 
        public String TW1_Cidade; 
        public String TW1_Complemento;
        public String TW1_CPF;
        public String TW1_Data_de_Nascimento; 
        public String TW1_Email;
        public String Numero; 
        public String TW1_RG; 
        public String TW1_Rua; 
        public String Sexo;
        public String TW1_UF; 
        public String TW1_Certificado_Autenticao_Promocao; 
        public String TW1_Pergunta;
        public String TW1_Operador; 
        public String Nome_Parametro_Promocao;
        Public String Nome_Shopping; 
        Public String Nome_da_Loja;
        Public String Nome_Lojista;
    }
}