objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TW1_OpportunityRecordTypeName__c</fullName>
        <formula>RecordType.Name</formula>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_Oportunidade_Rep.cls
public class TW1_Ancar_Venda_Oportunidade_Rep {
    
    /// Buscar oportunidade pelo ID
    public Opportunity GetOpportunityById(string idOpportunity){
        system.debug('Consultando oportunidade com o ID: ' + idOpportunity);
        List<Opportunity> vaOpportunitys = [select id,name,TW1_Shopping__c,TW1_OpportunityRecordTypeName__c, recordtype.name from Opportunity WHERE id=:idOpportunity limit 1];
        system.debug('Retorno da consulta Consultando oportunidade com o ID: ' + idOpportunity + ' retorno: ' + vaOpportunitys);
        
        if(vaOpportunitys.size() <1)
            return null;
        else
            return vaOpportunitys[0];        
    }
}