objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Acrescimo_sazonal_dezembro__c</fullName>
        <label>Acréscimo sazonal dezembro (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Acrescimo_sazonal_maio__c</fullName>
        <label>Acréscimo sazonal maio (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Acrescimo_sazonal_novembro__c</fullName>
        <label>Acréscimo sazonal novembro (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Aluguel_Percentual__c</fullName>
        <label>Aluguel %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TW1_Area_utilizada__c</fullName>
        <label>Área utilizada</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condomínio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_FPP__c</fullName>
        <label>FPP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Forma_pagamento_pacote_de_midia__c</fullName>
        <label>Forma de pagamento pacote de mídia</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Periodo_de_locacao__c</fullName>
        <label>Período de locação</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Indeterminado</fullName>
                </value>
                <value>
                    <fullName>Determinado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Taxa_de_transferencia__c</fullName>
        <label>Taxa de transferência</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_pacote_de_midia__c</fullName>
        <label>Valor de pacote de mídia</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condominio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade_da_Cotacao__c.object
<CustomObject>
    <description>Objeto de junção entre propriedade e cotação</description>
    <fields>
        <fullName>TW1_Cotacao__c</fullName>
        <label>Cotação</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_fim__c</fullName>
        <label>Data de fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_inicio__c</fullName>
        <label>Data de início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade da Cotação</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propriedades da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_CotacaoMallApplication.cls
public class TW1_Ancar_Venda_CotacaoMallApplication {
    
    public TW1_Ancar_wrapRecodtypes rec = new TW1_Ancar_wrapRecodtypes();
    
    /// Repositório de oportunidade
    public TW1_Ancar_Venda_Oportunidade_Rep oportunidadeRepository = new TW1_Ancar_Venda_Oportunidade_Rep();
    
    /// Repositório de propriedade
    public TW1_Ancar_Venda_Propriedade_Rep propriedadeRepository = new TW1_Ancar_Venda_Propriedade_Rep();
     
    /// Repositório de cotação 
    public TW1_Ancar_Venda_Cotacao_Rep cotacaoRepository = new TW1_Ancar_Venda_Cotacao_Rep();
    
    /// Application de cálculo de cotação
    public TW1_Ancar_Venda_CalculosCotaApplication calculoApplication = new TW1_Ancar_Venda_CalculosCotaApplication();
    
    public list<string> getListSubTipoDePropriedadeMall(){
        list<String> subtipos = new list<String>();
        
        subtipos.add('Antena');
        subtipos.add('Caixa Eletronico');
        subtipos.add('Deposito');
        subtipos.add('Quiosque');
        
        return subtipos;
    }
    
    public list<string> getListPeriodoLocacao(){
        list<String> tipoLocacao = new list<String>();
        
        tipoLocacao.add('Determinado');
        tipoLocacao.add('Indeterminado');
        
        return tipoLocacao;
    }
        
    public List<SObject> PesquisarPropriedadeCotacaoMall(String opportunityId,String subTipo)
    {
        Opportunity opportunity = oportunidadeRepository.GetOpportunityById(opportunityId);
        return propriedadeRepository.ListarPropriedadeMall(opportunity.TW1_Shopping__c, subTipo);
    }
    
    private RecordType getRecordtype(String vaNomeDoRecodtype){
        return [SELECT Id,Name FROM RecordType WHERE Name=:vaNomeDoRecodtype limit 1];
    }
    
    public void SalvarCotacao(Quote cotacao, string idPropriedade, string nomePropriedade)
    {   
        Savepoint sp = Database.setSavepoint();
        
        try{
            String vaRecordType ='';
            
            cotacao.RecordTypeId = this.getRecordtype(rec.rec_Cotcao_mall).id;
            cotacao.Name = nomePropriedade + ' - ' + Date.today().day() + '/' + Date.today().month() + '/' + Date.today().year();
            
            system.debug('Inserindo cotação de mall');
            Insert cotacao;
            system.debug('Cotação inserida ');
            
            ///Montando lista de propriedades de cotação
            list<TW1_Propriedade_da_Cotacao__c> propCotacao = new List<TW1_Propriedade_da_Cotacao__c>();
            
            TW1_Propriedade_da_Cotacao__c vaPropriedadeCotacao = new TW1_Propriedade_da_Cotacao__c();
            vaPropriedadeCotacao.TW1_Cotacao__c = cotacao.id;
            vaPropriedadeCotacao.TW1_Propriedade__c = idPropriedade;
            vaPropriedadeCotacao.TW1_Data_de_inicio__c = cotacao.TW1_Data_inicio_de_vigencia__c;
            vaPropriedadeCotacao.TW1_Data_de_fim__c = cotacao.TW1_Data_fim_de_vigencia__c;
            vaPropriedadeCotacao.TW1_Valor__c = cotacao.TW1_AMM__c;
            propCotacao.add(vaPropriedadeCotacao);
            
            system.debug('Inserindo propriedade');
            Insert propCotacao;
            system.debug('Propriedade inserida');
            
            //Executa calculo da cotação
            system.debug('Executando cálculo da cotação: ' + cotacao);
            cotacao = calculoApplication.CalcularCotacaco(cotacao, propCotacao);
            system.debug('Cálculos executados: ' + cotacao);
            
            update cotacao;
        }
        catch(Exception ex){
            System.debug('erro de cotação:'+ex.getMessage());
            Database.rollback(sp);
            throw ex;
        }
    }
    
    public TW1_Ancar_Venda_CotacaoMall_LP_ctrl.CotacaoMallRequest GetCotacaoCloneMall(string vaCotacaoId){
        
        quote cotacao = cotacaoRepository.GetCotacaoById(vaCotacaoId);
        TW1_Propriedade__c listPropriedades = propriedadeRepository.GetPropriedadeByIdCotacaoMALL(vaCotacaoId);
        System.debug('listPropriedades: '+listPropriedades);
        listPropriedades =  listPropriedades == null? new TW1_Propriedade__c() : listPropriedades;
        System.debug('listPropriedades Old: '+listPropriedades);
        TW1_Ancar_Venda_CotacaoMall_LP_ctrl.CotacaoMallRequest cotacaoDto = MapCotacaoPropriedadeClone(cotacao,listPropriedades);
        System.debug('MapCotacaoPropriedadeClone: '+cotacaoDto);
        return cotacaoDto;
    }
    
    public TW1_Ancar_Venda_CotacaoMall_LP_ctrl.CotacaoMallRequest MapCotacaoPropriedadeClone(quote cotacao,TW1_Propriedade__c listPropriedades)
    {
        TW1_Ancar_Venda_CotacaoMall_LP_ctrl.CotacaoMallRequest cotacaoDto = new TW1_Ancar_Venda_CotacaoMall_LP_ctrl.CotacaoMallRequest();
		cotacaoDto.OpportunityId = cotacao.OpportunityId;       
        cotacaoDto.PeriodoLocacao = cotacao.TW1_Periodo_de_locacao__c;	
        cotacaoDto.DataInicio = cotacao.TW1_Data_inicio_de_vigencia__c;	
      	cotacaoDto.DataFim = cotacao.TW1_Data_fim_de_vigencia__c;
        cotacaoDto.AMM = cotacao.TW1_AMM__c;
        cotacaoDto.Condominio = cotacao.TW1_Condominio__c;
        cotacaoDto.FPP = cotacao.TW1_FPP__c;
        cotacaoDto.AluguelPercentual = cotacao.TW1_Aluguel_Percentual__c;
        cotacaoDto.AcrescimoSazonalMaio = cotacao.TW1_Acrescimo_sazonal_maio__c;
        cotacaoDto.AcrescimoSazonalNovembro = cotacao.TW1_Acrescimo_sazonal_novembro__c;
        cotacaoDto.AcrescimoSazonalDezembro = cotacao.TW1_Acrescimo_sazonal_dezembro__c;
        cotacaoDto.ValorPacoteMidia = cotacao.TW1_Valor_pacote_de_midia__c;
        //cotacaoDto.TaxaTransferencia = cotacao.TW1_Taxa_de_transferencia__c;
        cotacaoDto.FormaPagamentoPacoteMidia = cotacao.TW1_Forma_pagamento_pacote_de_midia__c;
        cotacaoDto.Observacao = cotacao.Description;
        cotacaoDto.IdPropriedade = listPropriedades.Id;
        cotacaoDto.NomePropriedade = listPropriedades.Name;
        cotacaoDto.AreaUtilizada = cotacao.TW1_Area_utilizada__c;
        return cotacaoDto;
    }
	
}