objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Prazo__c</fullName>
        <label>Prazo (dias)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Frio</fullName>
                    <default>true</default>
                    <label>Frio</label>
                </value>
                <value>
                    <fullName>Morno</fullName>
                </value>
                <value>
                    <fullName>Quente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM_10__c</fullName>
        <label>AMM 10</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_1__c</fullName>
        <label>AMM 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_2__c</fullName>
        <label>AMM 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_3__c</fullName>
        <label>AMM 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_4__c</fullName>
        <label>AMM 4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_5__c</fullName>
        <label>AMM 5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_6__c</fullName>
        <label>AMM 6</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_7__c</fullName>
        <label>AMM 7</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_8__c</fullName>
        <label>AMM 8</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_9__c</fullName>
        <label>AMM 9</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Aluguel_Percentual__c</fullName>
        <label>Aluguel %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TW1_CDU__c</fullName>
        <label>CDU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Carencia__c</fullName>
        <label>Carência</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condomínio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_FPP__c</fullName>
        <label>FPP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Forma_de_pagamento_da_CDU__c</fullName>
        <label>Forma de pagamento da CDU</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Forma_pagamento_pacote_de_midia__c</fullName>
        <label>Forma de pagamento pacote de mídia</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Mes_aluguel_dobrado__c</fullName>
        <label>Mês de aluguel dobrado</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Janeiro</fullName>
                </value>
                <value>
                    <fullName>Fevereiro</fullName>
                </value>
                <value>
                    <fullName>Março</fullName>
                </value>
                <value>
                    <fullName>Abril</fullName>
                </value>
                <value>
                    <fullName>Maio</fullName>
                </value>
                <value>
                    <fullName>Junho</fullName>
                </value>
                <value>
                    <fullName>Julho</fullName>
                </value>
                <value>
                    <fullName>Agosto</fullName>
                </value>
                <value>
                    <fullName>Setembro</fullName>
                </value>
                <value>
                    <fullName>Outubro</fullName>
                </value>
                <value>
                    <fullName>Novembro</fullName>
                </value>
                <value>
                    <fullName>Dezembro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Prazo__c</fullName>
        <label>Prazo (dias)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Taxa_de_transferencia__c</fullName>
        <label>Taxa de transferência</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_pacote_de_midia__c</fullName>
        <label>Valor de pacote de mídia</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Ativa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ativa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condominio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Fundo__c</fullName>
        <label>Fundo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Nota_de_d_bito_ou_CTO__c</fullName>
        <label>Nota de débito ou CTO</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_OTN__c</fullName>
        <label>OTN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Observacao__c</fullName>
        <label>Observação</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Piso__c</fullName>
        <label>Piso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1º andar</fullName>
                </value>
                <value>
                    <fullName>Subsolo</fullName>
                </value>
                <value>
                    <fullName>2º andar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Res_Perata__c</fullName>
        <label>Res Perata</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato assinado</fullName>
                </value>
                <value>
                    <fullName>Repasse</fullName>
                </value>
                <value>
                    <fullName>Vaga</fullName>
                </value>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Status_da_prospecao__c</fullName>
        <label>Prospecção/Proposta aprovada</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Subtipo__c</fullName>
        <label>Subtipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Âncora</fullName>
                </value>
                <value>
                    <fullName>Depósito</fullName>
                </value>
                <value>
                    <fullName>Megaloja</fullName>
                </value>
                <value>
                    <fullName>Quiosque</fullName>
                </value>
                <value>
                    <fullName>Satélite</fullName>
                </value>
                <value>
                    <fullName>Mega Banner</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Totem Digital</fullName>
                </value>
                <value>
                    <fullName>Adesivos de Mesa</fullName>
                </value>
                <value>
                    <fullName>Portas de Acesso</fullName>
                </value>
                <value>
                    <fullName>Totem Interno</fullName>
                </value>
                <value>
                    <fullName>Feiras e Eventos</fullName>
                </value>
                <value>
                    <fullName>Colunas Mall</fullName>
                </value>
                <value>
                    <fullName>Colunas Praça de Alimentação</fullName>
                </value>
                <value>
                    <fullName>Painel Backlight</fullName>
                </value>
                <value>
                    <fullName>Porta de Banheiro</fullName>
                </value>
                <value>
                    <fullName>Testeira</fullName>
                </value>
                <value>
                    <fullName>Espelho de Banheiro</fullName>
                </value>
                <value>
                    <fullName>Painel Fachada</fullName>
                </value>
                <value>
                    <fullName>Painel</fullName>
                </value>
                <value>
                    <fullName>Adoção de Espaço</fullName>
                </value>
                <value>
                    <fullName>Cancela Estacionamento</fullName>
                </value>
                <value>
                    <fullName>Painel Frontlight</fullName>
                </value>
                <value>
                    <fullName>Adesivo Piso</fullName>
                </value>
                <value>
                    <fullName>Escada Rolante</fullName>
                </value>
                <value>
                    <fullName>Display Mall</fullName>
                </value>
                <value>
                    <fullName>Panfletagem</fullName>
                </value>
                <value>
                    <fullName>Portas de Elevador</fullName>
                </value>
                <value>
                    <fullName>Display Mesa</fullName>
                </value>
                <value>
                    <fullName>Stand Temporário</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_de_tabela__c</fullName>
        <label>Valor de tabela</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_area_m2__c</fullName>
        <label>Área (m²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_CotacaoLoja_Test.cls
@isTest
public class TW1_Ancar_Venda_CotacaoLoja_Test {
    
    @isTest static void getDataAtual() {
        
        Date data = TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.getDataAtual();
        System.assertEquals(Date.today(), data);
    }
    
    @isTest static void getCotacaoClone() {
        
		Opportunity opportunity = TW1_Ancar_OpportunityMockGenerator_cls.getLojaMock();
        
        Quote quote = TW1_Ancar_CotacaoMockGenerator_cls.getLojaMock(opportunity.Id);   
        
        TW1_Propriedade__c propriedade = TW1_Ancar_PropriedadeMockGenerator_cls.getLojaMock(quote.Id);
        
        CotacaoDto cotacaoDto = MapCotacaoPropriedade(quote, propriedade);      
        System.debug('CotacaoDto Mock:' + cotacaoDto);
        
        //Expected
        string jsonData = JSON.serialize((Object)cotacaoDto);
        
        //Actual
        String listJson = TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.getCotacaoClone(quote.Id);
        
        System.assertEquals(jsonData, listJson);
    }
        
    @isTest static void getListaPropriedadesDisponiveis() {
        
 		Opportunity opportunity = TW1_Ancar_OpportunityMockGenerator_cls.getLojaMock();
        
        Quote quote = TW1_Ancar_CotacaoMockGenerator_cls.getLojaMock(opportunity.Id);   
        
        TW1_Propriedade__c propriedade = TW1_Ancar_PropriedadeMockGenerator_cls.getLojaMock(quote.Id);
        
        //Expected
        List<sObject> propriedadesMock = ListarPropriedadeLoja(opportunity.TW1_Shopping__c);
        System.debug(propriedadesMock);
        
        //Actual
        List<SObject> propriedades = TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.getListaPropriedadesDisponiveis(opportunity.Id);
        System.debug(propriedades);
        
        System.assertEquals(propriedadesMock, propriedades);
    }
        
    @isTest static void getListaMeses() {
        
        List<string> mesesMock = new List<string>();
        mesesMock.add('Janeiro');
        mesesMock.add('Fevereiro');
        mesesMock.add('Março');
        mesesMock.add('Abril');
        mesesMock.add('Maio');
        mesesMock.add('Junho');
        mesesMock.add('Julho');
        mesesMock.add('Agosto');
        mesesMock.add('Setembro');
        mesesMock.add('Outubro');
        mesesMock.add('Novembro');
        mesesMock.add('Dezembro');
        
        List<string> meses = TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.getListaMeses();
        System.assertEquals(mesesMock, meses);
    }
    
    @isTest static void salvarCotacao() {
        
		Opportunity opportunity = TW1_Ancar_OpportunityMockGenerator_cls.getLojaMock();
        System.debug('opportunity: ' + opportunity);
        
        Quote quote = TW1_Ancar_CotacaoMockGenerator_cls.getLojaMock(opportunity.Id); 
        System.debug('quote: ' + quote);  
        
        TW1_Propriedade__c propriedade = TW1_Ancar_PropriedadeMockGenerator_cls.getLojaMock(quote.Id);
        System.debug('propriedade: ' + propriedade);  
                
        CotacaoDto cotacaoDTO = MapCotacaoPropriedade(quote, propriedade);
        System.debug(cotacaoDTO);
        
        String dtoSerialized = JSON.serialize(cotacaoDTO);
        System.debug(dtoSerialized);
        
        String sucesso = TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.SalvarCotacao(opportunity.Id, propriedade.Id, dtoSerialized);
        
        System.assertEquals('SUCESSO', sucesso);
    }
    
    public static CotacaoDto MapCotacaoPropriedade(quote cotacao,TW1_Propriedade__c Propriedade)
    {
        CotacaoDto cotacaoDto = new CotacaoDto();
         
        cotacaoDto.OpportunityId = cotacao.OpportunityId;
        cotacaoDto.ValorFPP = cotacao.TW1_FPP__c;
        cotacaoDto.Amm1 = cotacao.TW1_AMM_1__c;
        cotacaoDto.Amm2 = cotacao.TW1_AMM_2__c;
        cotacaoDto.Amm3 = cotacao.TW1_AMM_3__c;
        cotacaoDto.Amm4 = cotacao.TW1_AMM_4__c;
        cotacaoDto.Amm5 = cotacao.TW1_AMM_5__c;
        cotacaoDto.Amm6 = cotacao.TW1_AMM_6__c;
        cotacaoDto.Amm7 = cotacao.TW1_AMM_7__c;
        cotacaoDto.Amm8 = cotacao.TW1_AMM_8__c;
        cotacaoDto.Amm9 = cotacao.TW1_AMM_9__c;
        cotacaoDto.Amm10 = cotacao.TW1_AMM_10__c;
        cotacaoDto.Periodo = cotacao.TW1_Prazo__c;
        cotacaoDto.ValorMidia  = cotacao.TW1_Valor_pacote_de_midia__c;
        cotacaoDto.FormaPagamentoMidia = cotacao.TW1_Forma_pagamento_pacote_de_midia__c;
        cotacaoDto.ValorCondominio = cotacao.TW1_Condominio__c;
        cotacaoDto.AluguelPercentual  = cotacao.TW1_Aluguel_Percentual__c;
        cotacaoDto.ValorCDU = cotacao.TW1_CDU__c;
        cotacaoDto.FormaPagamentoCDU = cotacao.TW1_Forma_de_pagamento_da_CDU__c;
        cotacaoDto.Carencia = cotacao.TW1_Carencia__c;
        cotacaoDto.MesAluguelDobrado = cotacao.TW1_Mes_aluguel_dobrado__c;
        cotacaoDto.Observavao = cotacao.Description;
        cotacaoDto.DataInicio = cotacao.TW1_Data_inicio_de_vigencia__c;
        cotacaoDto.DataFim = cotacao.TW1_Data_fim_de_vigencia__c;
        cotacaoDto.TaxaTransferencia = cotacao.TW1_Taxa_de_transferencia__c;
     	cotacaoDto.Propriedade = Propriedade;
        return cotacaoDto;
    }
    
    public class CotacaoDto
    {
        public Date DataInicio {get;set;}
        public String OpportunityId{get;set;}
        public Date DataFim {get;set;}
        public Decimal Amm1 {get;set;}
        public Decimal Amm2 {get;set;}
        public Decimal Amm3 {get;set;}
        public Decimal Amm4 {get;set;}
        public Decimal Amm5 {get;set;}
        public Decimal Amm6 {get;set;}
        public Decimal Amm7 {get;set;}
        public Decimal Amm8 {get;set;}
        public Decimal Amm9 {get;set;}
        public Decimal Amm10 {get;set;}
        public Decimal ValorCondominio {get;set;}
        public Decimal ValorFPP {get;set;}
        public Decimal ValorCDU {get;set;}
        public String FormaPagamentoCDU{get;set;}
        public Decimal AluguelPercentual{get;set;}
        public string Carencia{get;set;}
        public String MesAluguelDobrado{get;set;}
        public Decimal ValorMidia{get;set;}
        public String FormaPagamentoMidia{get;set;}
        public Decimal TaxaTransferencia{get;set;}
        public String Observavao{get;set;}
        public Decimal Periodo{get;set;}
        public TW1_Propriedade__c Propriedade{get;set;}
    }
    
    private static List<SObject> ListarPropriedadeLoja(Id idShopping)
    {
        try{
            
            List<TW1_Propriedade__c> vaPropriedade = [
                Select
                id,
                Name,
                TW1_Shopping__c,
                TW1_Subtipo__c,
                TW1_Piso__c,
                TW1_area_m2__c, 
                TW1_Observacao__c,
                TW1_Status__c,
                TW1_Ativa__c,
                TW1_Status_da_prospecao__c,
                TW1_AMM__c,
                TW1_Fundo__c,
                TW1_OTN__c,
                TW1_Condominio__c,
                TW1_Nota_de_d_bito_ou_CTO__c,
                TW1_Res_Perata__c,
                TW1_IPTU__c,
                TW1_Valor_TR__c,
                TW1_Valor_de_tabela__c
                from 
                TW1_Propriedade__c 
                where
                TW1_Ativa__c = true and
                TW1_Shopping__c =:idShopping and 
                (
                    TW1_Status__c='Vaga' or 
                    TW1_Status__c='Repasse'
                ) and
                (
                    TW1_Subtipo__c ='Âncora' or
                    TW1_Subtipo__c ='Megaloja' or
                    TW1_Subtipo__c ='Satélite'
                )
            ];
            
            System.debug('Propriedade loja' + vaPropriedade);
            if(vaPropriedade.size() >= 1){
                return vaPropriedade;
            }else{
                return null;
            }
            
        }catch(Exception ex){
            system.debug('Erro em consultar ListarPropriedadeLoja EX:' +ex);
            return null;
        }
    }
}