objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Frio</fullName>
                    <default>true</default>
                    <label>Frio</label>
                </value>
                <value>
                    <fullName>Morno</fullName>
                </value>
                <value>
                    <fullName>Quente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Atividade__c</fullName>
        <label>Atividade (descrição da ação)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condomínio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_pagamento__c</fullName>
        <label>Data de pagamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Segunda_data_de_pagamento__c</fullName>
        <label>Segunda data de pagamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_Desconto__c</fullName>
        <label>Valor Desconto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Calendario_de_propriedades__c.object
<CustomObject>
    <description>Objeto que deve registrar o calendário de locação das propriedades.</description>
    <fields>
        <fullName>TW1_Data_de_fim__c</fullName>
        <label>Data de fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_inicio__c</fullName>
        <label>Data de início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Calendário de propriedades</relationshipLabel>
        <relationshipName>Calendario_de_propriedades</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_ShoppingId__c</fullName>
        <formula>TW1_Propriedade__r.TW1_Shopping__c</formula>
        <label>ShoppingId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calendário de propriedade</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendário de propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Ativa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ativa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condominio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Fundo__c</fullName>
        <label>Fundo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Localizacao__c</fullName>
        <label>Localização</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nota_de_d_bito_ou_CTO__c</fullName>
        <label>Nota de débito ou CTO</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_OTN__c</fullName>
        <label>OTN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Observacao__c</fullName>
        <label>Observação</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Piso__c</fullName>
        <label>Piso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1º andar</fullName>
                </value>
                <value>
                    <fullName>Subsolo</fullName>
                </value>
                <value>
                    <fullName>2º andar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Res_Perata__c</fullName>
        <label>Res Perata</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato assinado</fullName>
                </value>
                <value>
                    <fullName>Repasse</fullName>
                </value>
                <value>
                    <fullName>Vaga</fullName>
                </value>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Status_da_prospecao__c</fullName>
        <label>Prospecção/Proposta aprovada</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Subtipo__c</fullName>
        <label>Subtipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Âncora</fullName>
                </value>
                <value>
                    <fullName>Depósito</fullName>
                </value>
                <value>
                    <fullName>Megaloja</fullName>
                </value>
                <value>
                    <fullName>Quiosque</fullName>
                </value>
                <value>
                    <fullName>Satélite</fullName>
                </value>
                <value>
                    <fullName>Mega Banner</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Totem Digital</fullName>
                </value>
                <value>
                    <fullName>Adesivos de Mesa</fullName>
                </value>
                <value>
                    <fullName>Portas de Acesso</fullName>
                </value>
                <value>
                    <fullName>Totem Interno</fullName>
                </value>
                <value>
                    <fullName>Feiras e Eventos</fullName>
                </value>
                <value>
                    <fullName>Colunas Mall</fullName>
                </value>
                <value>
                    <fullName>Colunas Praça de Alimentação</fullName>
                </value>
                <value>
                    <fullName>Painel Backlight</fullName>
                </value>
                <value>
                    <fullName>Porta de Banheiro</fullName>
                </value>
                <value>
                    <fullName>Testeira</fullName>
                </value>
                <value>
                    <fullName>Espelho de Banheiro</fullName>
                </value>
                <value>
                    <fullName>Painel Fachada</fullName>
                </value>
                <value>
                    <fullName>Painel</fullName>
                </value>
                <value>
                    <fullName>Adoção de Espaço</fullName>
                </value>
                <value>
                    <fullName>Cancela Estacionamento</fullName>
                </value>
                <value>
                    <fullName>Painel Frontlight</fullName>
                </value>
                <value>
                    <fullName>Adesivo Piso</fullName>
                </value>
                <value>
                    <fullName>Escada Rolante</fullName>
                </value>
                <value>
                    <fullName>Display Mall</fullName>
                </value>
                <value>
                    <fullName>Panfletagem</fullName>
                </value>
                <value>
                    <fullName>Portas de Elevador</fullName>
                </value>
                <value>
                    <fullName>Display Mesa</fullName>
                </value>
                <value>
                    <fullName>Stand Temporário</fullName>
                </value>
                <value>
                    <fullName>Adoção Fraldário</fullName>
                </value>
                <value>
                    <fullName>Voicer de cancela</fullName>
                </value>
                <value>
                    <fullName>Mock up</fullName>
                </value>
                <value>
                    <fullName>Placas aéreas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_de_tabela__c</fullName>
        <label>Valor de tabela</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_area_m2__c</fullName>
        <label>Área (m²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade_da_Cotacao__c.object
<CustomObject>
    <description>Objeto de junção entre propriedade e cotação</description>
    <fields>
        <fullName>TW1_Area__c</fullName>
        <label>Área</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Cotacao__c</fullName>
        <label>Cotação</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_fim__c</fullName>
        <label>Data de fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_inicio__c</fullName>
        <label>Data de início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Localizacao__c</fullName>
        <label>Localização</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade da Cotação</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propriedades da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_CotacaoMidia_Test.cls
@isTest
public class TW1_Ancar_Venda_CotacaoMidia_Test {

    public static TW1_Ancar_wrapRecodtypes rec = new TW1_Ancar_wrapRecodtypes();
    
    @isTest
    public static void getUIThemeDescription() {
        String theme = TW1_Ancar_Venda_CotacaoMidia_LP_ctrl.getUIThemeDescription();
        System.debug('tema '+theme);
        System.assertEquals('Theme3', theme);
    } 
    
    @isTest static void getCotacaoClone() {
        
        Opportunity opportunity = TW1_Ancar_OpportunityMockGenerator_cls.getMidiaMock();
        
        Quote quote = TW1_Ancar_CotacaoMockGenerator_cls.getMidiaMock(opportunity.Id);   
        
        TW1_Propriedade__c propriedade = TW1_Ancar_PropriedadeMockGenerator_cls.getMidiaMock(quote.Id);
        TW1_Propriedade__c propriedade2 = TW1_Ancar_PropriedadeMockGenerator_cls.getMidiaMock(quote.Id);
        
        List<TW1_Propriedade_da_Cotacao__c> listPropriedades = 
            [SELECT TW1_Propriedade__c, TW1_Cotacao__c, TW1_Data_de_inicio__c, TW1_Data_de_fim__c, TW1_Localizacao__c, TW1_Valor__c, TW1_Area__c
            FROM TW1_Propriedade_da_Cotacao__c
            WHERE TW1_Propriedade__c =:propriedade.Id OR TW1_Propriedade__c =:propriedade2.Id ];
        
        System.debug(listPropriedades);
        
        CotacaoRequestDto requestMock = MapCotacaoPropriedadeClone(quote, listPropriedades);
        
        //Expected
        string jsonData = JSON.serialize((Object)requestMock);
        
        //Actual
        String listJson = TW1_Ancar_Venda_CotacaoMidia_LP_ctrl.GetCotacaoClone(quote.Id);
        
        System.assertEquals(jsonData, listJson);
    }
    
    @isTest
    public static void getCurrentDate() {
        Date dt = TW1_Ancar_Venda_CotacaoMall_LP_ctrl.GetCurrentDate();
        System.assertEquals(Date.today(), dt);
    }
    
    @isTest
    public static void getListSubTipoDePropriedade() {
        
        List<String> subtiposMok = new list<String>();
        subtiposMok.add('Adesivo Piso');
        subtiposMok.add('Adesivos de Mesa');
        subtiposMok.add('Adoção de Espaço');
        subtiposMok.add('Adoção Fraldário');
        subtiposMok.add('Banner');
        subtiposMok.add('Cancela Estacionamento');
        subtiposMok.add('Colunas Mall');
        subtiposMok.add('Colunas Praça de Alimentação');
        subtiposMok.add('Display Mall');
        subtiposMok.add('Display Mesa');
        subtiposMok.add('Escada Rolante');
        subtiposMok.add('Espelho de Banheiro');
        subtiposMok.add('Feiras e Eventos');
        subtiposMok.add('Mega Banner');
        subtiposMok.add('Mock up');
        subtiposMok.add('Painel');
        subtiposMok.add('Painel Backlight');
        subtiposMok.add('Painel Fachada');
        subtiposMok.add('Painel Frontlight');
        subtiposMok.add('Panfletagem');
        subtiposMok.add('Placas aéreas');
        subtiposMok.add('Porta de Banheiro');
        subtiposMok.add('Portas de Acesso');
        subtiposMok.add('Portas de Elevador');
        subtiposMok.add('Stand Temporário');
        subtiposMok.add('Testeira');
        subtiposMok.add('Totem Digital');
        subtiposMok.add('Totem Interno');
        subtiposMok.add('Voicer de cancela');

        List<String> response = TW1_Ancar_Venda_CotacaoMidia_LP_ctrl.getListSubTipoDePropriedade();
        
        System.assertEquals(subtiposMok, response);
    }
    
    @isTest
    public static void PesquisaPropriedade(){

        Opportunity opportunity = TW1_Ancar_OpportunityMockGenerator_cls.getMidiaMock();
        Quote quote = TW1_Ancar_CotacaoMockGenerator_cls.getMidiaMock(opportunity.Id);   
        TW1_Propriedade__c propriedade = TW1_Ancar_PropriedadeMockGenerator_cls.getMidiaMock(quote.Id);
        
        TW1_Calendario_de_propriedades__c calendar = new TW1_Calendario_de_propriedades__c(
            TW1_Data_de_inicio__c = Date.newInstance(2018, 10, 18),
            TW1_Data_de_fim__c = Date.newInstance(2018, 10, 19),
            TW1_Status__c ='Reservada',
            TW1_Propriedade__c = propriedade.Id
        );
        insert calendar;
        
        PesquisaRequestDto request = new PesquisaRequestDto();
        request.SubTipo = propriedade.TW1_Subtipo__c;
        request.DataInicio = calendar.TW1_Data_de_inicio__c;
        request.DataFim = calendar.TW1_Data_de_fim__c;
      	
        string requestMock = JSON.serialize(request);
        
        String jsonPropriedade = TW1_Ancar_Venda_CotacaoMidia_LP_ctrl.PesquisaPropriedade(opportunity.Id,requestMock);
		
         List<List<SObject>> ListRetornoPropriedade = ListarPorpriedadeMidiaFeira(opportunity.TW1_Shopping__c, request.SubTipo, request.DataInicio, request.DataFim);
        System.debug(ListRetornoPropriedade);
        
		List<RetornoPesquisaPropriedadeMidiaDto> RetornoMap = MapRetornoPropriedadeMidia(ListRetornoPropriedade);
        System.debug('RetornoMap: ' + RetornoMap);
        
        //Expected
        String listJson = JSON.serialize((List<Object>)RetornoMap);
        System.debug('listJson: ' + listJson);
        
        System.assertEquals(listJson, jsonPropriedade);        

    }
    
    @isTest
    public static void postSalvarCotacao() {
        
        Opportunity opportunity = TW1_Ancar_OpportunityMockGenerator_cls.getMidiaMock();
        
        Quote quote = TW1_Ancar_CotacaoMockGenerator_cls.getMidiaMock(opportunity.Id);   
        
        TW1_Propriedade__c propriedade = TW1_Ancar_PropriedadeMockGenerator_cls.getMidiaMock(quote.Id);
        TW1_Propriedade__c propriedade2 = TW1_Ancar_PropriedadeMockGenerator_cls.getMidiaMock(quote.Id);
        
        List<TW1_Propriedade_da_Cotacao__c> listPropriedades = 
            [SELECT TW1_Propriedade__c, TW1_Cotacao__c, TW1_Data_de_inicio__c, TW1_Data_de_fim__c, TW1_Localizacao__c, TW1_Valor__c, TW1_Area__c
            FROM TW1_Propriedade_da_Cotacao__c
            WHERE TW1_Propriedade__c =:propriedade.Id OR TW1_Propriedade__c =:propriedade2.Id ];
        
        System.debug(listPropriedades);
        
        CotacaoRequestDto requestMock = MapCotacaoPropriedadeClone(quote, listPropriedades);
        
        string jsonRequest = JSON.serialize((Object)requestMock);
        
        //Actual
        String response = TW1_Ancar_Venda_CotacaoMidia_LP_ctrl.PostSalvarCotacao(opportunity.Id, jsonRequest);
        
        //Expected
        String responseMock = SalvarCotacaoMidia(opportunity.Id, requestMock);
        
        System.assertEquals('Sucesso', response);
    }
    
    public static List<List<SObject>> ListarPorpriedadeMidiaFeira(Id idShopping, String paPropriedadeSubtipo, Date paDtini, Date paDtfim)
    {
			string IdShoppingsub = idShopping;
        	IdShoppingsub = IdShoppingsub.substring(0,15);
        
        try{
            
            List<TW1_Propriedade__c> vaPropriedade = [
                select 
                Id,
                Name,
                TW1_Shopping__c,
                TW1_Subtipo__c,
                TW1_Piso__c,
                TW1_area_m2__c, 
                TW1_Observacao__c,
                TW1_Status__c,
                TW1_Ativa__c,
                TW1_Status_da_prospecao__c,
                TW1_AMM__c,
                TW1_Fundo__c,
                TW1_OTN__c,
                TW1_Condominio__c,
                TW1_Nota_de_d_bito_ou_CTO__c,
                TW1_Res_Perata__c,
                TW1_IPTU__c,
                TW1_Valor_TR__c,
                TW1_Valor_de_tabela__c,
                TW1_Localizacao__c
                from 
                TW1_Propriedade__c
                where
                TW1_Ativa__c = true and
                TW1_Subtipo__c=:paPropriedadeSubtipo and
                TW1_Shopping__c=:idShopping and
                Id NOT IN
                (Select TW1_Propriedade__c from TW1_Calendario_de_propriedades__c 
                 where TW1_ShoppingId__c=:IdShoppingsub and 
                 TW1_Data_de_inicio__c <=:paDtfim and
                 TW1_Data_de_fim__c >=:paDtini and 
                 TW1_Status__c ='Ocupada'
                )
            ];	
            
            List<List<SObject>> listObjetosPropriedade = new List<List<SObject>>();
                  
            listObjetosPropriedade.add(vaPropriedade);            
            
            if(listObjetosPropriedade.size() >= 1){
                return listObjetosPropriedade;
            }else{
                return null;
            }
            
        }catch(Exception ex){
            return null;
        }
    }
    
    public static List<RetornoPesquisaPropriedadeMidiaDto> MapRetornoPropriedadeMidia (List<List<SObject>> ListRetornoPropriedade)
    {
        List<RetornoPesquisaPropriedadeMidiaDto> ListMapRetornoPropriedade = new List<RetornoPesquisaPropriedadeMidiaDto>();
        
        List<TW1_Propriedade__c> ListPropriedade =  (List<TW1_Propriedade__c>)ListRetornoPropriedade.get(0);
               
        for(TW1_Propriedade__c item : ListPropriedade)
        {
            RetornoPesquisaPropriedadeMidiaDto dtoMap = new RetornoPesquisaPropriedadeMidiaDto(); 
            
            dtoMap.Id = item.Id;
            dtoMap.Name = item.Name;
            dtoMap.Status = item.TW1_Status__c == null? 'Vaga':item.TW1_Status__c;
            dtoMap.Valor_de_tabela  = item.TW1_Valor_de_tabela__c;   
            dtoMap.Localizacao = item.TW1_Localizacao__c;
            
            ListMapRetornoPropriedade.add(dtoMap);
        }
                
        System.debug('MAP ---Fim---'+ListRetornoPropriedade);
        return ListMapRetornoPropriedade;
    }
    
    private static CotacaoRequestDto MapCotacaoPropriedadeClone(quote cotacao,List<TW1_Propriedade_da_Cotacao__c> listPropriedades)
    {
        CotacaoRequestDto cotacaoDto = new CotacaoRequestDto();
        
        cotacaoDto.OpportunityId = cotacao.OpportunityId == null ? '':cotacao.OpportunityId;
        cotacaoDto.Atividade= cotacao.TW1_Atividade__c == null ? '':cotacao.TW1_Atividade__c;
        cotacaoDto.DataPagamento = cotacao.TW1_Data_de_pagamento__c;
        cotacaoDto.SegundaDataPagamento = cotacao.TW1_Segunda_data_de_pagamento__c;
        cotacaoDto.Observacao = cotacao.Description == null ? '':cotacao.Description;
        cotacaoDto.ValorDesconto = cotacao.TW1_Valor_Desconto__c ;
        
        cotacaoDto.RecordTypeId = cotacao.RecordTypeId == null ? '':cotacao.RecordTypeId;
        cotacaoDto.ListaDePropriedade = new List<PropriedadeDto>();
        
        for(TW1_Propriedade_da_Cotacao__c propriedade : listPropriedades)
        {
            PropriedadeDto propriedadeCotacaoDto = new PropriedadeDto();
            
            propriedadeCotacaoDto.IdPropriedade = propriedade.TW1_Propriedade__c == null ? '':propriedade.TW1_Propriedade__c;
            propriedadeCotacaoDto.DataInicio = propriedade.TW1_Data_de_inicio__c;
            propriedadeCotacaoDto.DataFim = propriedade.TW1_Data_de_fim__c;
            propriedadeCotacaoDto.Localizacao = propriedade.TW1_Localizacao__c == null ? '':propriedade.TW1_Localizacao__c;
            propriedadeCotacaoDto.ValorAluguel = propriedade.TW1_Valor__c == null ? 0.0:propriedade.TW1_Valor__c;
            propriedadeCotacaoDto.AreaUtilizada = propriedade.TW1_Area__c;
            cotacaoDto.ListaDePropriedade.add(propriedadeCotacaoDto);
        }
        
        return cotacaoDto;
    }
    
    private static String SalvarCotacaoMidia(String opportunityId, CotacaoRequestDto request)
    {        
        try{
            List<RecordType> record = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Cotcao_midia];
            
            Quote cotacao = new Quote();
            cotacao.OpportunityId = opportunityId;
            cotacao.TW1_Atividade__c= request.Atividade;
            cotacao.TW1_Data_de_pagamento__c= request.DataPagamento;
            cotacao.TW1_Segunda_data_de_pagamento__c= request.SegundaDataPagamento;cotacao.Description = request.Observacao;
            cotacao.RecordTypeId = record[0].Id;
            cotacao.Name = rec.rec_Cotcao_midia + ' - ' + Date.today().day() + '/' + Date.today().month() + '/' + Date.today().year();
            cotacao.TW1_Valor_Desconto__c = request.ValorDesconto;
            
            Insert cotacao;
            
            /// Montando lista de propriedades de cotação
            list<TW1_Propriedade_da_Cotacao__c> listaPropriedadesCotacao = new List<TW1_Propriedade_da_Cotacao__c>();
            
            
            for(PropriedadeDto propriedade : request.ListaDePropriedade)
            {
                TW1_Propriedade_da_Cotacao__c propriedadeCotacao = new TW1_Propriedade_da_Cotacao__c();
                propriedadeCotacao.TW1_Cotacao__c = cotacao.id;
                propriedadeCotacao.TW1_Propriedade__c = propriedade.IdPropriedade;
                propriedadeCotacao.TW1_Data_de_inicio__c = propriedade.DataInicio;
                propriedadeCotacao.TW1_Data_de_fim__c = propriedade.DataFim;
                propriedadeCotacao.TW1_Localizacao__c = propriedade.Localizacao;
                propriedadeCotacao.TW1_Valor__c = propriedade.ValorAluguel;
                propriedadeCotacao.TW1_Area__c = propriedade.AreaUtilizada;
                listaPropriedadesCotacao.add(propriedadeCotacao);
            }
            
            system.debug('Final ');
            
            Insert listaPropriedadesCotacao;
            
            /// Executa calculo da cotação
            system.debug('Executando cálculo da cotação: ' + cotacao);
            TW1_Ancar_CalcCotacao_MidiaApp calculadoraMidiaApp = new TW1_Ancar_CalcCotacao_MidiaApp(cotacao, listaPropriedadesCotacao);
            cotacao = calculadoraMidiaApp.RealizarCalculo();
            system.debug('Cálculo mídia realizado com sucesso: ' + cotacao);
            
            update cotacao;
            
            return 'Success';
        }
        catch(Exception ex){
            System.debug('erro em salvar cotação de mídia:'+ex.getMessage());
            return 'Fail';
        }
    }
    
    public class CotacaoRequestDto
    {
        public Date DataPagamento {get;set;}
        public Date SegundaDataPagamento {get;set;}
        public string  Atividade {get;set;}
        public string  Observacao {get;set;}
        public string OpportunityId {get;set;}
        public string RecordTypeId {get;set;}
        public Decimal ValorDesconto {get;set;}
        public List<PropriedadeDto> ListaDePropriedade{get;set;}
    }
    
    public class PropriedadeDto
    {	
        public string IdPropriedade {get;set;}
        public Date DataInicio {get;set;}
        public Date DataFim {get;set;}
        public string Localizacao {get;set;}
        public Decimal ValorAluguel {get;set;}
        public decimal AreaUtilizada {get;set;}
    }
    
    public class PesquisaRequestDto
    {   
        public string SubTipo {get;set;}
        public Date DataInicio {get;set;}
        public Date DataFim {get;set;}
    }
    
    public with sharing class RetornoPesquisaPropriedadeMidiaDto
    {
        public string Id {get;set;}
        public string Name {get;set;}
        public string Status {get;set;}
        public string Localizacao {get;set;}
        public decimal Valor_de_tabela {get;set;}
        public decimal AreaUtilizada {get;set;}
    }
}