objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Prazo__c</fullName>
        <label>Prazo (dias)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM_10__c</fullName>
        <label>AMM 10</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_1__c</fullName>
        <label>AMM 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_2__c</fullName>
        <label>AMM 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_3__c</fullName>
        <label>AMM 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_4__c</fullName>
        <label>AMM 4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_5__c</fullName>
        <label>AMM 5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_6__c</fullName>
        <label>AMM 6</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_7__c</fullName>
        <label>AMM 7</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_8__c</fullName>
        <label>AMM 8</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_9__c</fullName>
        <label>AMM 9</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Aluguel_Percentual__c</fullName>
        <label>Aluguel %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TW1_CDU__c</fullName>
        <label>CDU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Carencia__c</fullName>
        <label>Carência</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condomínio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_FPP__c</fullName>
        <label>FPP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Forma_de_pagamento_da_CDU__c</fullName>
        <label>Forma de pagamento da CDU</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Forma_pagamento_pacote_de_midia__c</fullName>
        <label>Forma de pagamento pacote de mídia</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Mes_aluguel_dobrado__c</fullName>
        <label>Mês de aluguel dobrado</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Janeiro</fullName>
                </value>
                <value>
                    <fullName>Fevereiro</fullName>
                </value>
                <value>
                    <fullName>Março</fullName>
                </value>
                <value>
                    <fullName>Abril</fullName>
                </value>
                <value>
                    <fullName>Maio</fullName>
                </value>
                <value>
                    <fullName>Junho</fullName>
                </value>
                <value>
                    <fullName>Julho</fullName>
                </value>
                <value>
                    <fullName>Agosto</fullName>
                </value>
                <value>
                    <fullName>Setembro</fullName>
                </value>
                <value>
                    <fullName>Outubro</fullName>
                </value>
                <value>
                    <fullName>Novembro</fullName>
                </value>
                <value>
                    <fullName>Dezembro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Prazo__c</fullName>
        <label>Prazo (dias)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Taxa_de_transferencia__c</fullName>
        <label>Taxa de transferência</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_pacote_de_midia__c</fullName>
        <label>Valor de pacote de mídia</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condominio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_area_m2__c</fullName>
        <label>Área (m²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade_da_Cotacao__c.object
<CustomObject>
    <description>Objeto de junção entre propriedade e cotação</description>
    <fields>
        <fullName>TW1_Area__c</fullName>
        <label>Área</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Cotacao__c</fullName>
        <label>Cotação</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_fim__c</fullName>
        <label>Data de fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_inicio__c</fullName>
        <label>Data de início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Propriedade da Cotação</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propriedades da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_CotacaoLojaApplication.cls
public class TW1_Ancar_Venda_CotacaoLojaApplication {
    public TW1_Ancar_wrapRecodtypes rec = new TW1_Ancar_wrapRecodtypes();
    
    /// Repositório de oportunidade
    public TW1_Ancar_Venda_Oportunidade_Rep oportunidadeRepository = new TW1_Ancar_Venda_Oportunidade_Rep();
    
    /// Repositório de propriedade
    public TW1_Ancar_Venda_Propriedade_Rep propriedadeRepository = new TW1_Ancar_Venda_Propriedade_Rep();
    
    /// Repositório de cotação
    public TW1_Ancar_Venda_Cotacao_Rep cotacaoRepository = new TW1_Ancar_Venda_Cotacao_Rep();
    
    /// Application de cálculo de cotação
    public TW1_Ancar_Venda_CalculosCotaApplication calculoApplication = new TW1_Ancar_Venda_CalculosCotaApplication();
    
    public RecordType getRecordtype(String vaNomeDoRecodtype){
        return [SELECT Id,Name FROM RecordType WHERE Name=:vaNomeDoRecodtype limit 1];
    }
    
    public TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.CotacaoDto GetCotacaoCloneLoja(string vaCotacaoId){
        
        quote cotacao = cotacaoRepository.GetCotacaoById(vaCotacaoId);
        System.debug('Quote:' + cotacao);
        TW1_Propriedade__c Propriedade = propriedadeRepository.GetPropriedadeCotacaoLoja(vaCotacaoId);
        System.debug('Propriedade:' + Propriedade);
        TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.CotacaoDto cotacaoDto = MapCotacaoPropriedadeClone(cotacao,Propriedade);
        System.debug('cotacaoDto:' + cotacaoDto);
        
        return cotacaoDto; 
    }
    
    public TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.CotacaoDto MapCotacaoPropriedadeClone(quote cotacao,TW1_Propriedade__c Propriedade)
    {
        TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.CotacaoDto cotacaoDto = new TW1_Ancar_Venda_CotacaoLoja_LP_ctrl.CotacaoDto();
        
        cotacaoDto.OpportunityId = cotacao.OpportunityId;
        cotacaoDto.ValorFPP = cotacao.TW1_FPP__c;
        cotacaoDto.Amm1 = cotacao.TW1_AMM_1__c;
        cotacaoDto.Amm2 = cotacao.TW1_AMM_2__c;
        cotacaoDto.Amm3 = cotacao.TW1_AMM_3__c;
        cotacaoDto.Amm4 = cotacao.TW1_AMM_4__c;
        cotacaoDto.Amm5 = cotacao.TW1_AMM_5__c;
        cotacaoDto.Amm6 = cotacao.TW1_AMM_6__c;
        cotacaoDto.Amm7 = cotacao.TW1_AMM_7__c;
        cotacaoDto.Amm8 = cotacao.TW1_AMM_8__c;
        cotacaoDto.Amm9 = cotacao.TW1_AMM_9__c;
        cotacaoDto.Amm10 = cotacao.TW1_AMM_10__c;
        cotacaoDto.Periodo = cotacao.TW1_Prazo__c;
        cotacaoDto.ValorMidia  = cotacao.TW1_Valor_pacote_de_midia__c;
        cotacaoDto.FormaPagamentoMidia = cotacao.TW1_Forma_pagamento_pacote_de_midia__c;
        cotacaoDto.ValorCondominio = cotacao.TW1_Condominio__c;
        cotacaoDto.AluguelPercentual  = cotacao.TW1_Aluguel_Percentual__c;
        cotacaoDto.ValorCDU = cotacao.TW1_CDU__c;
        cotacaoDto.FormaPagamentoCDU = cotacao.TW1_Forma_de_pagamento_da_CDU__c;
        cotacaoDto.Carencia = cotacao.TW1_Carencia__c;
        cotacaoDto.MesAluguelDobrado = cotacao.TW1_Mes_aluguel_dobrado__c;
        cotacaoDto.Observavao = cotacao.Description;
        cotacaoDto.DataInicio = cotacao.TW1_Data_inicio_de_vigencia__c;
        cotacaoDto.DataFim = cotacao.TW1_Data_fim_de_vigencia__c;
        cotacaoDto.TaxaTransferencia = cotacao.TW1_Taxa_de_transferencia__c;
        cotacaoDto.Propriedade = Propriedade;
        return cotacaoDto;
    }
    
    public List<SObject> getListaPropriedadesDisponiveis(string opportunityId)
    {
        Opportunity opportunity = oportunidadeRepository.GetOpportunityById(opportunityId);
        return propriedadeRepository.ListarPropriedadeLoja(opportunity.TW1_Shopping__c);
    }
    
    public void SalvarCotacao(Quote cotacao, TW1_Propriedade__c Propriedade)
    {
        System.debug('cotacao: ' + cotacao);
        Savepoint sp = Database.setSavepoint();
        
        try{
            String vaRecordType ='';
            
            cotacao.RecordTypeId = this.getRecordtype(rec.rec_Cotcao_loja).id;
            cotacao.Name = Propriedade.Name + ' - ' + Date.today().day() + '/' + Date.today().month() + '/' + Date.today().year();
            
            system.debug('Inserindo cotação');
            Insert cotacao;
            system.debug('Cotação inserida ');
            
            ///Montando lista de propriedades de cotação
            list<TW1_Propriedade_da_Cotacao__c> propCotacao = new List<TW1_Propriedade_da_Cotacao__c>();
            
            TW1_Propriedade_da_Cotacao__c vaPropriedadeCotacao = new TW1_Propriedade_da_Cotacao__c();
            vaPropriedadeCotacao.TW1_Cotacao__c = cotacao.id;
            vaPropriedadeCotacao.TW1_Propriedade__c = Propriedade.Id;
            vaPropriedadeCotacao.TW1_Data_de_inicio__c = cotacao.TW1_Data_inicio_de_vigencia__c;
            
            integer periodo = integer.valueOf(cotacao.TW1_Prazo__c);
            vaPropriedadeCotacao.TW1_Data_de_fim__c = cotacao.TW1_Data_inicio_de_vigencia__c.addMonths(periodo);
            System.debug('5: ' + cotacao.TW1_Data_inicio_de_vigencia__c.addMonths(periodo));
            
            vaPropriedadeCotacao.TW1_Area__c = Propriedade.TW1_area_m2__c;
            propCotacao.add(vaPropriedadeCotacao);
            
            system.debug('Inserindo propriedade');
            Insert propCotacao;
            system.debug('Propriedade inserida');
            
            //Executa calculo da cotação
            system.debug('Executando cálculo da cotação: ' + cotacao);
            cotacao = calculoApplication.CalcularCotacaco(cotacao, propCotacao);
            system.debug('Cálculos executados: ' + cotacao);
            
            update cotacao;
        }
        catch(Exception ex){
            System.debug('erro de cotação:'+ex.getMessage());
            Database.rollback(sp);
            throw ex;
        }
    }
}