objects/Quote.object
<CustomObject>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Periodo_de_locacao__c</fullName>
        <label>Período de locação</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Indeterminado</fullName>
                </value>
                <value>
                    <fullName>Determinado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Prazo__c</fullName>
        <label>Prazo (dias)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade_da_Cotacao__c.object
<CustomObject>
    <description>Objeto de junção entre propriedade e cotação</description>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Propriedade da Cotação</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propriedades da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TW1_Ancar_CalcCotacao_MallApp.cls
public class TW1_Ancar_CalcCotacao_MallApp {
    
    Quote Cotacao;
    
    list<TW1_Propriedade_da_Cotacao__c> ListaDePropriedades;
    
    TW1_Propriedade__c PropriedadeLoja;
    
    public TW1_Ancar_CalcCotacao_MallApp(Quote pcotacao, list<TW1_Propriedade_da_Cotacao__c> listaPropriedadesCotacao)
    {
        system.debug('Criando instancia calculadora de Mall:  ' + pcotacao + ' Propriedade: ' + listaPropriedadesCotacao );
        Cotacao = pcotacao;
        ListaDePropriedades = listaPropriedadesCotacao;
    }
    
    public Quote RealizarCalculo()
    {
        system.debug('Calculando prazo');
        CalcularPrazo();
        system.debug('Prazo calculado com sucesso');
        return Cotacao;
    }
    
    
    private void CalcularPrazo()
    {
        system.debug('Calculando prazo com período de locação: ' + Cotacao.TW1_Periodo_de_locacao__c);
        if(Cotacao.TW1_Periodo_de_locacao__c == 'Indeterminado')
        {
            system.debug('Zerando prazo em caso de Indeterminado');
            Cotacao.TW1_Prazo__c = 0;
            return;
        }
        
        system.debug('Executando cálculos em dias de prazo');
        Cotacao.TW1_Prazo__c = Cotacao.TW1_Data_inicio_de_vigencia__c.daysBetween(Cotacao.TW1_Data_fim_de_vigencia__c) + 1;
        system.debug('Prazo total: ' + Cotacao.TW1_Prazo__c);
    }
}