objects/Quote.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM_10__c</fullName>
        <label>AMM 10</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_1__c</fullName>
        <label>AMM 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_2__c</fullName>
        <label>AMM 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_3__c</fullName>
        <label>AMM 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_4__c</fullName>
        <label>AMM 4</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_5__c</fullName>
        <label>AMM 5</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_6__c</fullName>
        <label>AMM 6</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_7__c</fullName>
        <label>AMM 7</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_8__c</fullName>
        <label>AMM 8</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_9__c</fullName>
        <label>AMM 9</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Acrescimo_sazonal_dezembro__c</fullName>
        <label>Acréscimo sazonal dezembro (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Acrescimo_sazonal_maio__c</fullName>
        <label>Acréscimo sazonal maio (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Acrescimo_sazonal_novembro__c</fullName>
        <label>Acréscimo sazonal novembro (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Aluguel_Percentual__c</fullName>
        <label>Aluguel %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TW1_Area_utilizada__c</fullName>
        <label>Área utilizada</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Atividade__c</fullName>
        <label>Atividade (descrição da ação)</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_CDU__c</fullName>
        <label>CDU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Carencia__c</fullName>
        <label>Carência</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condomínio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_pagamento__c</fullName>
        <label>Data de pagamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_fim_de_vigencia__c</fullName>
        <label>Data de fim de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio_de_vigencia__c</fullName>
        <label>Data de início de vigência</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_FPP__c</fullName>
        <label>FPP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Forma_de_pagamento_da_CDU__c</fullName>
        <label>Forma de pagamento da CDU</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Forma_pagamento_pacote_de_midia__c</fullName>
        <label>Forma de pagamento pacote de mídia</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Mes_aluguel_dobrado__c</fullName>
        <label>Mês de aluguel dobrado</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Janeiro</fullName>
                </value>
                <value>
                    <fullName>Fevereiro</fullName>
                </value>
                <value>
                    <fullName>Março</fullName>
                </value>
                <value>
                    <fullName>Abril</fullName>
                </value>
                <value>
                    <fullName>Maio</fullName>
                </value>
                <value>
                    <fullName>Junho</fullName>
                </value>
                <value>
                    <fullName>Julho</fullName>
                </value>
                <value>
                    <fullName>Agosto</fullName>
                </value>
                <value>
                    <fullName>Setembro</fullName>
                </value>
                <value>
                    <fullName>Outubro</fullName>
                </value>
                <value>
                    <fullName>Novembro</fullName>
                </value>
                <value>
                    <fullName>Dezembro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Periodo_de_locacao__c</fullName>
        <label>Período de locação</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Indeterminado</fullName>
                </value>
                <value>
                    <fullName>Determinado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Prazo__c</fullName>
        <label>Prazo (dias)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_QuoteRecordTypeName__c</fullName>
        <formula>RecordType.Name</formula>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Segunda_data_de_pagamento__c</fullName>
        <label>Segunda data de pagamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Sincronizada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sincronizada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Taxa_de_transferencia__c</fullName>
        <label>Taxa de transferência</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_VGL_AMM__c</fullName>
        <label>VGL AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_VGL_total__c</fullName>
        <label>VGL total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_Desconto__c</fullName>
        <label>Valor Desconto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_pacote_de_midia__c</fullName>
        <label>Valor de pacote de mídia</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TW1_Ancar_CotacaoMockGenerator_cls.cls
public class TW1_Ancar_CotacaoMockGenerator_cls {

    public static TW1_Ancar_wrapRecodtypes rec = new TW1_Ancar_wrapRecodtypes();
    
    public static Quote getFeiraoMock(String opportunityId)
    {
    	List<RecordType> recordFeirao = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Cotcao_feiras];
        
        Quote quoteMock = new Quote(
            Name = 'ApexTest QuoteName', 
            RecordTypeId = recordFeirao[0].Id, 
            TW1_Sincronizada__c = false,    
            TW1_Data_inicio_de_vigencia__c = Date.today(),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(10),    
            TW1_Prazo__c = 132,      
            TW1_Valor__c = 1,    
            TW1_AMM__c = 10, 
            TW1_AMM_1__c = 10, 
            TW1_AMM_2__c = 10, 
            TW1_AMM_3__c = 10, 
            TW1_AMM_4__c = 10, 
            TW1_AMM_5__c = 10,
            TW1_AMM_6__c = 10, 
            TW1_AMM_7__c = 10, 
            TW1_AMM_8__c = 10, 
            TW1_AMM_9__c = 10, 
            TW1_AMM_10__c = 10,
            OpportunityId = opportunityId
        );
        insert quoteMock;
        
        Quote quote = 
            [SELECT id, TW1_FPP__c, TW1_AMM__c, TW1_AMM_1__c, TW1_AMM_2__c, TW1_AMM_3__c, TW1_AMM_4__c, TW1_AMM_5__c, TW1_Segunda_data_de_pagamento__c,
             TW1_AMM_6__c, TW1_AMM_7__c, TW1_AMM_8__c, TW1_AMM_9__c, TW1_AMM_10__c, TW1_VGL_AMM__c, TW1_Prazo__c, TW1_Valor__c, 
             TW1_Valor_pacote_de_midia__c, TW1_Forma_pagamento_pacote_de_midia__c, TW1_Condominio__c, TW1_Acrescimo_sazonal_maio__c, 
             TW1_Acrescimo_sazonal_novembro__c, TW1_Acrescimo_sazonal_dezembro__c, TW1_Aluguel_Percentual__c, TW1_CDU__c, TW1_Valor_Desconto__c,
             TW1_Forma_de_pagamento_da_CDU__c, TW1_Carencia__c, TW1_Mes_aluguel_dobrado__c, TW1_Data_inicio_de_vigencia__c,
             TW1_Data_fim_de_vigencia__c, TW1_Data_de_pagamento__c, TW1_Atividade__c, TW1_Periodo_de_locacao__c, Description,
             TW1_Taxa_de_transferencia__c, TW1_QuoteRecordTypeName__c, TW1_Area_utilizada__c, RecordTypeId, Name, OpportunityId
             FROM Quote WHERE Id = :quoteMock.Id];
        
        return quote;
    }
    
    public static Quote getMidiaMock(String opportunityId)
    {
    	List<RecordType> recordMidia = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Cotcao_midia];
        
        Quote quoteMock = new Quote(
            Name = 'ApexTest QuoteName',
            RecordTypeId = recordMidia[0].Id, 
            TW1_Sincronizada__c = false,
            TW1_Data_inicio_de_vigencia__c = Date.today(),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(10),
            TW1_Prazo__c = 132,
            TW1_Valor_pacote_de_midia__c = 2,
            TW1_AMM__c = 10, 
            TW1_AMM_1__c = 10, 
            TW1_AMM_2__c = 10, 
            TW1_AMM_3__c = 10, 
            TW1_AMM_4__c = 10, 
            TW1_AMM_5__c = 10,
            TW1_AMM_6__c = 10, 
            TW1_AMM_7__c = 10, 
            TW1_AMM_8__c = 10, 
            TW1_AMM_9__c = 10, 
            TW1_AMM_10__c = 10,
            TW1_VGL_AMM__c = 4000,
            TW1_VGL_total__c = 10000,
            OpportunityId = opportunityId
        );
        insert quoteMock;
        
        Quote quote = 
            [SELECT id, TW1_FPP__c, TW1_AMM__c, TW1_AMM_1__c, TW1_AMM_2__c, TW1_AMM_3__c, TW1_AMM_4__c, TW1_AMM_5__c, TW1_Valor__c,
             TW1_AMM_6__c, TW1_AMM_7__c, TW1_AMM_8__c, TW1_AMM_9__c, TW1_AMM_10__c, TW1_VGL_AMM__c, TW1_Prazo__c, TW1_VGL_total__c, 
             TW1_Valor_pacote_de_midia__c, TW1_Forma_pagamento_pacote_de_midia__c, TW1_Condominio__c, TW1_Acrescimo_sazonal_maio__c, 
             TW1_Acrescimo_sazonal_novembro__c, TW1_Acrescimo_sazonal_dezembro__c, TW1_Aluguel_Percentual__c, TW1_CDU__c, TW1_Segunda_data_de_pagamento__c,
             TW1_Forma_de_pagamento_da_CDU__c, TW1_Carencia__c, TW1_Mes_aluguel_dobrado__c, TW1_Data_inicio_de_vigencia__c,TW1_Valor_Desconto__c,
             TW1_Data_fim_de_vigencia__c, TW1_Data_de_pagamento__c, TW1_Atividade__c, TW1_Periodo_de_locacao__c, Description,
             TW1_Taxa_de_transferencia__c, TW1_QuoteRecordTypeName__c, TW1_Area_utilizada__c, RecordTypeId, Name, OpportunityId
             FROM Quote WHERE Id = :quoteMock.Id];
        
        return quote;
    }
    
    public static Quote getMallMock(String opportunityId)
    {
        List<RecordType> recordMall = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Cotcao_mall];
        
        Quote quoteMock = new Quote(
            Name = 'ApexTest QuoteName',
            RecordTypeId = recordMall[0].Id,
            TW1_Sincronizada__c = false,
            TW1_Periodo_de_locacao__c = 'Determinado',
            TW1_Data_inicio_de_vigencia__c = Date.today(),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(10),
            TW1_Prazo__c = 132,
            TW1_AMM__c = 10, 
            TW1_AMM_1__c = 10, 
            TW1_AMM_2__c = 10, 
            TW1_AMM_3__c = 10, 
            TW1_AMM_4__c = 10, 
            TW1_AMM_5__c = 10,
            TW1_AMM_6__c = 10, 
            TW1_AMM_7__c = 10, 
            TW1_AMM_8__c = 10, 
            TW1_AMM_9__c = 10, 
            TW1_AMM_10__c = 10,
            TW1_VGL_AMM__c = 4000,
            TW1_VGL_total__c = 10000,
            OpportunityId = opportunityId
        );
        insert quoteMock;
        
        Quote quote = 
            [SELECT id, TW1_FPP__c, TW1_AMM__c, TW1_AMM_1__c, TW1_AMM_2__c, TW1_AMM_3__c, TW1_AMM_4__c, TW1_AMM_5__c, TW1_Valor__c,
             TW1_AMM_6__c, TW1_AMM_7__c, TW1_AMM_8__c, TW1_AMM_9__c, TW1_AMM_10__c, TW1_VGL_AMM__c, TW1_Prazo__c, TW1_VGL_total__c,
             TW1_Valor_pacote_de_midia__c, TW1_Forma_pagamento_pacote_de_midia__c, TW1_Condominio__c, TW1_Acrescimo_sazonal_maio__c, 
             TW1_Acrescimo_sazonal_novembro__c, TW1_Acrescimo_sazonal_dezembro__c, TW1_Aluguel_Percentual__c, TW1_CDU__c, TW1_Segunda_data_de_pagamento__c,
             TW1_Forma_de_pagamento_da_CDU__c, TW1_Carencia__c, TW1_Mes_aluguel_dobrado__c, TW1_Data_inicio_de_vigencia__c,TW1_Valor_Desconto__c,
             TW1_Data_fim_de_vigencia__c, TW1_Data_de_pagamento__c, TW1_Atividade__c, TW1_Periodo_de_locacao__c, Description,
             TW1_Taxa_de_transferencia__c, TW1_QuoteRecordTypeName__c, TW1_Area_utilizada__c, RecordTypeId, Name, OpportunityId
             FROM Quote WHERE Id = :quoteMock.Id];
        
        return quote;
    }
    
    public static Quote getLojaMock(String opportunityId)
    {
    	List<RecordType> recordLoja = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Cotcao_loja]; 
        
        Quote quoteMock = new Quote(
            Name = 'ApexTest QuoteName', 
            RecordTypeId = recordLoja[0].Id, 
            TW1_Sincronizada__c = false,
            TW1_Data_inicio_de_vigencia__c = Date.today(),
            TW1_Data_fim_de_vigencia__c = Date.today().AddDays(10),
            TW1_Prazo__c = 132,
            TW1_Valor_pacote_de_midia__c = 2,
            TW1_AMM__c = 10, 
            TW1_AMM_1__c = 10, 
            TW1_AMM_2__c = 10, 
            TW1_AMM_3__c = 10, 
            TW1_AMM_4__c = 10, 
            TW1_AMM_5__c = 10,
            TW1_AMM_6__c = 10, 
            TW1_AMM_7__c = 10, 
            TW1_AMM_8__c = 10, 
            TW1_AMM_9__c = 10, 
            TW1_AMM_10__c = 10,
            TW1_VGL_AMM__c = 400,
            TW1_VGL_total__c = 100000,
            TW1_Condominio__c = 1234567812345678.22,
      		TW1_FPP__c = 1234567812345678.22,
      		TW1_CDU__c = 1234567812345678.22,
      		TW1_Forma_de_pagamento_da_CDU__c = 'Long Text Area(500)',
            TW1_Aluguel_Percentual__c = 1234567812345678.22,
            TW1_Carencia__c = 'Text Area(255)',
            TW1_IPTU__c =1234567812345678.22,
            TW1_Valor_TR__c = 1234567812345678.22,
            TW1_Mes_aluguel_dobrado__c = 'Janeiro',
            TW1_Forma_pagamento_pacote_de_midia__c = 'Long Text Area(500)',
      		Description = 'Long Text Area(32000)',
            TW1_Acrescimo_sazonal_dezembro__c = 1234567891,
      		TW1_Acrescimo_sazonal_maio__c = 1234567891,
      		TW1_Acrescimo_sazonal_novembro__c = 1234567891,
      		TW1_Periodo_de_locacao__c = 'Indeterminado',
            TW1_Area_utilizada__c = 1234567812345678.22,
      		TW1_Atividade__c = 'Long Text Area(500)',
            TW1_Data_de_pagamento__c = Date.today(),
      		TW1_Valor__c = 1234567812345678.22,
            OpportunityId = opportunityId
        );
        insert quoteMock;
        
        Quote quote = 
            [SELECT id, TW1_FPP__c, TW1_AMM__c, TW1_AMM_1__c, TW1_AMM_2__c, TW1_AMM_3__c, TW1_AMM_4__c, TW1_AMM_5__c, TW1_Valor__c,
             TW1_AMM_6__c, TW1_AMM_7__c, TW1_AMM_8__c, TW1_AMM_9__c, TW1_AMM_10__c, TW1_VGL_AMM__c, TW1_Prazo__c, TW1_VGL_total__c, 
             TW1_Valor_pacote_de_midia__c, TW1_Forma_pagamento_pacote_de_midia__c, TW1_Condominio__c, TW1_Acrescimo_sazonal_maio__c, 
             TW1_Acrescimo_sazonal_novembro__c, TW1_Acrescimo_sazonal_dezembro__c, TW1_Aluguel_Percentual__c, TW1_CDU__c, TW1_Segunda_data_de_pagamento__c,
             TW1_Forma_de_pagamento_da_CDU__c, TW1_Carencia__c, TW1_Mes_aluguel_dobrado__c, TW1_Data_inicio_de_vigencia__c,TW1_Valor_Desconto__c,
             TW1_Data_fim_de_vigencia__c, TW1_Data_de_pagamento__c, TW1_Atividade__c, TW1_Periodo_de_locacao__c, Description,
             TW1_Taxa_de_transferencia__c, TW1_QuoteRecordTypeName__c, TW1_Area_utilizada__c, RecordTypeId, Name, OpportunityId
             FROM Quote WHERE Id = :quoteMock.Id];
        
        return quote;
    }
}