objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM_M2__c</fullName>
        <formula>IF(OR(TW1_AMM__c = 0,TW1_area_m2__c=0),0,TW1_AMM__c/TW1_area_m2__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AMM/M²</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM_OTN__c</fullName>
        <formula>IF(OR(TW1_AMM__c=0,TW1_OTN__c=0),0,TW1_AMM__c/TW1_OTN__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AMM/OTN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condominio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Fundo__c</fullName>
        <label>Fundo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Nota_de_d_bito_ou_CTO__c</fullName>
        <label>Nota de débito ou CTO</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_OTN__c</fullName>
        <label>OTN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Observacao__c</fullName>
        <label>Observação</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Piso__c</fullName>
        <label>Piso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1º andar</fullName>
                </value>
                <value>
                    <fullName>Subsolo</fullName>
                </value>
                <value>
                    <fullName>2º andar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_RES_m2__c</fullName>
        <formula>IF(OR(TW1_Res_Perata__c=0,TW1_area_m2__c=0),0,TW1_Res_Perata__c/TW1_area_m2__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RES/m²</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Res_Perata__c</fullName>
        <label>Res Perata</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato assinado</fullName>
                </value>
                <value>
                    <fullName>Repasse</fullName>
                </value>
                <value>
                    <fullName>Vaga</fullName>
                </value>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Status_da_prospecao__c</fullName>
        <label>Prospecção/Proposta aprovada</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_area_m2__c</fullName>
        <label>Área (m²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_TabelaComercialController.cls
public with sharing class TW1_Ancar_TabelaComercialController {
    
    
    public boolean displayPesquisa {get;set;}
    public String valorPesquisaShopping {get;set;}
    public List<TW1_Shopping__c> listshoppings{get;set;}
    public string IdObjetoDisplay{get;set;}
    public String nomeDoshopping{get;set;}
    public List<TW1_Propriedade__c> listlucs{get;set;}
    public boolean displayTabela {get;set;}
    
    
    public TW1_Ancar_TabelaComercialController(){
        displayPesquisa = true;
        valorPesquisaShopping = '';
        getListaShoppings();
    }
    
    public void TelaInicio()
    {
        listlucs = new List<TW1_Propriedade__c>();
        displayTabela = false;
        IdObjetoDisplay ='';
        valorPesquisaShopping = '';
        displayPesquisa = true;
    }
    
    public void getLucsByShopping(){
        displayTabela = true;
        displayPesquisa = false;
        String idShopping = IdObjetoDisplay;
        
        listlucs = new List<TW1_Propriedade__c>();
        
        for(TW1_Propriedade__c luc : [
            SELECT
            Name,
            TW1_Piso__c,
            TW1_Status_da_prospecao__c,
            TW1_Status__c,
            TW1_area_m2__c,
            TW1_AMM__c,
            TW1_AMM_M2__c,
            TW1_Fundo__c,
            TW1_OTN__c,
            TW1_AMM_OTN__c,
            TW1_Valor_TR__c,
            TW1_Condominio__c,
            TW1_Nota_de_d_bito_ou_CTO__c,
            TW1_RES_m2__c,
            TW1_Res_Perata__c,
            TW1_IPTU__c,
            TW1_Observacao__c
            FROM TW1_Propriedade__c
            WHERE TW1_Shopping__c = :idShopping And
            RecordType.Name = 'Propriedade de loja'
            AND (TW1_Status__c = 'Vaga' OR TW1_Status__c = 'Repasse')
        ])
        {
            luc.TW1_IPTU__c = (luc.TW1_IPTU__c == null ? 0:luc.TW1_IPTU__c);
            luc.TW1_AMM__c = (luc.TW1_AMM__c == null ? 0:luc.TW1_AMM__c);
            luc.TW1_Condominio__c = (luc.TW1_Condominio__c == null ? 0:luc.TW1_Condominio__c);
            luc.TW1_Fundo__c = (luc.TW1_Fundo__c == null ? 0:luc.TW1_Fundo__c);
            luc.TW1_Nota_de_d_bito_ou_CTO__c = (luc.TW1_Nota_de_d_bito_ou_CTO__c == null ? 0:luc.TW1_Nota_de_d_bito_ou_CTO__c);
            luc.TW1_OTN__c = (luc.TW1_OTN__c == null ? 0:luc.TW1_OTN__c);
            luc.TW1_Valor_TR__c = (luc.TW1_Valor_TR__c == null ? 0:luc.TW1_Valor_TR__c);
            luc.TW1_Res_Perata__c = (luc.TW1_Res_Perata__c == null ? 0:luc.TW1_Res_Perata__c);

            listlucs.add(luc);
        }
    }
    
    public void getListaShoppings(){
        String strShopping = valorPesquisaShopping;
        
        List<TW1_Shopping__c> listaShoppings = new List<TW1_Shopping__c>();
        
        if(strShopping.length() <= 1){
            String strShoppingLike = '%' + strShopping + '%';
            listaShoppings = [SELECT Id, Name FROM TW1_Shopping__c WHERE Name LIKE :strShoppingLike];
        }else{
            List<List<SObject>> searchResult = [FIND :strShopping IN Name Fields RETURNING TW1_Shopping__c(Id, Name)];
            listaShoppings = searchResult[0];
        }
        
        listshoppings = listaShoppings;
    }
}