objects/TW1_Informacoes_historicas__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM_faturado__c</fullName>
        <label>AMM faturado</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_FPP_Total_faturado__c</fullName>
        <label>FPP Total faturado</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Propriedade old</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Informação histórica da propriedade</label>
    <nameField>
        <label>Ano/Mes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações históricas da propriedade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condominio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Fundo__c</fullName>
        <label>Fundo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Localizacao__c</fullName>
        <label>Localização</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Observacao__c</fullName>
        <label>Observação</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Piso__c</fullName>
        <label>Piso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1º andar</fullName>
                </value>
                <value>
                    <fullName>Subsolo</fullName>
                </value>
                <value>
                    <fullName>2º andar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Res_Perata__c</fullName>
        <label>Res Perata</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_area_m2__c</fullName>
        <label>Área (m²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_InfHistProp_Rep.cls
public class TW1_Ancar_Venda_InfHistProp_Rep {
    public list<TW1_Propriedade__c> ListarInformacoesHistoricas(String paRecordId, list<String> paInformacaoDaPropriedade)
    {
        try{
            /*
            list<TW1_Informacoes_historicas__c> vaInformacaoDaPropriedade =[
                SELECT
                id,
                TW1_Propriedade__r.Name,
                TW1_Propriedade__r.TW1_area_m2__c,
                TW1_Propriedade__r.TW1_Piso__c,
                TW1_AMM_faturado__c,
                TW1_Propriedade__r.TW1_Condominio__c,
                TW1_FPP_Total_faturado__c,
                TW1_Propriedade__r.TW1_Res_Perata__c,
                TW1_Propriedade__r.TW1_Localizacao__c,
                TW1_Propriedade__r.TW1_IPTU__c,
                TW1_Propriedade__r.TW1_Valor_TR__c,
                TW1_Propriedade__r.TW1_Observacao__c,
                TW1_Propriedade__r.TW1_AMM__c,
                TW1_Propriedade__r.TW1_Fundo__c
                FROM
                TW1_Informacoes_historicas__c
                WHERE 
                TW1_Propriedade__C IN:paInformacaoDaPropriedade
            ];
            */
            
            list<TW1_Propriedade__c> vaInformacaoDaPropriedade =[
                SELECT
                id,
                Name,
                TW1_area_m2__c,
                TW1_Piso__c,
                //TW1_AMM_faturado__c,
                TW1_Condominio__c,
                //TW1_FPP_Total_faturado__c,
                TW1_Res_Perata__c,
                TW1_Localizacao__c,
                TW1_IPTU__c,
                TW1_Valor_TR__c,
                TW1_Observacao__c,
                TW1_AMM__c,
                TW1_Fundo__c
                FROM
                TW1_Propriedade__c
                WHERE 
                Id IN:paInformacaoDaPropriedade
            ];
            
            if(vaInformacaoDaPropriedade.size() >= 1){
                return vaInformacaoDaPropriedade;
            }else{
                return null;
            }
            
        }catch(Exception ex){
            return null;
        }
    }
}