objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato assinado</fullName>
                </value>
                <value>
                    <fullName>Repasse</fullName>
                </value>
                <value>
                    <fullName>Vaga</fullName>
                </value>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>Sigla</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_TabelaComercial_tst.cls
@isTest
public class TW1_Ancar_TabelaComercial_tst {
  @isTest
    static void TestgetLucsByShopping(){
        Test.startTest();
        	
        	recordtype rt = [Select Id,Name from recordtype where Name='Propriedade de loja'];
        
        	TW1_Shopping__c shopping = new TW1_Shopping__c(Name='Teste Shopping 2',TW1_SGL_Empreendimento__c = 'BPS');
        	insert shopping;
        
        	TW1_Propriedade__c propriedade = new TW1_Propriedade__c();
        	propriedade.Name = '1';
        	propriedade.TW1_Shopping__c = shopping.Id;
        	propriedade.RecordTypeId = rt.Id;
        	propriedade.TW1_Status__c = 'Vaga';
        	insert propriedade;
        
        	TW1_Ancar_TabelaComercialController tabelaComercial = new TW1_Ancar_TabelaComercialController();
        	tabelaComercial.displayPesquisa = true;
        	tabelaComercial.displayTabela = true;
            tabelaComercial.valorPesquisaShopping = shopping.Name;
        	tabelaComercial.IdObjetoDisplay = shopping.Id; 
        
        	tabelaComercial.getLucsByShopping();
        	tabelaComercial.TelaInicio();
        	tabelaComercial.getListaShoppings();

        Test.stopTest();
    }
      @isTest
    static void TestgetLucsByShoppingSoSL(){
        Test.startTest();
        	
        	recordtype rt = [Select Id,Name from recordtype where Name='Propriedade de loja'];
        	
        	TW1_Shopping__c shopping = new TW1_Shopping__c(Name='Teste Shopping 2',TW1_SGL_Empreendimento__c = 'BPS');
        	insert shopping;
        
        	TW1_Propriedade__c propriedade = new TW1_Propriedade__c();
        	propriedade.Name = '1';
        	propriedade.TW1_Shopping__c = shopping.Id;
        	propriedade.RecordTypeId = rt.Id;
        	propriedade.TW1_Status__c = 'Vaga';
        	insert propriedade;
        
        	TW1_Ancar_TabelaComercialController tabelaComercial = new TW1_Ancar_TabelaComercialController();
        	tabelaComercial.displayPesquisa = true;
        	tabelaComercial.displayTabela = true;
            tabelaComercial.valorPesquisaShopping = 'gcsacsacsacf';
        	tabelaComercial.IdObjetoDisplay = shopping.Id; 
        
        	tabelaComercial.getLucsByShopping();
        	tabelaComercial.TelaInicio();
        	tabelaComercial.valorPesquisaShopping = 'gfscszczsc';
        	tabelaComercial.getListaShoppings();

        Test.stopTest();
    }
    
    @isTest
    static void TestgetLucsByShopping2(){
        Test.startTest();

        	TW1_Ancar_TabelaComercialController tabelaComercial = new TW1_Ancar_TabelaComercialController();
        	tabelaComercial.displayPesquisa = false;
        	tabelaComercial.displayTabela = false;
            tabelaComercial.valorPesquisaShopping = '';
        	tabelaComercial.nomeDoshopping = '';
        	tabelaComercial.IdObjetoDisplay = ''; 
        
        	tabelaComercial.getLucsByShopping();
        	tabelaComercial.TelaInicio();
			tabelaComercial.getListaShoppings();

        Test.stopTest();
    }
    
}