objects/TW1_Informacoes_historicas__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Propriedade old</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Informação histórica da propriedade</label>
    <nameField>
        <label>Ano/Mes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações históricas da propriedade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/getLucsByLuc.cls
public class getLucsByLuc {
	@AuraEnabled
    public static List<TW1_Propriedade__c> getLucsByLuc(String strLuc, String idShopping){
        TW1_Propriedade__c luc = getLuc(strLuc, idShopping);
        
        List<TW1_Informacoes_historicas__c> listaInformacoesHistoricas = [SELECT TW1_Propriedade__c FROM TW1_Informacoes_historicas__c WHERE TW1_Propriedade__c = :luc.Id AND TW1_Shopping__c = :idShopping];
        
        List<Id> listaLucsIds = new List<Id>();
        for(TW1_Informacoes_historicas__c informacaoHistorica : listaInformacoesHistoricas){
            listaLucsIds.add(informacaoHistorica.TW1_Propriedade__c);
        }
        
        List<TW1_Propriedade__c> listaLucs = [SELECT Id, Name FROM TW1_Propriedade__c WHERE Id IN :listaLucsIds];
        
        return listaLucs;
    }
    
    @AuraEnabled
    public static TW1_Propriedade__c getLuc(String strLuc, String idShopping){
        List<TW1_Propriedade__c> listaLucsEqual = [SELECT Name FROM TW1_Propriedade__c WHERE Name = :strLuc AND TW1_Shopping__c = :idShopping];
        
        if(listaLucsEqual.size() >= 1){
            return listaLucsEqual.get(0);
        }else{
            String strLucLike = '%' + strLuc + '%';
            List<TW1_Propriedade__c> listaLucsLike = [SELECT Name FROM TW1_Propriedade__c WHERE Name LIKE :strLucLike AND TW1_Shopping__c = :idShopping];
            
            if(listaLucsLike.size() >= 1){
                List<String> listaLucsLikeStr = new List<String>();
                for(TW1_Propriedade__c lucLike : listaLucsLike){
                    listaLucsLikeStr.add(lucLike.Name);
                }
                Integer moreSimilarLucIndex = Util.getClosestString(strLuc, listaLucsLikeStr);
                
                return listaLucsLike.get(moreSimilarLucIndex);
            }else{
                List<TW1_Propriedade__c> listaLucsAll = [SELECT Name FROM TW1_Propriedade__c WHERE TW1_Shopping__c = :idShopping];
                
                List<String> listaLucsAllStr = new List<String>();
                for(TW1_Propriedade__c lucAll : listaLucsAll){
                    listaLucsAllStr.add(lucAll.Name);
                }
                
                Integer moreSimilarLucIndex = Util.getClosestString(strLuc, listaLucsAllStr);
                
                return listaLucsAll.get(moreSimilarLucIndex);
                
            }
        }
    }
}