objects/TW1_Calendario_de_propriedades__c.object
<CustomObject>
    <description>Objeto que deve registrar o calendário de locação das propriedades.</description>
    <fields>
        <fullName>TW1_Data_de_fim__c</fullName>
        <label>Data de fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_inicio__c</fullName>
        <label>Data de início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Calendário de propriedades</relationshipLabel>
        <relationshipName>Calendario_de_propriedades</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calendário de propriedade</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendário de propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Ativa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ativa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condominio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Fundo__c</fullName>
        <label>Fundo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Localizacao__c</fullName>
        <label>Localização</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nota_de_d_bito_ou_CTO__c</fullName>
        <label>Nota de débito ou CTO</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_OTN__c</fullName>
        <label>OTN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Observacao__c</fullName>
        <label>Observação</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Piso__c</fullName>
        <label>Piso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1º andar</fullName>
                </value>
                <value>
                    <fullName>Subsolo</fullName>
                </value>
                <value>
                    <fullName>2º andar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Res_Perata__c</fullName>
        <label>Res Perata</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato assinado</fullName>
                </value>
                <value>
                    <fullName>Repasse</fullName>
                </value>
                <value>
                    <fullName>Vaga</fullName>
                </value>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Status_da_prospecao__c</fullName>
        <label>Prospecção/Proposta aprovada</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Subtipo__c</fullName>
        <label>Subtipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Âncora</fullName>
                </value>
                <value>
                    <fullName>Depósito</fullName>
                </value>
                <value>
                    <fullName>Megaloja</fullName>
                </value>
                <value>
                    <fullName>Quiosque</fullName>
                </value>
                <value>
                    <fullName>Satélite</fullName>
                </value>
                <value>
                    <fullName>Mega Banner</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Totem Digital</fullName>
                </value>
                <value>
                    <fullName>Adesivos de Mesa</fullName>
                </value>
                <value>
                    <fullName>Portas de Acesso</fullName>
                </value>
                <value>
                    <fullName>Totem Interno</fullName>
                </value>
                <value>
                    <fullName>Feiras e Eventos</fullName>
                </value>
                <value>
                    <fullName>Colunas Mall</fullName>
                </value>
                <value>
                    <fullName>Colunas Praça de Alimentação</fullName>
                </value>
                <value>
                    <fullName>Painel Backlight</fullName>
                </value>
                <value>
                    <fullName>Porta de Banheiro</fullName>
                </value>
                <value>
                    <fullName>Testeira</fullName>
                </value>
                <value>
                    <fullName>Espelho de Banheiro</fullName>
                </value>
                <value>
                    <fullName>Painel Fachada</fullName>
                </value>
                <value>
                    <fullName>Painel</fullName>
                </value>
                <value>
                    <fullName>Adoção de Espaço</fullName>
                </value>
                <value>
                    <fullName>Cancela Estacionamento</fullName>
                </value>
                <value>
                    <fullName>Painel Frontlight</fullName>
                </value>
                <value>
                    <fullName>Adesivo Piso</fullName>
                </value>
                <value>
                    <fullName>Escada Rolante</fullName>
                </value>
                <value>
                    <fullName>Display Mall</fullName>
                </value>
                <value>
                    <fullName>Panfletagem</fullName>
                </value>
                <value>
                    <fullName>Portas de Elevador</fullName>
                </value>
                <value>
                    <fullName>Display Mesa</fullName>
                </value>
                <value>
                    <fullName>Stand Temporário</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_de_tabela__c</fullName>
        <label>Valor de tabela</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_area_m2__c</fullName>
        <label>Área (m²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade_da_Cotacao__c.object
<CustomObject>
    <description>Objeto de junção entre propriedade e cotação</description>
    <fields>
        <fullName>TW1_Area__c</fullName>
        <label>Área</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Cotacao__c</fullName>
        <label>Cotação</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_fim__c</fullName>
        <label>Data de fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_inicio__c</fullName>
        <label>Data de início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Localizacao__c</fullName>
        <label>Localização</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade da Cotação</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propriedades da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>Sigla</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_PropriedadeMockGenerator_cls.cls
public class TW1_Ancar_PropriedadeMockGenerator_cls {
    
    //private static List<TW1_Shopping__c> shopping = [SELECT Id FROM TW1_Shopping__c LIMIT 1];
    
    public static TW1_Ancar_wrapRecodtypes rec = new TW1_Ancar_wrapRecodtypes();
    
    public static TW1_Shopping__c criaShopping(){
        
        TW1_Shopping__c vaShopping = new TW1_Shopping__c();
        vaShopping.Name = 'Shopping Teste';
        vaShopping.TW1_SGL_Empreendimento__c='ST';
        insert vaShopping;
        
        return vaShopping;
    }
    
    public static TW1_Propriedade__c getFeiraoMock(String quoteId)
    {
        List<RecordType> recordFeirao = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Prop_Feiras];
        
        TW1_Propriedade__c propriedade = new TW1_Propriedade__c (
            Name = 'ApexTest Propriedade 1',
            TW1_Status__c = 'Vaga',
            RecordTypeId = recordFeirao[0].Id,
            TW1_Shopping__c = criaShopping().Id          
        );
        insert propriedade;
        
        TW1_Propriedade_da_Cotacao__c cotProp = new TW1_Propriedade_da_Cotacao__c(
            TW1_Propriedade__c = propriedade.Id,
            TW1_Cotacao__c = quoteId,
            TW1_Data_de_inicio__c = Date.today(),
            TW1_Data_de_fim__c = Date.today().addDays(10),
            TW1_Localizacao__c = 'Localização',
            TW1_Valor__c = 16.20,
            TW1_Area__c = 40
        );        
        insert cotProp; 
        
        TW1_Propriedade__c prop = 
            [SELECT TW1_Piso__c, TW1_Shopping__c, TW1_Subtipo__c, TW1_area_m2__c, TW1_Observacao__c, TW1_Status__c,
             TW1_Ativa__c, TW1_Status_da_prospecao__c, TW1_AMM__c, TW1_Fundo__c, TW1_OTN__c, TW1_Condominio__c,
             TW1_Nota_de_d_bito_ou_CTO__c, TW1_Res_Perata__c, TW1_Valor_TR__c, TW1_Valor_de_tabela__c, TW1_IPTU__c, Name
             FROM TW1_Propriedade__c WHERE Id= :propriedade.Id];
        
        return prop;
    }
    
    public static TW1_Propriedade__c getMidiaMock(String quoteId)
    {
        List<RecordType> recordMidia = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Prop_Midia];
        
        TW1_Propriedade__c propriedade = new TW1_Propriedade__c (
            Name = 'DEV Propriedade Midia',
            TW1_Status__c = 'Vaga',
            RecordTypeId = recordMidia[0].Id,
            TW1_Shopping__c = criaShopping().Id 
        );
        insert propriedade;
        
        TW1_Propriedade_da_Cotacao__c cotProp = new TW1_Propriedade_da_Cotacao__c(
            TW1_Propriedade__c = propriedade.Id,
            TW1_Cotacao__c = quoteId,
            TW1_Data_de_inicio__c = Date.today(),
            TW1_Data_de_fim__c = Date.today().addDays(10),            
            TW1_Area__c = 40
        );        
        insert cotProp; 
        
        TW1_Propriedade__c prop = 
            [SELECT TW1_Piso__c, TW1_Shopping__c, TW1_Subtipo__c, TW1_area_m2__c, TW1_Observacao__c, TW1_Status__c,
             TW1_Ativa__c, TW1_Status_da_prospecao__c, TW1_AMM__c, TW1_Fundo__c, TW1_OTN__c, TW1_Condominio__c,
             TW1_Nota_de_d_bito_ou_CTO__c, TW1_Res_Perata__c, TW1_Valor_TR__c, TW1_Valor_de_tabela__c, TW1_IPTU__c, Name
             FROM TW1_Propriedade__c WHERE Id= :propriedade.Id];
        
        return prop;
    }
    
    public static TW1_Propriedade__c getLojaMock(String quoteId)
    {   
        List<RecordType> recordLoja = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Prop_Loja];
        
        TW1_Propriedade__c propriedade = new TW1_Propriedade__c (
            Name = 'ApexTest Propriedade 1',
            TW1_Status__c = 'Vaga',
            RecordTypeId = recordLoja[0].Id,
            TW1_Shopping__c = criaShopping().Id         
        );
        insert propriedade; 
        
        TW1_Propriedade_da_Cotacao__c cotProp = new TW1_Propriedade_da_Cotacao__c(
            TW1_Propriedade__c = propriedade.Id,
            TW1_Cotacao__c = quoteId,
            TW1_Data_de_inicio__c = Date.today(),
            TW1_Data_de_fim__c = Date.today().addDays(10), 
            TW1_Valor__c = 16.20,           
            TW1_Area__c = 40
        );        
        insert cotProp; 
        
        TW1_Propriedade__c prop = 
            [SELECT TW1_Piso__c, TW1_Shopping__c, TW1_Subtipo__c, TW1_area_m2__c, TW1_Observacao__c, TW1_Status__c,
             TW1_Ativa__c, TW1_Status_da_prospecao__c, TW1_AMM__c, TW1_Fundo__c, TW1_OTN__c, TW1_Condominio__c,
             TW1_Nota_de_d_bito_ou_CTO__c, TW1_Res_Perata__c, TW1_Valor_TR__c, TW1_Valor_de_tabela__c, TW1_IPTU__c, Name
             FROM TW1_Propriedade__c WHERE Id= :propriedade.Id];
        
        return prop;
    }
    
    public static TW1_Propriedade__c getMallMock(String quoteId)
    {   
        List<RecordType> recordMall = [SELECT Id FROM RecordType WHERE Name = :rec.rec_Prop_Mall];
        
        TW1_Propriedade__c propriedade = new TW1_Propriedade__c (
            Name = 'ApexTest Propriedade 1',
            TW1_Status__c = 'Vaga',
            RecordTypeId = recordMall[0].Id,
            TW1_Shopping__c = criaShopping().Id          
        );
        insert propriedade;
        
        TW1_Propriedade_da_Cotacao__c cotProp = new TW1_Propriedade_da_Cotacao__c(
            TW1_Propriedade__c = propriedade.Id,
            TW1_Cotacao__c = quoteId,
            TW1_Data_de_inicio__c = Date.today(),
            TW1_Data_de_fim__c = Date.today().addDays(10),            
            TW1_Area__c = 40
        );        
        insert cotProp; 
        
        TW1_Propriedade__c prop = 
            [SELECT TW1_Piso__c, TW1_Shopping__c, TW1_Subtipo__c, TW1_area_m2__c, TW1_Observacao__c, TW1_Status__c,
             TW1_Ativa__c, TW1_Status_da_prospecao__c, TW1_AMM__c, TW1_Fundo__c, TW1_OTN__c, TW1_Condominio__c,
             TW1_Nota_de_d_bito_ou_CTO__c, TW1_Res_Perata__c, TW1_Valor_TR__c, TW1_Valor_de_tabela__c, TW1_IPTU__c, Name
             FROM TW1_Propriedade__c WHERE Id= :propriedade.Id];
        
        return prop;
    }
    
    public static TW1_Calendario_de_propriedades__c getCalendarioOcupado(string idPropriedade, Date dataInicio, Date dataFim)
    {
        TW1_Calendario_de_propriedades__c calendario = new TW1_Calendario_de_propriedades__c();
        
        calendario.TW1_Propriedade__c = idPropriedade;
        calendario.TW1_Data_de_inicio__c = dataInicio;
        calendario.TW1_Data_de_fim__c = dataFim;
        calendario.TW1_Status__c ='Ocupada';
        insert calendario;
        
        return calendario;
    }
}