objects/TW1_Informacoes_historicas__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Marca__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marca</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>O valor preenchido no filtro não retornou nenhum registro existente.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Marca</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Informações históricas da propriedade</relationshipLabel>
        <relationshipName>Informacoes_historicas_da_propriedade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Informação histórica da propriedade</label>
    <nameField>
        <label>Ano/Mes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informações históricas da propriedade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_JuctionMarcaPlanoMix__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Marca__c</fullName>
        <label>Marca</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Plano de mix</relationshipLabel>
        <relationshipName>TW1_Marcas_e_Plano_de_mix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Plano_de_mix__c</fullName>
        <label>Plano de mix</label>
        <referenceTo>TW1_Plano_de_mix__c</referenceTo>
        <relationshipLabel>Marcas</relationshipLabel>
        <relationshipName>Marcas_e_Plano_de_mix</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Marca e Plano de mix</label>
    <nameField>
        <label>Marcas e Plano de mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marcas e Plano de mix</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Plano_de_mix__c.object
<CustomObject>
    <fields>
        <fullName>Ramo_de_atividade__c</fullName>
        <label>Ramo de atividade</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Plano de mix</label>
    <nameField>
        <label>Código Plano de mix</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de mix</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/getShoppingsBySegmento.cls
public with sharing class getShoppingsBySegmento {
	@AuraEnabled
    public static List<TW1_Shopping__c> getShoppingsBySegmento(String strSegmento){
       
        TW1_Plano_de_mix__c segmento = getSegmento(strSegmento);
        
        List<TW1_Informacoes_historicas__c> listaInformacoesHistoricas = 
            [
                SELECT TW1_Shopping__c
                FROM TW1_Informacoes_historicas__c
                WHERE TW1_Marca__c IN (
                	SELECT TW1_Marca__c
                    FROM TW1_JuctionMarcaPlanoMix__c
                    WHERE TW1_Plano_de_mix__c = :segmento.Id
                )
            ];
        
        List<Id> listaShoppingsIds = new List<Id>();
        for(TW1_Informacoes_historicas__c informacaoHistorica : listaInformacoesHistoricas){
            listaShoppingsIds.add(informacaoHistorica.TW1_Shopping__c);
        }
        
        List<TW1_Shopping__c> listaShoppings = [SELECT Id, Name FROM TW1_Shopping__c WHERE Id IN :listaShoppingsIds];
        
        return listaShoppings;
    }
    
    @AuraEnabled
    public static TW1_Plano_de_mix__c getSegmento(String strSegmento){

        List<TW1_Plano_de_mix__c> listaSegmentosEqual = [SELECT Name FROM TW1_Plano_de_mix__c WHERE Ramo_de_atividade__c = :strSegmento];

        if(listaSegmentosEqual.size() >= 1){
            return listaSegmentosEqual.get(0);
        }else{
            String strSegmentoLike = '%' + strSegmento + '%';
            List<TW1_Plano_de_mix__c> listaSegmentosLike = [SELECT Name,Ramo_de_atividade__c FROM TW1_Plano_de_mix__c WHERE Ramo_de_atividade__c LIKE :strSegmentoLike ];
            
            if(listaSegmentosLike.size() >= 1){
                List<String> listaSegmentosLikeStr = new List<String>();
                for(TW1_Plano_de_mix__c segmentoLike : listaSegmentosLike){
                    listaSegmentosLikeStr.add(segmentoLike.Ramo_de_atividade__c);
                }
                Integer moreSimilarSegmentoIndex = Util.getClosestString(strSegmento, listaSegmentosLikeStr);
                
                return listaSegmentosLike.get(moreSimilarSegmentoIndex);
            }else{
                List<TW1_Plano_de_mix__c> listaSegmentosAll = [SELECT Ramo_de_atividade__c FROM TW1_Plano_de_mix__c];
                
                List<String> listaSegmentosAllStr = new List<String>();
                for(TW1_Plano_de_mix__c segmentoAll : listaSegmentosAll){
                    listaSegmentosAllStr.add(segmentoAll.Ramo_de_atividade__c);
                }
                
                Integer moreSimilarSegmentoIndex = Util.getClosestString(strSegmento, listaSegmentosAllStr);
                
                return listaSegmentosAll.get(moreSimilarSegmentoIndex);
                
            }
        }
    }
}