objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato assinado</fullName>
                </value>
                <value>
                    <fullName>Repasse</fullName>
                </value>
                <value>
                    <fullName>Vaga</fullName>
                </value>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>Sigla</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_InfHistProp_Rep_Test.cls
@isTest
public class TW1_Ancar_Venda_InfHistProp_Rep_Test {
	
    @isTest
    public static void ListarInformacoesHistoricas_Test() {
      
        list<String> propriedades = new list<String>();
        propriedades.add('0000000011');
        propriedades.add('0000000012');
        propriedades.add('0000000013');

        TW1_Ancar_Venda_InfHistProp_Rep infoRep = new TW1_Ancar_Venda_InfHistProp_Rep();
        list<TW1_Propriedade__c> listadeProprieade = infoRep.ListarInformacoesHistoricas('', propriedades);
    	System.debug('saida de propriedade '+listadeProprieade);
        System.assert(listadeProprieade==null);
        
    }
    
    @isTest
    public static void ListarInformacoesHistoricas_Test2() {
     
        TW1_Shopping__c vaShopping = new TW1_Shopping__c();
        vaShopping.Name = 'Shopping Teste';
        vaShopping.TW1_SGL_Empreendimento__c='ST';
        insert vaShopping;
        
        TW1_Propriedade__c propriedade = new TW1_Propriedade__c (
            Name = 'ApexTest Propriedade 1',
            TW1_Status__c = 'Vaga',
            TW1_Shopping__c = vaShopping.Id          
        );
        insert propriedade;
        
        TW1_Propriedade__c propriedade2 = new TW1_Propriedade__c (
            Name = 'ApexTest Propriedade 2',
            TW1_Status__c = 'Vaga',
            TW1_Shopping__c = vaShopping.Id          
        );
        insert propriedade2;
        
        list<String> propriedades = new list<String>();
        propriedades.add(propriedade.Id);
        propriedades.add(propriedade2.Id);
        
        TW1_Ancar_Venda_InfHistProp_Rep infoRep = new TW1_Ancar_Venda_InfHistProp_Rep();
        list<TW1_Propriedade__c> listadeProprieade = infoRep.ListarInformacoesHistoricas('', propriedades);
    	System.debug('saida de propriedade '+listadeProprieade);
        System.assert(listadeProprieade!=null);
        
    }
    @isTest
    public static void ListarInformacoesHistoricas_Test3() {
        
        TW1_Ancar_Venda_InfHistProp_Rep infoRep = new TW1_Ancar_Venda_InfHistProp_Rep();
        list<TW1_Propriedade__c> listadeProprieade = infoRep.ListarInformacoesHistoricas('', null);
        
    }    
        
}