objects/TW1_Caixa__c.object
<CustomObject>
    <fields>
        <fullName>TW1_CxFechado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CaixaFechado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_Abertura__c</fullName>
        <label>Data de Abertura</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Operador__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operador</label>
        <referenceTo>TW1_Operador__c</referenceTo>
        <relationshipLabel>Caixas</relationshipLabel>
        <relationshipName>Caixas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_Total_Sum__c</fullName>
        <label>Valor Total</label>
        <summarizedField>TW1_Extrato__c.TW1_Valor__c</summarizedField>
        <summaryFilterItems>
            <field>TW1_Extrato__c.TW1_Tipo__c</field>
            <operation>equals</operation>
            <value>Valor do Brinde</value>
        </summaryFilterItems>
        <summaryForeignKey>TW1_Extrato__c.TW1_Caixa__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_de_Abertura_Sum__c</fullName>
        <label>Valor de Abertura</label>
        <summarizedField>TW1_Extrato__c.TW1_Valor__c</summarizedField>
        <summaryFilterItems>
            <field>TW1_Extrato__c.TW1_Tipo__c</field>
            <operation>equals</operation>
            <value>Valor de Abertura</value>
        </summaryFilterItems>
        <summaryForeignKey>TW1_Extrato__c.TW1_Caixa__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Caixa</label>
    <nameField>
        <label>Nome de Caixa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Caixas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Extrato__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Caixa__c</fullName>
        <label>Caixa</label>
        <referenceTo>TW1_Caixa__c</referenceTo>
        <relationshipName>Estratos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Data__c</fullName>
        <label>Data</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TW1_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ValorAbertura</fullName>
                </value>
                <value>
                    <fullName>ValorBrinde</fullName>
                </value>
                <value>
                    <fullName>ValorFechamento</fullName>
                </value>
                <value>
                    <fullName>ValorEstorno</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Extrato</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número do Estrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Operador__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operador</fullName>
                </value>
                <value>
                    <fullName>Coordenador</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operador</label>
    <nameField>
        <label>Nome do Operador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Terminal__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Operador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operador</label>
        <referenceTo>TW1_Operador__c</referenceTo>
        <relationshipLabel>Terminais</relationshipLabel>
        <relationshipName>Terminais</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Terminal</label>
    <nameField>
        <label>Nome do Terminal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terminais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FluxoCaixaManager.cls
/******************************************************************************************************
Author  	: Leonardo Façanha
Date    	: 05/01/2017
Purpose 	: Api Rest para buscar/Inserir informações do fluxo de Caixa para a aplicação de promoção
*******************************************************************************************************/
@RestResource(urlMapping='/FluxoCaixa/*')
global with sharing class FluxoCaixaManager {
    
    
    @HttpGet
    global static string getAberturaCaixaPorId(){
        RestRequest req = RestContext.request;
        
        String vaTerminalId = req.params.get('IdTerminal');
        String vaOperadorId = req.params.get('IdOperador');
        String vaValor = req.params.get('Valor');
        string TipoOperacao = req.params.get('TipoOperacao');
        
        If((vaTerminalId != null && vaTerminalId != '' && vaTerminalId != 'null') && (vaOperadorId != null && vaOperadorId != '' && vaOperadorId != 'null') && (vaValor != null && vaValor != '' && vaValor != 'null') && TipoOperacao == null){
            
            TW1_Terminal__c terminal = new TW1_Terminal__c();
            terminal.Id = vaTerminalId;
            terminal.TW1_Operador__c = vaOperadorId;
            Update terminal;
            
            TW1_Caixa__c caixa = new TW1_Caixa__c();
            caixa.TW1_Operador__c = vaOperadorId;
            caixa.TW1_Data_de_Abertura__c = DateTime.now().date();
            caixa.Name = terminal.Name;
            insert caixa;
            
            TW1_Extrato__c extrato = new TW1_Extrato__c();
            extrato.TW1_Tipo__c = 'ValorAbertura';
            extrato.TW1_Valor__c = Decimal.valueOf(vaValor);
            extrato.TW1_Data__c = datetime.now();
            extrato.TW1_Caixa__c = caixa.Id;
            
            insert extrato;
            
            return 'Caixa aberto com sucesso!';
        }
        
         Savepoint sp = Database.setSavepoint();
        
        try{

          If((vaTerminalId != null && vaTerminalId != '' && vaTerminalId != 'null') && (vaOperadorId != null && vaOperadorId != '' && vaOperadorId != 'null') && (vaValor != null && vaValor != '' && vaValor != 'null')){
          	
              TW1_Caixa__c caixa = [Select Id,Name from TW1_Caixa__c where TW1_Operador__c=:vaOperadorId order by CreatedDate desc limit 1];
              TW1_Terminal__c terminal = [select Id from TW1_Terminal__c where TW1_Operador__c=:vaOperadorId limit 1];
              
              caixa.TW1_CxFechado__c = true;
              
              TW1_Extrato__c extrato = new TW1_Extrato__c();
              extrato.TW1_Caixa__c = caixa.Id;
              extrato.TW1_Data__c = DateTime.now();
              extrato.TW1_Tipo__c = 'ValorFechamento';
              extrato.TW1_Valor__c = double.valueOf(vaValor);
              
              terminal.TW1_Operador__c = null;
              
              update caixa;
              update terminal;
              insert extrato;
              return 'Caixa fechado com sucesso!';
          }
               }catch (Exception ce) {
                    Database.rollback(sp);
                    return 'Erro na operação: '+ce.getMessage();
            }  

        
        if(TipoOperacao != null && vaTerminalId == null)
        {
            TW1_Caixa__c caixa = [Select Id,Name,TW1_Valor_de_Abertura_Sum__c,TW1_Valor_Total_Sum__c from TW1_Caixa__c where TW1_Operador__c=:vaOperadorId order by CreatedDate desc limit 1];
            
            string infCaixa = caixa.TW1_Valor_de_Abertura_Sum__c+';'+caixa.TW1_Valor_Total_Sum__c;
                
            return infCaixa;
        }
        
        return 'Erro na operação!';
    } 
}