objects/TW1_Caixa__c.object
<CustomObject>
    <fields>
        <fullName>TW1_CxFechado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CaixaFechado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Operador__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operador</label>
        <referenceTo>TW1_Operador__c</referenceTo>
        <relationshipLabel>Caixas</relationshipLabel>
        <relationshipName>Caixas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Caixa</label>
    <nameField>
        <label>Nome de Caixa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Caixas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Operador__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Email__c</fullName>
        <externalId>true</externalId>
        <label>E-mail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Empresa__c</fullName>
        <label>Empresa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_do_Usuario__c</fullName>
        <label>Nome do Usuário</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Senha__c</fullName>
        <externalId>true</externalId>
        <label>Senha</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Operadores</relationshipLabel>
        <relationshipName>Operadores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operador</fullName>
                </value>
                <value>
                    <fullName>Coordenador</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operador</label>
    <nameField>
        <label>Nome do Operador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Parametros_Promocao__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Acumula_Saldo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Acumula Saldo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_CampoVendedor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Campo Vendedor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Concurso_Cultural__c</fullName>
        <label>Concurso Cultural</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sim</fullName>
                </value>
                <value>
                    <fullName>Não</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Contabiliza_Bonus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Considerar condição especial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Formas_de_Pagamento__c</fullName>
        <label>Formas de Pagamento</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                </value>
                <value>
                    <fullName>Cartão Credito</fullName>
                </value>
                <value>
                    <fullName>Cartão Debito</fullName>
                </value>
                <value>
                    <fullName>Cartão Caixa</fullName>
                </value>
                <value>
                    <fullName>Cartão Caixa ELO</fullName>
                </value>
                <value>
                    <fullName>Visa Vale</fullName>
                </value>
                <value>
                    <fullName>VISA PLATINUM</fullName>
                </value>
                <value>
                    <fullName>VISA INFINITE</fullName>
                </value>
                <value>
                    <fullName>CLUBE RIO DESIGN</fullName>
                </value>
                <value>
                    <fullName>Dinheiro(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Débito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito(FDS)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Imprimir_nome_do_lojista__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imprimir nome do lojista?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipName>Promo_es</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Troca_por__c</fullName>
        <label>Troca por</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Brinde</fullName>
                </value>
                <value>
                    <fullName>Cupom</fullName>
                </value>
                <value>
                    <fullName>Ambos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parâmetros da Promoção</label>
    <nameField>
        <label>Nome da Promoção</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parâmetros da Promoções</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LoginManager.cls
/******************************************************************************************************
Author  : Leonardo Façanha
Date    : 05/12/2017
Update	: 27/12/2017 por Wellington Rodrigues - linha:[23,25]
Purpose : Api Rest para buscar informações do Usuario para a aplicação de promoção
*******************************************************************************************************/
@RestResource(urlMapping='/Login')
global with sharing class LoginManager {
    
    @HttpPost
    global static List<string> doLogin(string login,string senha,string shopping){
        
        List<String> arrayOfoperdaor = new List<String>();
        
        if(login == '' || senha == '' || shopping == ''){
            arrayOfoperdaor.add('Erro - Campos em branco');
            return arrayOfoperdaor;
        }
        
        try{

            date vaData = DateTime.now().date();  
            TW1_Operador__c operador = [Select Id,Name,TW1_Email__c,TW1_Empresa__c,TW1_Nome_do_Usuario__c,TW1_Shopping__c,TW1_Tipo__c From TW1_Operador__c Where TW1_Tipo__c!='Coordenador' And TW1_Email__c=:login And TW1_Senha__c=:senha And TW1_Shopping__c=:shopping limit 1];
            
            TW1_Parametros_Promocao__c promocao = [Select Id,Name,TW1_Imprimir_nome_do_lojista__c,TW1_CampoVendedor__c,TW1_Troca_por__c,TW1_Acumula_Saldo__c,TW1_Contabiliza_Bonus__c,TW1_Formas_de_Pagamento__c,TW1_Concurso_Cultural__c,CreatedDate from TW1_Parametros_Promocao__c where TW1_Shopping__c=:operador.TW1_Shopping__c And TW1_Data_Fim__c >=:vaData Order By CreatedDate Desc limit 1];
           
            List<TW1_Caixa__c> vaCaixa = [select Id,TW1_CxFechado__c From TW1_Caixa__c where CreatedDate>=:vaData And TW1_Operador__c=:operador.id];
            
            if(operador != null || Shopping != null){
                
                If(promocao!=null){
                    arrayOfoperdaor.add(operador.Id);
                    arrayOfoperdaor.add(operador.Name);
                    arrayOfoperdaor.add(operador.TW1_Email__c);
                    arrayOfoperdaor.add(operador.TW1_Empresa__c);
                    arrayOfoperdaor.add(operador.TW1_Tipo__c);
                    arrayOfoperdaor.add(operador.TW1_Shopping__c);
                    arrayOfoperdaor.add(operador.TW1_Nome_do_Usuario__c);
                    arrayOfoperdaor.add(promocao.Id);
                    arrayOfoperdaor.add(promocao.TW1_Troca_por__c);
                    arrayOfoperdaor.add(promocao.TW1_Formas_de_Pagamento__c);
                    arrayOfoperdaor.add(promocao.TW1_Concurso_Cultural__c);
                    arrayOfoperdaor.add(String.valueOf(promocao.TW1_Contabiliza_Bonus__c));
                    arrayOfoperdaor.add(String.valueOf(promocao.TW1_Acumula_Saldo__c));
                    if(vaCaixa.size() >= 1){
                    if(!vaCaixa.get(0).TW1_CxFechado__c){
                        arrayOfoperdaor.add('CaixaAberto');
                    }
                    else {
                        arrayOfoperdaor.add('CaixaFechado');
                    }
                    }else {
                        arrayOfoperdaor.add('CaixaFechado');
                    }
                    arrayOfoperdaor.add('Aberto com Sucesso');
                    arrayOfoperdaor.add(promocao.Name);
                    arrayOfoperdaor.add(String.valueOf(promocao.TW1_CampoVendedor__c));
                    arrayOfoperdaor.add(String.valueOf(promocao.TW1_Imprimir_nome_do_lojista__c));
                }else{
                    arrayOfoperdaor.add('Não existe promoção para este shopping');
                    return arrayOfoperdaor;
                }
                
                return arrayOfoperdaor;
            }           
            
        }Catch(Exception err){
            arrayOfoperdaor.add('Erro no login - Verifique seu usuário e senha ou se o shopping tem promoção vigente!');
            return arrayOfoperdaor;
        }

        return arrayOfoperdaor;
    }
}