objects/TW1_Calendario_de_propriedades__c.object
<CustomObject>
    <description>Objeto que deve registrar o calendário de locação das propriedades.</description>
    <fields>
        <fullName>TW1_Data_de_fim__c</fullName>
        <label>Data de fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_inicio__c</fullName>
        <label>Data de início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Calendário de propriedades</relationshipLabel>
        <relationshipName>Calendario_de_propriedades</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_ShoppingId__c</fullName>
        <formula>TW1_Propriedade__r.TW1_Shopping__c</formula>
        <label>ShoppingId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calendário de propriedade</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calendário de propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_AMM__c</fullName>
        <label>AMM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Ativa__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ativa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Condominio__c</fullName>
        <label>Condominio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Fundo__c</fullName>
        <label>Fundo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_IPTU__c</fullName>
        <label>IPTU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Localizacao__c</fullName>
        <label>Localização</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nota_de_d_bito_ou_CTO__c</fullName>
        <label>Nota de débito ou CTO</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_OTN__c</fullName>
        <label>OTN</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Observacao__c</fullName>
        <label>Observação</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Piso__c</fullName>
        <label>Piso</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1º andar</fullName>
                </value>
                <value>
                    <fullName>Subsolo</fullName>
                </value>
                <value>
                    <fullName>2º andar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Res_Perata__c</fullName>
        <label>Res Perata</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Propriedades</relationshipLabel>
        <relationshipName>Propriedades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contrato assinado</fullName>
                </value>
                <value>
                    <fullName>Repasse</fullName>
                </value>
                <value>
                    <fullName>Vaga</fullName>
                </value>
                <value>
                    <fullName>Ocupada</fullName>
                </value>
                <value>
                    <fullName>Reservada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Status_da_prospecao__c</fullName>
        <label>Prospecção/Proposta aprovada</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Subtipo__c</fullName>
        <label>Subtipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Âncora</fullName>
                </value>
                <value>
                    <fullName>Depósito</fullName>
                </value>
                <value>
                    <fullName>Megaloja</fullName>
                </value>
                <value>
                    <fullName>Quiosque</fullName>
                </value>
                <value>
                    <fullName>Satélite</fullName>
                </value>
                <value>
                    <fullName>Mega Banner</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Totem Digital</fullName>
                </value>
                <value>
                    <fullName>Adesivos de Mesa</fullName>
                </value>
                <value>
                    <fullName>Portas de Acesso</fullName>
                </value>
                <value>
                    <fullName>Totem Interno</fullName>
                </value>
                <value>
                    <fullName>Feiras e Eventos</fullName>
                </value>
                <value>
                    <fullName>Colunas Mall</fullName>
                </value>
                <value>
                    <fullName>Colunas Praça de Alimentação</fullName>
                </value>
                <value>
                    <fullName>Painel Backlight</fullName>
                </value>
                <value>
                    <fullName>Porta de Banheiro</fullName>
                </value>
                <value>
                    <fullName>Testeira</fullName>
                </value>
                <value>
                    <fullName>Espelho de Banheiro</fullName>
                </value>
                <value>
                    <fullName>Painel Fachada</fullName>
                </value>
                <value>
                    <fullName>Painel</fullName>
                </value>
                <value>
                    <fullName>Adoção de Espaço</fullName>
                </value>
                <value>
                    <fullName>Cancela Estacionamento</fullName>
                </value>
                <value>
                    <fullName>Painel Frontlight</fullName>
                </value>
                <value>
                    <fullName>Adesivo Piso</fullName>
                </value>
                <value>
                    <fullName>Escada Rolante</fullName>
                </value>
                <value>
                    <fullName>Display Mall</fullName>
                </value>
                <value>
                    <fullName>Panfletagem</fullName>
                </value>
                <value>
                    <fullName>Portas de Elevador</fullName>
                </value>
                <value>
                    <fullName>Display Mesa</fullName>
                </value>
                <value>
                    <fullName>Stand Temporário</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Valor_TR__c</fullName>
        <label>Valor TR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_de_tabela__c</fullName>
        <label>Valor de tabela</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_area_m2__c</fullName>
        <label>Área (m²)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade</label>
    <nameField>
        <label>Nº da Propriedade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Propriedades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Propriedade_da_Cotacao__c.object
<CustomObject>
    <description>Objeto de junção entre propriedade e cotação</description>
    <fields>
        <fullName>TW1_Area__c</fullName>
        <label>Área</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Cotacao__c</fullName>
        <label>Cotação</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_fim__c</fullName>
        <label>Data de fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_inicio__c</fullName>
        <label>Data de início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Localizacao__c</fullName>
        <label>Localização</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Propriedade__c</fullName>
        <label>Propriedade</label>
        <referenceTo>TW1_Propriedade__c</referenceTo>
        <relationshipLabel>Propriedades da Cotação</relationshipLabel>
        <relationshipName>Propriedades_da_Cotacao</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Propriedade da Cotação</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Propriedades da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Shopping__c.object
<CustomObject>
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TW1_Ancar_Venda_Propriedade_Rep.cls
public class TW1_Ancar_Venda_Propriedade_Rep {
    
    public TW1_Propriedade__c GetPropriedadeCotacaoLoja(string vaCotacaoId)
    {
        TW1_Propriedade_da_Cotacao__c Consulta = [SELECT Id,TW1_Propriedade__c FROM TW1_Propriedade_da_Cotacao__c WHERE TW1_Cotacao__c= :vaCotacaoId limit 1];
        
        if(Consulta != null)
            return GetPropriedadeById(Consulta.TW1_Propriedade__c);
        else
            return null;
    }
    
    public TW1_Propriedade__c GetPropriedadeByIdCotacaoMALL(string vaCotacaoId)
    {
        try{
            TW1_Propriedade_da_Cotacao__c listaConsulta = [SELECT TW1_Propriedade__c FROM TW1_Propriedade_da_Cotacao__c WHERE TW1_Cotacao__c= :vaCotacaoId limit 1];
            
            
            
            TW1_Propriedade__c vaPropriedade = [
                Select
                id,
                Name,
                TW1_Shopping__c,
                TW1_Subtipo__c,
                TW1_Piso__c,
                TW1_area_m2__c, 
                TW1_Observacao__c,
                TW1_Status__c,
                TW1_Ativa__c,
                TW1_Status_da_prospecao__c,
                TW1_AMM__c,
                TW1_Fundo__c,
                TW1_OTN__c,
                TW1_Condominio__c,
                TW1_Nota_de_d_bito_ou_CTO__c,
                TW1_Res_Perata__c,
                TW1_IPTU__c,
                TW1_Valor_TR__c,
                TW1_Valor_de_tabela__c,
                TW1_Localizacao__c
                from 
                TW1_Propriedade__c 
                where
                Id=:listaConsulta.TW1_Propriedade__c limit 1];
            
            return vaPropriedade;
            
        }catch(Exception ex){
            system.debug('Erro em consultar ListarPropriedadeLoja EX:' +ex);
            return null;
        }
        
    }
    
    public List<TW1_Propriedade_da_Cotacao__c> GetPropriedadeCotacao(string vaCotacaoId)
    {
        List<TW1_Propriedade_da_Cotacao__c> listaConsulta = [SELECT Id,TW1_Data_de_fim__c,TW1_Data_de_inicio__c,TW1_Valor__c,TW1_Propriedade__c,TW1_Localizacao__c,TW1_Area__c FROM TW1_Propriedade_da_Cotacao__c WHERE TW1_Cotacao__c= :vaCotacaoId];
        
        
        if(listaConsulta.size()  > 0)
            return listaConsulta;
        else
            return null;
    }
    
    public List<SObject> ListarPropriedadeLoja(Id idShopping)
    {
        try{
            
            List<TW1_Propriedade__c> vaPropriedade = [
                Select
                id,
                Name,
                TW1_Shopping__c,
                TW1_Subtipo__c,
                TW1_Piso__c,
                TW1_area_m2__c, 
                TW1_Observacao__c,
                TW1_Status__c,
                TW1_Ativa__c,
                TW1_Status_da_prospecao__c,
                TW1_AMM__c,
                TW1_Fundo__c,
                TW1_OTN__c,
                TW1_Condominio__c,
                TW1_Nota_de_d_bito_ou_CTO__c,
                TW1_Res_Perata__c,
                TW1_IPTU__c,
                TW1_Valor_TR__c,
                TW1_Valor_de_tabela__c
                from 
                TW1_Propriedade__c 
                where
                TW1_Ativa__c = true and
                TW1_Shopping__c =:idShopping and 
                (
                    TW1_Status__c='Vaga' or 
                    TW1_Status__c='Repasse'
                ) and
                (
                    TW1_Subtipo__c ='Âncora' or
                    TW1_Subtipo__c ='Megaloja' or
                    TW1_Subtipo__c ='Satélite'
                )
            ];
            
            System.debug('Propriedade loja' + vaPropriedade);
            if(vaPropriedade.size() >= 1){
                return vaPropriedade;
            }else{
                return null;
            }
            
        }catch(Exception ex){
            system.debug('Erro em consultar ListarPropriedadeLoja EX:' +ex);
            return null;
        }
    }
    
    public TW1_Propriedade__c GetPropriedadeById(Id idPropriedade)
    {
        List<TW1_Propriedade__c> listaConsulta = [SELECT TW1_Piso__c,
                                                  TW1_Shopping__c,
                                                  TW1_Subtipo__c,
                                                  TW1_area_m2__c, 
                                                  TW1_Observacao__c,
                                                  TW1_Status__c,
                                                  TW1_Ativa__c,
                                                  TW1_Status_da_prospecao__c,
                                                  TW1_AMM__c,
                                                  TW1_Fundo__c,
                                                  TW1_OTN__c,
                                                  TW1_Condominio__c,
                                                  TW1_Nota_de_d_bito_ou_CTO__c,
                                                  TW1_Res_Perata__c,
                                                  TW1_Valor_TR__c,
                                                  TW1_Valor_de_tabela__c,
                                                  TW1_IPTU__c,Name
                                                  FROM TW1_Propriedade__c WHERe id= :idPropriedade];
        
        if(listaConsulta.size()  > 0)
            return listaConsulta[0];
        else
            return null;
    }
    
    public List<SObject> ListarPorpriedadeMidiaFeira(Id idShopping, String paPropriedadeSubtipo, Date paDtini, Date paDtfim)
    {
        string IdShoppingsub = idShopping;
        IdShoppingsub = IdShoppingsub.substring(0,15);
        
        try{
            List<TW1_Propriedade__c> vaPropriedade = [
                select 
                Id,
                Name,
                TW1_Shopping__c,
                TW1_Subtipo__c,
                TW1_Piso__c,
                TW1_area_m2__c, 
                TW1_Observacao__c,
                TW1_Status__c,
                TW1_Ativa__c,
                TW1_Status_da_prospecao__c,
                TW1_AMM__c,
                TW1_Fundo__c,
                TW1_OTN__c,
                TW1_Condominio__c,
                TW1_Nota_de_d_bito_ou_CTO__c,
                TW1_Res_Perata__c,
                TW1_IPTU__c,
                TW1_Valor_TR__c,
                TW1_Valor_de_tabela__c,
                TW1_Localizacao__c
                from 
                TW1_Propriedade__c
                where
                TW1_Ativa__c = true and
                TW1_Subtipo__c=:paPropriedadeSubtipo and
                TW1_Shopping__c=:idShopping 
                and
                Id NOT IN
                (Select TW1_Propriedade__c from TW1_Calendario_de_propriedades__c 
                 where TW1_ShoppingId__c=:IdShoppingsub and 
                 TW1_Data_de_inicio__c <=:paDtfim and
                 TW1_Data_de_fim__c >=:paDtini and 
                 TW1_Status__c ='Ocupada'
                )
            ];	
            
            
            
            if(vaPropriedade.size() >= 1){
                return vaPropriedade;
            }else{
                return null;
            }
            
        }catch(Exception ex){
            return null;
        }
    }
    
    public List<SObject> ListarPorpriedadeMidiaFeiraOcupadas(Id idShopping, String paPropriedadeSubtipo, Date paDtini, Date paDtfim)
    {
        string IdShoppingsub = idShopping;
        IdShoppingsub = IdShoppingsub.substring(0,15);
        
        try{
            List<TW1_Propriedade__c> vaPropriedade = [
                select 
                Id,
                Name,
                TW1_Shopping__c,
                TW1_Subtipo__c,
                TW1_Piso__c,
                TW1_area_m2__c, 
                TW1_Observacao__c,
                TW1_Status__c,
                TW1_Ativa__c,
                TW1_Status_da_prospecao__c,
                TW1_AMM__c,
                TW1_Fundo__c,
                TW1_OTN__c,
                TW1_Condominio__c,
                TW1_Nota_de_d_bito_ou_CTO__c,
                TW1_Res_Perata__c,
                TW1_IPTU__c,
                TW1_Valor_TR__c,
                TW1_Valor_de_tabela__c,
                TW1_Localizacao__c
                from 
                TW1_Propriedade__c
                where
                TW1_Ativa__c = true and
                TW1_Subtipo__c=:paPropriedadeSubtipo and
                TW1_Shopping__c=:idShopping 
                and
                Id IN
                (Select TW1_Propriedade__c from TW1_Calendario_de_propriedades__c 
                 where TW1_ShoppingId__c=:IdShoppingsub and 
                 TW1_Data_de_inicio__c <=:paDtfim and
                 TW1_Data_de_fim__c >=:paDtini and 
                 TW1_Status__c ='Ocupada'
                )
            ];	
            
            if(vaPropriedade.size() >= 1){
                return vaPropriedade;
            }else{
                return null;
            }
            
        }catch(Exception ex){
            return null;
        }
    }
    
    public List<SObject> ListarPropriedadeMall(Id idShopping, String paPropriedadeSubtipo)
    {
        try{
            List<TW1_Propriedade__c> vaPropriedade = [
                SELECT 
                id,
                Name,
                TW1_Shopping__c,
                TW1_Subtipo__c,
                TW1_Piso__c,
                TW1_area_m2__c, 
                TW1_Observacao__c,
                TW1_Status__c,
                TW1_Ativa__c,
                TW1_Status_da_prospecao__c,
                TW1_AMM__c,
                TW1_Fundo__c,
                TW1_OTN__c,
                TW1_Condominio__c,
                TW1_Nota_de_d_bito_ou_CTO__c,
                TW1_Res_Perata__c,
                TW1_IPTU__c,
                TW1_Valor_TR__c,
                TW1_Valor_de_tabela__c,
                TW1_Localizacao__c
                from 
                TW1_Propriedade__c
                where
                TW1_Ativa__c = true and
                TW1_Subtipo__c =:paPropriedadeSubtipo and
                TW1_Shopping__c =:idShopping]; 
            
            if(vaPropriedade.size() >= 1){
                return vaPropriedade;
            }else{
                return null;
            }
            
        }catch(Exception ex){
            return null;
        }
        
    }
    
    public List<TW1_Calendario_de_propriedades__c> ListaPeriodosOcupacao(string idPropriedade, Date dataInicio, Date dataFim)
    {
        List<TW1_Calendario_de_propriedades__c> listaRetorno = [SELECT 
                                                                TW1_Propriedade__c,
                                                                TW1_Data_de_inicio__c,
                                                                TW1_Data_de_fim__c,
                                                                TW1_Status__c
                                                                FROM TW1_Calendario_de_propriedades__c 
                                                                where TW1_Propriedade__c=:idPropriedade and 
                                                                TW1_Data_de_inicio__c <=:dataFim and
                                                                TW1_Data_de_fim__c >=:dataInicio and 
                                                                TW1_Status__c ='Ocupada'];
        
        if(listaRetorno.size() > 0)
            return listaRetorno;
        else
            return null;
    }
    
}