objects/TW1_Cartoes_Estacionamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_inicio__c</fullName>
        <label>Data início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Fidelidade__c</fullName>
        <label>Número Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cartões Estacionamento</relationshipLabel>
        <relationshipName>Cart_es_Estacionamento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Inativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cartão Estacionamento</label>
    <nameField>
        <label>Número do cartão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões Estacionamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Fidelidade__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Historico__c</fullName>
        <label>Histórico</label>
        <summarizedField>TW1_Historico__c.TW1_Pontos__c</summarizedField>
        <summaryFilterItems>
            <field>TW1_Historico__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cadastro de NTFS</value>
        </summaryFilterItems>
        <summaryForeignKey>TW1_Historico__c.TW1_Fidelidade__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TW1_Modalidade__c</fullName>
        <label>Modalidade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Saldo__c</fullName>
        <label>Saldo</label>
        <summarizedField>TW1_Historico__c.TW1_Pontos__c</summarizedField>
        <summaryForeignKey>TW1_Historico__c.TW1_Fidelidade__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fidelidade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número Fidelidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidelidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

groups/flowDefinitions/objects/TW1_Historico__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Data__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Data</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <label>Fidelidade</label>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Históricos</relationshipLabel>
        <relationshipName>Hist_ricos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Pontos__c</fullName>
        <label>Pontos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Saldo__c</fullName>
        <formula>TW1_Fidelidade__r.TW1_Saldo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Saldo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Válida</fullName>
                    <default>true</default>
                    <label>Válida</label>
                </value>
                <value>
                    <fullName>Expirada</fullName>
                </value>
                <value>
                    <fullName>Utilizada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ajuste de Saldo</fullName>
                </value>
                <value>
                    <fullName>Aniversário</fullName>
                </value>
                <value>
                    <fullName>Cadastro de NTFS</fullName>
                </value>
                <value>
                    <fullName>Cartão Estacionamento</fullName>
                </value>
                <value>
                    <fullName>Saldo Inicial</fullName>
                </value>
                <value>
                    <fullName>Vinho</fullName>
                </value>
                <value>
                    <fullName>Nota Expirada</fullName>
                </value>
                <value>
                    <fullName>Ação Marketing</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Histórico</label>
    <nameField>
        <displayFormat>HIST-{00000000}</displayFormat>
        <label>Código Histórico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Anc_Fidelidade_Handler_cls.cls
global with sharing class Anc_Fidelidade_Handler_cls {

    @future
    public static void sendWithFuture(){
        executeJob();
    } 
    
    @testVisible
    private static void executeJob(){
        
        Anc_Utils_cls.LogToSystemDebug('Inicio do processamento Anc_Fidelidade_Handler_cls.sendWithFuture');
        try 
        {  
            // get data 
            Anc_Utils_cls.LogToSystemDebug('obtendo dados...');
            getDataToProcess();   
            Anc_Utils_cls.LogToSystemDebug('processando informação...');
        }
        catch(Anc_Utils_cls.Cal_Exception e)  
        {   
            System.debug('Anc_Fidelidade_Handler_cls.sendWithFuture error: ' + e.getMessage()); 
        }
        finally{
            if(!Test.isRunningTest())
                scheaduleJobAgain();
        }  
        Anc_Utils_cls.LogToSystemDebug('Fim do processamento Anc_Fidelidade_Handler_cls.sendWithFuture');
        
    }
    
    
    private static void getDataToProcess(){ 
        
        Map<ID, TW1_Fidelidade__c> MapFidelidade = new Map<ID, TW1_Fidelidade__c>([select TW1_Modalidade__c,TW1_Saldo__c from TW1_Fidelidade__c where TW1_Modalidade__c='Gold' Or TW1_Modalidade__c='Prospect' ORDER BY TW1_Saldo__c DESC limit 100]);
        SET<ID> keys = MapFidelidade.keyset();
        
        List<TW1_Fidelidade__c> ListFidelidade = new List<TW1_Fidelidade__c>();
        List<TW1_Cartoes_Estacionamento__c> cartoes = [select Id,TW1_Data_Fim__c,TW1_Data_inicio__c,TW1_Numero_Fidelidade__c from TW1_Cartoes_Estacionamento__c where TW1_Numero_Fidelidade__c IN :keys And TW1_Status__c ='Ativo'];
        
        List<TW1_Historico__c> ListaHistorico = new List<TW1_Historico__c>();
        
        RecordType recordtype = [Select Id,Name from RecordType where RecordType.Name = 'Cartão Estacionamento'];
        
        for(ID idKey : MapFidelidade.keyset())
        {
            TW1_Fidelidade__c Top100 = MapFidelidade.get(idKey);
            
            Top100.TW1_Modalidade__c = 'Platinum';
            ListFidelidade.add(Top100);
            
            TW1_Historico__c historico = new TW1_Historico__c();
            historico.TW1_Fidelidade__c = Top100.Id;
            historico.TW1_Tipo__c = 'Cartão Estacionamento';
            historico.TW1_Pontos__c = 0 - Top100.TW1_Saldo__c;
            historico.TW1_Data__c = DateTime.now().date();
            historico.RecordTypeId = recordtype.Id;
            ListaHistorico.add(historico);
        }
        
        for(TW1_Cartoes_Estacionamento__c Cartao : cartoes){
            MapFidelidade.remove(Cartao.TW1_Numero_Fidelidade__c);
            
            Cartao.TW1_Data_Fim__c = DateTime.now().addMonths(3).date();
            Cartao.TW1_Data_inicio__c = DateTime.now().date();
        }
         SET<ID> listkeys = MapFidelidade.keyset();
        
        For(ID fidel:listkeys)
        {
           TW1_Cartoes_Estacionamento__c cartao = new TW1_Cartoes_Estacionamento__c();
            cartao.TW1_Numero_Fidelidade__c = fidel;
            Cartao.TW1_Status__c = 'Ativo';
            cartao.TW1_Data_Fim__c = DateTime.now().addMonths(3).date();
            cartao.TW1_Data_inicio__c = DateTime.now().date();
            
            cartoes.add(cartao);
        }
        
        
        insert ListaHistorico;  
        Upsert cartoes Id;
        Update ListFidelidade;
    }
    
    private static void scheaduleJobAgain(){
        //Produção
        Anc_ScheaduleUtils_cls.scheadule('Anc_Fidelidade_sch', DateTime.now().addMonths(3));
    }
}